from rsf.tex import *

Paper('slides',
      lclass='cwpslides',
      use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy,comment,verbatim',
      include='\\newcommand{\\RSFSRC}{../../..}')
    
End()
