from rsf.proj import *
from rsf.gallery import teapot

teapot.get_vint1('Vint')

Result('Vint',
     '''
     graph  title="Interval Velocity" label1=Time unit1=s
     ''')
	
Fetch('final_stack.rsf','teapot',server='http://s3.amazonaws.com',top='')

Plot('final_stack',
     '''
     window j3=20 |
     grey title=stack
     label1=Time     unit1=sec 
     label2=xline    unit2=count
     ''',view=1)

Plot('final_stack_filter', 'final_stack',
     '''
     window j3=20 |
     bandpass fhi=20 |
     grey title=filterred_stack
     label1=Time    unit2=sec 
     label2=xline   unit1=count
      ''',view=1)

Flow ('spray2','Vint','spray axis=2 n=188 d=1 o=1')

Result('spray2',
     	'''
     	window j3=20 |
     	sfgrey color=j  title="Interval Velocity Interpolated" 
        scalebar=y mean=y barreverse=y
     	''')

Flow ('Vint3D','spray2','spray axis=3 n=345 d=1 o=1')

Result('Vint3D',
     '''
     sfbyte mean=y | sfgrey3 color=j flat=n title="Interval Velocity" 
     ''')


Flow('Vint3Dz','Vint3D','time2depth dz=30 intime=y nz=1200 velocity=$SOURCE')

Result('Vint3Dz',
     '''
     byte mean=y | sfgrey3 color=j  flat=n title="Interval Velocity"
     ''')

########    Change velocity to slowness  ##########################

Flow('slo','Vint3Dz','put d2=110 d3=110 | transp | transp plane=23 | math output=1/input')

Result('slo',
     '''
     byte mean=y gainpanel=all | sfgrey3 color=j  flat=n title="Interval Slowness" 
     ''')




########    FFT  ##########################





Flow('fft','final_stack',
     'put d2=110 d3=110 | fft1 | window max1=20 | transp plane=12 | transp plane=23')



Flow('real','fft','real')



Result('real',
     '''
     byte gainpanel=all | sfgrey3 flat=n title=FFT frame1=100 frame2=100 frame3=50
     ''')




# Extended split-step migration
# to run in parallel:
#  ~/RSFSRC/Zomig1 $ export RSF_THREADS=4
#  ~/RSFSRC/Zomig1 $ pscons mig_t.view

Flow('mig','fft slo',
     '''
     zomig3 ompnth=1 mode=m --readwrite=y verb=y
     nrmax=1 slo=${SOURCES[1]}
     ''',split=[3,87],reduce='add')

Plot('mig',
     '''
     window j3=20 | 
     grey title="Migration Depth Slices" gainpanel=all
     label2=Depth    unit2=ft 
     label1=Distance unit1=ft
     ''',view=1)

# ouput of migration is depth slices.  transpose back to y,x,z 
# (or z,x,y if you prefer fortran terminology)

Flow('mig_z','mig',
     'transp plane=23 | transp plane=12')

Plot('mig_z',
     '''
     window j3=20 | 
     grey title=Migration transp=y 
     label2=Depth    unit2=ft 
     label1=Distance unit1=ft
     ''',view=1)

Flow('mig_t','mig_z Vint3D','depth2time dt=.002 nt=2049 velocity=${SOURCES[1]}')

Plot('mig_t',
     '''
     window j3=20 n1=1501 |
     put d2=20 d3=20 |	
     grey title="Migration Data in Time" gainpanel=all
     label1=Time    unit1=s  
     label2=Trace unit2=num.
     ''',view=1)

Fetch('filt_mig.sgy','teapot',server='http://s3.amazonaws.com',top='')

Flow('filt_mig filt_mig_hdr filt_mig.asc filt_mig.bin','filt_mig.sgy',
     '''
     sfsegyread 
         tfile=${TARGETS[1]}
	 hfile=${TARGETS[2]}
	 bfile=${TARGETS[3]}
     | sfput n2=188 o2=1 n3=345 o3=1
     ''')
	
Plot('filt_mig',
     '''
     window j3=20 |
     grey title="Commercial Migration" gainpanel=all
     label1=Time     unit1=sec 
     label2=xline    unit2=count
     ''',view=1)

End()


