from rsfproj import *

Flow('spike',None,
     '''
     spike n1=100 n2=150 d1=0.004 d2=0.008
     nsp=1 k1=75 k2=75 | bandpass flo=10 fhi=50
     ''')

Flow('kirch1','spike',
     '''
     spray axis=2 o=0 n=1 | transp plane=24 |
     preconstkirch vel=2 | window |
     halfint inv=y adj=y
     ''')
Plot('kirch1','grey title="Kirchhoff 1"')

Flow('vel','spike','window n2=1 | math output=2')
Flow('kirch2','spike vel','kirchnew velocity=${SOURCES[1]}')
Plot('kirch2','grey title="Kirchhoff 2" ')

Plot('kirch','kirch1 kirch2','OverUnderAniso')

Flow('phase','spike vel',
     '''
     cosft sign2=1 | pad n1=400 |
     gazdag velocity=${SOURCES[1]} |
     window n1=100 | cosft sign2=-1
     ''')
Plot('phase','grey title="Phase Shift" ')

Flow('stolt','spike','cosft sign2=1 | stolt nf=4 vel=4 | cosft sign2=-1')
Plot('stolt','grey title=Stolt')

Plot('waves','phase stolt','OverUnderAniso')

Result('impls','kirch waves','SideBySideAniso')

End()
