from rsf.proj import *

size = int(ARGUMENTS.get('size',50))
half = size/2

n = size-1
d = 1.0/size

Flow('uniform',None,
     '''
     math n1=%d n2=%d n3=%d d1=%g d2=%g d3=%g 
     label1=X label2=Y label3=Z unit1=km unit2=km unit3=km \
     label=Velocity unit=km/s output=1
     ''' % (n,n,n,d,d,d))

# High-velocity separator
Flow('separ','uniform','cut max3=0.75 min2=0.25 max2=0.29')
Flow('separator','separ','math output="1e10*(1-input) + input"')


Result('separator',
       '''
       byte gainpanel=all mean=y | 
       grey3 frame1=%d frame2=%d frame3=%d color=j title=Separator screenratio=1
       ''' % (half,half,half))

Flow('solve','separator','mpipsp velocity=$SOURCE solution=$TARGET omega=60',stdin=0,stdout=-1,np=4)
Result('solve',
       '''
       real | byte gainpanel=all | 
       grey3 frame1=%d frame2=%d frame3=%d title=Separator screenratio=1
       ''' % (half,half,half))

End()
