from rsfproj import *
import math
import zomig,sgmig,pplot

# ------------------------------------------------------------
# PLOTTING
# ------------------------------------------------------------
def igrey(custom):
    return '''
    grey  labelrot=n wantaxis=y wanttitle=y title=""
    pclip=100
    min2=-1000 max2=1000 grid=y gridcol=0
    label1="z (m)" label2="x (m)"
    %s 
    ''' % (custom)
# ------------------------------------------------------------
par = {
    'nz':200,  'dz':5.0,  'oz':0,
    'nx':600,  'dx':5.0,  'ox':-1500,
    'nt':1000, 'dt':0.004,'ot':0, 'kt':201,
#
    'nw':256, 'ow':1.0, 'jw':10, 'dw':0.05,
    'nw':30, 'ow':2.0, 'jw':3,
    'nw':1,  'ow':20.0,
    'nw':30, 'ow':3.0, 'dw':1,
#    
    'verb':'y','eps':0.01,'nrmax':1,'dtmax':0.00005,
    'tmx':32,'tmy':0,'pmx':32,'pmy':0,
    'misc':'incore=n',
#
    'nsc':1
    }
par['zmin']=par['oz']
par['zmax']=par['oz'] + (par['nz']-1) * par['dz']
par['xmin']=par['ox']
par['xmax']=par['ox'] + (par['nx']-1) * par['dx']


# ------------------------------------------------------------
# REFLECTIVITY
# ------------------------------------------------------------
Flow('rrr',None,
     '''
     spike nsp=1 mag=1
     n1=%(nz)d d1=%(dz)g o1=%(oz)g k1=150 l1=150
     n2=%(nx)d d2=%(dx)g o2=%(ox)g
     ''' % par)

Flow('msk',None,
     '''
     spike nsp=1 mag=0.7
     n1=%(nz)d d1=%(dz)g o1=%(oz)g
     n2=%(nx)d d2=%(dx)g o2=%(ox)g k2=250 l2=350 |
     math output="1-input" |
     smooth rect2=20
     ''' % par)

Flow('ref','rrr msk',
     '''
     math m=${SOURCES[1]} output="input*m" |
     ricker1 frequency=0.02 |
     put label1=z label2=x label3=y |
     transp plane=12 |
     transp plane=23 
     ''')
     
Result('ref','ref',
       '''
       transp plane=23 |
       transp plane=12 |
       '''+ igrey('title="image"'))

# ------------------------------------------------------------
# VELOCITY/SLOWNESS
# ------------------------------------------------------------
Flow('vel',None,
     '''
     spike nsp=1 mag=2000
     n1=%(nz)d d1=%(dz)g o1=0 |
     spray axis=2 n=%(nx)d o=%(ox)g d=%(dx)g |
     put label1=z label2=x label3=y 
     ''' % par )    
Result('vel','vel',igrey('title="background velocity"'))
Flow('slo','vel',
     '''
     transp |
     math "output=1/input" |
     spray axis=2 n=1 |
     put label2=y
     ''' % par )

Flow('dsl',None,
     '''
     spike nsp=1 mag=0.00005
     n1=%(nz)d d1=%(dz)g o1=%(oz)g k1=079 l1=081
     n2=%(nx)d d2=%(dx)g o2=%(ox)g |
     put label1=z label2=x label3=y |
     smooth rect1=1 rect2=1 |
     transp plane=12 |
     transp plane=23 |
     rtoc
     ''' % par )

# ------------------------------------------------------------
# DATA (exploding reflector)
# ------------------------------------------------------------

zomig.model('wfl','slo','ref',par)

# ------------------------------------------------------------
# IMAGE (background)
# ------------------------------------------------------------
zomig.image('img','slo','wfl',par)
Result('img','img','window | transp |' + igrey('title="image"'))

# ------------------------------------------------------------
# WAVEFIELD (background)
# ------------------------------------------------------------
zomig.Awftwo('www','wfl','slo',par)

# ------------------------------------------------------------
# WEMVA
# ------------------------------------------------------------
zomig.s2i('dsl','dim','www','slo',par) # forward
zomig.i2s('dim','bsl','www','slo',par) # adjoint

Plot('www','www','window | real | transp |'+ igrey('title="www"'))
Plot('dim','dim','window | real | transp |'+ igrey('title="dim"'))
Plot('img','img','window |        transp |'+ igrey('title="img"'))

Plot('dsl','dsl','window | real | transp |'+ igrey('title="dsl" color=F'))
Plot('bsl','bsl','window | real | transp |'+ igrey('title="bsl" color=F'))

pplot.p2x2('scat','img','dsl','dim','bsl',0.5,0.4,-10,-15)

# ------------------------------------------------------------

End()
