from rsf.proj import *
from math import *
import os

wf = 2*pi
nt = 501
dt = 0.004
ot = 0
nx = 501
dx = 0.01
ox = 0

for eve in (1,2,3,4):
    spike='spike%d' % eve
    tpara='tpara%d'   % eve
    para='para%d'     % eve
    Flow(spike,None,
        '''
        spike n1=%d d1=%g o1=%g n2=%d d2=%g o2=%g nsp=1 k1=%d mag=1  p2=0| 
        ricker1 frequency=15 | put unit2=km label2=Distance
        ''' % (nt,dt,ot,nx,dx,ox,eve*80-30))

    Flow(tpara,spike,
        '''
        window n1=1 | math output="-sqrt(%g*%g+(x1-2.5)*(x1-2.5)/%g/%g)+%g"
        ''' % (0.004*(eve*80-30),0.004*(eve*80-30),2,2,0.004*(eve*80-30)))

    Flow(para,[spike, tpara],
        'datstretch datum=${SOURCES[1]} ')

Flow('para','para1 para2 para3 para4','add ${SOURCES[1]} ${SOURCES[2]} ${SOURCES[3]}')
Plot('para','window | grey label2=Distance unit2=km transp=y yreverse=y poly=y  title="Missing 65% traces" scalebar=y')


# Mask for random traces
Flow('mask-logic','para',
     '''
     window n1=1 |
     noise rep=y type=n seed=2008 |
     math output="input^1" |
     mask min=0.15 | cut n1=5 | cut n1=5 f1=115
     ''')
Flow('mask','mask-logic','dd type=float')
Flow('dobs','para mask-logic','headercut mask=${SOURCES[1]}')
Plot('dobs','window | grey label2=Distance unit2=km transp=y yreverse=y poly=y  title="Missing 65% traces" scalebar=y')

Flow('drec_05_40','dobs mask',
     '''
     lsinterp2d mask=${SOURCES[1]} niter=40 verb=y eps=0.01 nouter=5
     ''')

Plot('drec_05_40','window | grey label2=Distance unit2=km transp=y yreverse=y poly=y  title="Reconstructed nouter=05 niter=40" scalebar=y')


Flow('derr_05_40','para drec_05_40',
    '''
    add ${SOURCES[1]} scale=1,-1
    ''')
Plot('derr_05_40','window | grey label2=Distance unit2=km transp=y yreverse=y poly=y  title="Error panel" scalebar=y')
Result('combined','para dobs drec_05_40 derr_05_40','TwoColumns')


End()
