from rsftex import *

import os
import rsfdoc
import rsfprog

root = os.environ.get('RSFROOT')
libdir = os.path.join(root,'lib')
bindir = os.path.join(root,'bin')
sfdoc  = os.path.join(bindir,'sfdoc')

progs = []
for prog in rsfdoc.progs.keys():
    progs.append(prog+'.tex')
    Command2(prog+'.tex',sfdoc,
             'PYTHONPATH=%s LD_LIBRARY_PATH=%s $SOURCE -l . %s' % \
             (os.environ.get('PYTHONPATH'),
              os.environ.get('LD_LIBRARY_PATH'),
              prog))

Alias('progs',progs)


Paper('install',use='[bookmarks=true]hyperref')
Paper('tour',use='listings,color,hyperref')
Paper('format',use='hyperref')
Paper('api', use='hyperref,listings',include='\\newcommand{\\RSF}{../../..}')
Paper('demo',use='hyperref,listings',include='\\newcommand{\\RSF}{../../..}')

Paper('prog',use='hyperref,amsmath,fancybox',
      include='''
      \\newcommand{\\prog}[1]{
      \\noindent\\fbox{
      \\parbox{\\textwidth}{
      \\input{sf#1}
      }}}
      ''')

Paper('abstract',lclass='eage',
      include=r'''
      \thispagestyle{empty}
      \setlength{\textheight}{25cm}
      \newenvironment{geotitle}{%
      \begin{minipage}{\textwidth}%
      \bfseries\Large\centering}
      {\end{minipage}\vspace{.2in}}%
      \renewcommand{\title}[1]{%
      \noindent\begin{geotitle}\setlength{\parindent}{0em}\par%
      {\smallskip #1}\end{geotitle}}
      \renewcommand{\author}[1]{%
      \begin{center}
      \textbf{#1}
      \end{center}}
      ''')

Paper('dummy')

Depends2('install',map(lambda x: x+'.install',
                       Split('api format install prog tour demo')))

End(use='hyperref')
