/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_ccdstep_h
#define _sf_ccdstep_h


#include "_bool.h"
#include "c99.h"
#include "komplex.h"


void sf_ccdstep_init(void);
/*< initialize internal storage >*/


void sf_ccdstep_close(void);
/*< free internal storage >*/


void sf_ccdstep(bool forget          /* restart flag */, 
	       int nx               /* model size */, 
	       int ny               /* data size */, 
	       sf_complex* x        /* current model [nx] */, 
	       const sf_complex* g  /* gradient [nx] */, 
	       sf_complex* rr       /* data residual [ny] */, 
	       const sf_complex* gg /* conjugate gradient [ny] */);
/*< Step of conjugate-direction iteration. 
  The data residual is rr = A x - dat
>*/

#endif
