/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_ccopy_h
#define _sf_ccopy_h


#include "c99.h"
#include "_bool.h"


void sf_ccopy_lop (bool adj, bool add, int nx, int ny, 
		   sf_complex* xx, sf_complex* yy);
/*< linear operator >*/

#endif
