/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_cdstep_h
#define _sf_cdstep_h


#include "_bool.h"


void sf_cdstep_init(void);
/*< initialize internal storage >*/


void sf_cdstep_close(void);
/*< free internal storage >*/


void sf_cdstep(bool forget     /* restart flag */, 
	       int nx          /* model size */, 
	       int ny          /* data size */, 
	       float* x        /* current model [nx] */, 
	       const float* g  /* gradient [nx] */, 
	       float* rr       /* data residual [ny] */, 
	       const float* gg /* conjugate gradient [ny] */);
/*< Step of conjugate-direction iteration. 
  The data residual is rr = A x - dat
>*/


void sf_cdstep_diag(int nx, float *res /* [nx] */);
/*< compute diagonal of the model resolution matrix >*/


void sf_cdstep_mat (int nx, float **res /* [nx][nx] */);
/*< compute complete model resolution matrix >*/

#endif
