/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_celltrace_h
#define _sf_celltrace_h


#include "_bool.h"


typedef struct sf_CellTrace *sf_celltrace;
/* abstract data type */


sf_celltrace sf_celltrace_init (bool lsint  /* use local ls interpolation */,
				int order   /* interpolation accuracy */, 
				int nt      /* maximum time steps */,
				int nz      /* depth samples */, 
				int nx      /* lateral samples */, 
				float dz    /* depth sampling */, 
				float dx    /* lateral sampling */, 
				float z0    /* depth origin */, 
				float x0    /* lateral origin */, 
				float* slow /* slowness [nz*nx] */);
/*< Initialize ray tracing object >*/


void sf_celltrace_close (sf_celltrace ct);
/*< Free allocated storage >*/


float sf_cell_trace (sf_celltrace ct, 
		     float* xp    /* position */, 
		     float* p     /* ray parameter */, 
		     int* it      /* steps till boundary */, 
		     float** traj /* trajectory */);
/*< ray trace >*/

#endif
