/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_copy_h
#define _sf_copy_h


#include "_bool.h"


void sf_copy_lop (bool adj, bool add, int nx, int ny, float* xx, float* yy);
/*< linear operator >*/

#endif
