/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_ctrianglen_h
#define _sf_ctrianglen_h


#include "_bool.h"
#include "komplex.h"


void sf_ctrianglen_init (int ndim  /* number of dimensions */, 
			int *nbox /* triangle radius [ndim] */, 
			int *ndat /* data dimensions [ndim] */);
/*< initialize >*/


void sf_ctrianglen_lop (bool adj, bool add, int nx, int ny, sf_complex* x, sf_complex* y);
/*< linear operator >*/


void sf_ctrianglen_close(void);
/*< free allocated storage >*/

#endif
