/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_deriv_h
#define _sf_deriv_h


void sf_deriv_init(int nt1  /* transform length */, 
		   int n1   /* trace length */, 
		   float c1 /* filter parameter */);
/*< initialize >*/


void sf_deriv_close(void);
/*< free allocated storage >*/


void sf_deriv (const float* trace, float* trace2);
/*< derivative operator >*/

#endif
