/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_fftlabel_h
#define _sf_fftlabel_h


#include "file.h"


void sf_fft_unit(int axis         /* axis number */,
		 const char* unit /* input unit */,
		 sf_file out      /* output file */);
/*< Change unit to 1/unit or vice versa >*/


bool sf_fft_label(int axis          /* axis number */,
		  const char* label /* input label */, 
		  sf_file out       /* output file */);
/*< Choose an output label appropriately. 
  Returns false if the label name is not recognized. >*/

#endif
