/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_gmres_h
#define _sf_gmres_h


#include "_bool.h"


void sf_gmres_init(int nx      /* data size */, 
		   int restart /* memory */);
/*< initialize >*/


void sf_gmres_close(void);
/*< free allocated storage >*/


void sf_gmres (const float *f                                         /* data */, 
	       float *x                                               /* estimated model */,
	       void (*myatimes) (int, const float *, float *, void *) /* operator */,
	       void * user_data                                       /* internal data */,
	       int itmax                                              /* number of iterations */, 
	       float tol                                              /* tolerance */, 
	       bool verb                                              /* verbosity */);
/*< GMRES solver >*/

#endif
