/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_grad2fill_h
#define _sf_grad2fill_h


#include "_bool.h"


void sf_grad2fill_init (int m1, int m2);
/*< Initialize with data dimensions >*/


void sf_grad2fill_close (void);
/*< Free allocate storage >*/


void sf_grad2fill(int niter   /* number of iterations */, 
	       float* mm   /* estimated model */, 
	       bool *known /* mask */);
/*< Run optimization >*/

#endif
