/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_hilbert_h
#define _sf_hilbert_h


void sf_hilbert_init(int nt1  /* trace length */, 
		     int n1   /* transform length */, 
		     float c1 /* filter parameter */);
/*< initialize >*/


void sf_hilbert_close(void);
/*< free allocated storage >*/


void sf_hilbert (const float* trace, float* trace2);
/*< transform >*/


void sf_hilbert4 (const float* trace, float* trace2);
/*< transform - kind 4 filter >*/

#endif
