/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_igrad1_h
#define _sf_igrad1_h


void  sf_igrad1_lop(bool adj, bool add, 
		    int nx, int ny, float *xx, float *yy);
/*< linear operator >*/

#endif
