/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_igrad2_h
#define _sf_igrad2_h


#include "_bool.h"


void sf_igrad2_init (int n1_in, int n2_in);
/*< initialize with data dimensions >*/


void sf_igrad2_lop (bool adj, bool add, int np, int nr, float* p, float* r);
/*< linear operator, r[n1*n2*2] is the gradient of p[n1*n2] >*/

#endif
