/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_impl2_h
#define _sf_impl2_h


void sf_impl2_init (float r1, float r2   /* radius */, 
		 int n1_in, int n2_in /* data size */, 
		 float tau            /* duration */, 
		 float pclip          /* percentage clip */, 
		 bool up_in           /* weighting case */,
		 bool verb_in         /* verbosity flag */,
		 float *dist_in       /* optional distance function */,
		 int nsnap_in         /* number of snapshots */,
		 sf_file snap_in      /* snapshot file */);
/*< initialize >*/


void sf_impl2_close (void);
/*< free allocated storage >*/


void sf_impl2_set(float ** x);
/*< compute weighting function >*/


void sf_impl2_apply (float **x, bool set, bool adj);
/*< apply diffusion >*/


void sf_impl2_lop (bool adj, bool add, int nx, int ny, float* x, float* y);
/*< linear operator >*/

#endif
