/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_int1_h
#define _sf_int1_h


#include "interp.h"


void  sf_int1_init (float* coord               /* cooordinates [nd] */, 
		    float o1, float d1, int n1 /* axis */, 
		    sf_interpolator interp     /* interpolation function */, 
		    int nf_in                  /* interpolator length */, 
		    int nd_in                  /* number of data points */,
		    float tau                  /* interpolation shift */);
/*< initialize >*/


void  sf_int1_lop (bool adj, bool add, int nm, int ny, float* x, float* ord);
/*< linear operator >*/


void  sf_cint1_lop (bool adj, bool add, int nm, int ny, sf_complex* x, sf_complex* ord);
/*< linear operator for complex numbers >*/


void sf_int1_close (void);
/*< free allocated storage >*/

#endif
