/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_int3_h
#define _sf_int3_h


#include "interp.h"


#include "_bool.h"


void  sf_int3_init (float** coord          /* coordinates [nd][3] */, 
		    float o1, float o2, float o3,
		    float d1, float d2, float d3,
		    int   n1, int   n2,   int n3 /* axes */, 
		    sf_interpolator interp /* interpolation function */, 
		    int nf_in              /* interpolator length */, 
		    int nd_in              /* number of data points */);
/*< initialize >*/


void  sf_int3_lop (bool adj, bool add, int nm, int ny, float* mm, float* dd);
/*< linear operator >*/


void int3_close (void);
/*< free allocated storage >*/

#endif
