/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_interp_spline_h
#define _sf_interp_spline_h


void sf_spline_int (float x, int n, float* w);
/*< interpolation function >*/


void sf_spline_der (float x, int n, float* w);
/*< derivative computation >*/


void sf_spline4_int (float x, float* w);
/*< Cubic spline interpolation >*/


void sf_spline4_der (float x, float* w);
/*< Cubic spline derivative >*/

#endif
