/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_lsint2_h
#define _sf_lsint2_h


#include "eno.h"


typedef struct LSint2 *sf_lsint2;
/* abstract data type */


sf_lsint2 sf_lsint2_init (int n1, int n2 /* data dimensions */);
/*< Initialize interpolation object >*/


void sf_lsint2_set (sf_lsint2 pnt, float** c /* data [n2][n1] */);
/*< Set the interpolation table. c can be changed or freed afterwords. >*/


void sf_lsint2_close (sf_lsint2 pnt);
/*< Free internal storage >*/


void sf_lsint2_set1 (sf_lsint2 pnt, float* c /* data [n2*n1] */);
/*< Set the interpolation table. c can be changed or freed afterwords. >*/


void sf_lsint2_apply (sf_lsint2 pnt, 
		      int i, int j     /* grid location */, 
		      float x, float y /* offset from grid */, 
		      float* f         /* output data value */, 
		      float* f1        /* output derivative [2] */,
		      der what         /* what to compute [FUNC,DER,BOTH] */);
/*< Apply interpolation. >*/

#endif
