/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_mask_h
#define _sf_mask_h


#include "_bool.h"
#include "c99.h"


void sf_mask_init(const bool *m_in);
/*< initialize with mask >*/


void sf_mask_lop(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< linear operator >*/


void sf_cmask_lop(bool adj, bool add, int nx, int ny, sf_complex *x, sf_complex *y);
/*< linear operator >*/

#endif
