/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_math1_h
#define _sf_math1_h


#include "kiss_fft.h"
#include "file.h"


void sf_math_evaluate (int     len  /* stack length */, 
		       int     nbuf /* buffer length */, 
		       float** fbuf /* number buffers */, 
		       float** fst  /* stack */);
/*< Evaluate a mathematical expression from stack (float numbers) >*/


void sf_int_math_evaluate (int   len  /* stack length */, 
			   int   nbuf /* buffer length */, 
			   int** ibuf /* number buffers */, 
			   int** ist  /* stack */);
/*< Evaluate a mathematical expression from stack (integer numbers) >*/


void sf_complex_math_evaluate (int          len  /* stack length */, 
			       int          nbuf /* buffer length */, 
			       sf_complex** cbuf /* number buffers */, 
			       sf_complex** cst  /* stack */);
/*< Evaluate a mathematical expression from stack (complex numbers) >*/


size_t sf_math_parse (char*       output /* expression */, 
		      sf_file     out    /* parameter file */,
		      sf_datatype datatype);
/*< Parse a mathematical expression, returns stack length >*/

#endif
