/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_matmult2_h
#define _sf_matmult2_h


#include "adjnull.h"


void sf_matmult2_init (float** bb);
/*< initialize with a pointer to a matrix >*/


void sf_matmult2_lop (bool adj, bool add, 
		      int nx, int ny, float* x, float*y);
/*< linear operator, no adjoint >*/


void sf_matmult2 (int nx, const float* x, float* y, void* mat);
/*< square linear operator, no adjoint >*/

#endif
