/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_pqueue_h
#define _sf_pqueue_h


enum {SF_IN, SF_FRONT, SF_OUT};


void sf_pqueue_init (int n);
/*< Initialize heap with the maximum size >*/


void sf_pqueue_start (void);
/*< Set starting values >*/


void sf_pqueue_close (void);
/*< Free the allocated storage >*/


void sf_pqueue_insert (float* v);
/*< Insert an element (smallest first) >*/


void sf_pqueue_insert2 (float* v);
/*< Insert an element (largest first) >*/


float* sf_pqueue_extract (void);
/*< Extract the smallest element >*/


float* sf_pqueue_extract2 (void);
/*< Extract the largest element >*/


void sf_pqueue_update (float **v);
/*< restore the heap: the value has been altered >*/

#endif
