/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_sharpinv_h
#define _sf_sharpinv_h


void sf_csharpinv(sf_coperator oper /* inverted operator */, 
		  float scale       /* extra operator scaling */,
		  int niter         /* number of outer iterations */,
		  int ncycle        /* number of iterations */,
		  float perc        /* sharpening percentage */,
		  bool verb         /* verbosity flag */,
		  int nq, int np    /* model and data size */,
		  sf_complex *qq    /* model */, 
		  sf_complex *pp    /* data */,
		  bool twhole       /* thresholding flag */);
/*< sharp inversion for complex-valued operators >*/


void sf_sharpinv(sf_operator oper  /* inverted operator */, 
		 float scale       /* extra operator scaling */,
		 int niter         /* number of outer iterations */,
		 int ncycle        /* number of iterations */,
		 float perc        /* sharpening percentage */,
		 bool verb         /* verbosity flag */,
		 int nq, int np    /* model and data size */,
		 float *qq         /* model */, 
		 float *pp         /* data */,
                 bool twhole       /* thresholding flag */);
/*< sharp inversion for real-valued operators >*/

#endif
