/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_stretch_h
#define _sf_stretch_h


#include "_bool.h"


typedef struct sf_Map *sf_map;
/* abstract data type */


sf_map sf_stretch_init (int n1, float o1, float d1 /* regular axis */, 
			int nd                     /* data length */, 
			float eps                  /* regularization */, 
			bool narrow                /* if zero boundary */);
/*< initialize >*/


void sf_stretch_define (sf_map str, const float* coord);
/*< define coordinates >*/


void sf_stretch_apply (sf_map str, const float* ord, float* mod);
/*< convert ordinates to model >*/


void sf_stretch_invert (sf_map str, float* ord, const float* mod);
/*< convert model to ordinates by linear interpolation >*/


void sf_stretch_close (sf_map str);
/*< free allocated storage >*/

#endif
