/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_tent2_h
#define _sf_tent2_h


void sf_tent2 (int dim          /* number of dimensions */, 
	       const int* nwind /* window size [dim] */, 
	       float* windwt    /* window weight */);
/*< define window weight >*/

#endif
