import os, sys

try:
    import bldutil
    glob_build = True 
    srcroot = '../..'
    Import('env bindir libdir pkgdir')
except:
    glob_build = False
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug() 
    bindir = libdir = pkgdir = None

targets = bldutil.UserSconsTargets()

targets.py = '''
svd
threedcube
gui
browser
'''

targets.build_all(env, glob_build, srcroot, bindir, libdir, pkgdir)
