/*        Generated by TAPENADE     (INRIA, Tropics team)
    Tapenade 3.6 (r4512) -  3 Aug 2012 15:11
*/
#include "cstd.h"

/*
  Differentiation of acd_2d_2 in forward (tangent) mode:
   variations   of useful results: **up
   with respect to varying inputs: **csq **uc **up
   RW status of diff variables: **csq:in **uc:in **up:in-out
   Plus diff mem management of: csq:in *csq:in uc:in *uc:in up:in
                *up:in
*/
void acd_2d_2_d(float **uc, float **ucd, float **up, float **upd, float **csq,
        float **csqd, int *s, int *e, float c0, float *c1) {
    int i0, i1;
    for (i1 = s[1]; i1 < e[1]+1; ++i1)
        for (i0 = s[0]; i0 < e[0]+1; ++i0) {
            upd[i1][i0] = 2.0*ucd[i1][i0] - upd[i1][i0] + csqd[i1][i0
                ]*(c0*uc[i1][i0]+c1[0]*(uc[i1][i0+1]+uc[i1][i0-1])+c1[1]*(uc[
                i1+1][i0]+uc[i1-1][i0])) + csq[i1][i0]*(c0*ucd[i1][
                i0]+c1[0]*(ucd[i1][i0+1]+ucd[i1][i0-1])+c1[1]*(ucd[i1+1][i0]+
                ucd[i1-1][i0]));
        }
}
