" ",
  " ",
  " ---------------------------------- LBFGS -----------------------------------",
  " ",
  " line search parameters",
  " rvl/umin/include/LBFGSBT.hh, rvl/umin/include/lbfgsalg.hh",
  " ",                 
  " ---------------------------- begin lbfgs parameters ------------------------",
  " ",
  "       InvHessScale = 1.0          overall scale for inverse Hessian",
  "  MaxInvHessUpdates = 5            max rank of BFGS inv Hessian approx",
  " ",
  " ------------------------------ end lbfgs parameters ------------------------",

