" ",
  " ",
  " ----------------------------- LINE SEARCH -----------------------------------",
  " ",
  " line search parameters",
  " rvl/umin/include/lnsrch.hh, rvl/umin/include/lnsrchBT.hh",
  " ",
  " ----------------------- begin line search parameters ------------------------",
  " ",   
  "	 LSMinStepFrac = 1.e-6        less than this step regarded as zero     ",
  " ",
  " ------------------------- end line search parameters ------------------------",
