" ",
  " ",
  " ----------------------------------- TRGN -----------------------------------",
  " ",
  " line search parameters",
  " rvl/umin/include/TRGNAlg.hh, rvl/umin/include/cgnealg.hh",
  " ",                 
  " ----------------------------- begin trgn parameters ------------------------",
  " ",
  "        ResidualTol = 0.0          stop if residual norm drops below this",
  "                                   relative to initial value in TRGN iteration",
  "        CGNE_ResTol = 0.0          stop if GN residual norm drops below this",
  "                                   relative to initial value in CGNE iteration",
  "       CGNE_GradTol = 0.0          stop if GN normal residual norm drops below this",
  "                                   relative to initial value in CGNE iteration",
  " ",
  " ------------------------------- end trgn parameters ------------------------",

