" ",
  " ",
  " ----------------------------------- UMIN -----------------------------------",
  " ",
  " Generic unconstrained minimization parameters",
  " rvl/umin/include/LBFGSBT.hh, rvl/umin/include/TRGNAlg.hh",
  " ",
  " --------------------------- begin acd parameters ---------------------------",
  " ",
  "           MaxSteps = 10           maximum number of model updates",       
  "        MaxSubSteps = 10           max number of inner alg steps (eg. line",
  "                                   search or iterative linear solver)",
  "      InitStepBound = 1.0f         max length of first step", 
  "        MinDecrease = 0.1f         minimum fractional decrease (1st G-A param)",
  "       GoodDecrease = 0.9f         decrease threshhold for step increase",
  "                                   (2nd G-A param)", 
  "     StepDecrFactor = 0.5f         decrease step or trust radius by this factor",
  "                                   if fractional decrease less than MinDecrease",
  "     StepIncrFactor = 1.8f         increase step or trust radius by this factor",
  "                                   if fractional decrease more than GoodDecrease",
  "  MaxFracDistToBdry = 1.0          do not allow update to exceed this fractional",
  "                                   step to boundary of feasible set (limits step",
  "                                   or trust radius)",
  "      AbsGradThresh = 0.0          stop if gradient norm falls below", 
  "      RelGradThresh = 1.e-2        stop if gradient norm falls below this fraction",
  "                                   of its initial value", 
  "     VerboseDisplay = true         write summary information to output stream", 
  " ",
  " ---------------------------- end umin parameters ---------------------------",
