from rsf.tex import *

Paper('slides',
      lclass='cwpslides',
      use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy')

Paper('slidesMadFast',
      lclass='cwpslides',
      use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy')

End(use='hyperref,listings',
    color='horizon smoothed mona smoothed2')

