from rsf.proj import *

# Download data
Fetch('austin-w.HH','bay')

# Convert format
Flow('dem','austin-w.HH',
     'dd form=native')

# Display
def plot(title):
    return '''
    grey bias=191 clip=150 yreverse=n 
    title="%s" screenratio=1
    ''' % title

Result('dem',plot('Digital Elevation Map'))

# Running median program
run = Program('running.c')

###########
# MODIFY ME
###########
Flow('med','dem %s' % run[0],
     './${SOURCES[1]} w1=20 w2=20 what=0')
Result('med',plot('Signal'))

# Difference
Flow('res','dem med','add scale=1,-1 ${SOURCES[1]}')
Result('res',plot('Noise') + ' bias=0')

End()
