from rsf.proj import *

sys.path.append('..')

import twohalf

# get velocity model
twohalf.getvel('vel')
Result('vel','grey color=j mean=y title="BP 2.5D Model" scalebar=y barreverse=y')

# get data
Fetch('thexp.rsf','bp')
Flow('exp','thexp','dd form=native')

# lowrank decomposition
Flow('cfft','vel','transp | rtoc |  fft3 axis=1 pad=1 | fft3 axis=2 pad=1')
Flow('cright cleft','vel cfft',
     '''
     transp | scale dscale=0.5 |
     cisolr2 seed=2012 dt=0.001 fft=${SOURCES[1]} left=${TARGETS[1]} 
     ''')

Flow('iexp','exp','envelope hilb=y | scale dscale=-1')
Flow('cexp','exp iexp','cmplx ${SOURCES[1]}')

# High-resolution zero-offset migration
Flow('czomig','cexp cleft cright',
     '''
     reverse which=1 |
     transp |
     wcfftexp2 mig=y timer=y
     left=${SOURCES[1]} right=${SOURCES[2]}
     nz=321 dz=12.5
     ''')

Result('czomig','window f3=-1 | real | grey title="Lowrank Onestep Zero-Offset Migration" unit2=km')

End()
