from rsf.proj import *

# files have names like:
#wget https://s3.amazonaws.com/open.source.geoscience/open_data/bpmodel94/Model94_shots.segy.gz

# fetch the text and jpg files
for filename in ['README.txt','README_Modification','optimum.jpg']:
    Fetch(filename,dir='bpmodel94',
      server='https://s3.amazonaws.com',top='open.source.geoscience/open_data',
      usedatapath=0)

Flow('README.display','README.txt','/bin/cat ${SOURCES[0]}',stdin=0,stdout=-1)
Flow('README_Modification.display',
     './README_Modification ','/bin/cat ${SOURCES[0]}',stdin=0,stdout=-1)

Flow('optimum.display','optimum.jpg','open ${SOURCES[0]}',stdin=0,stdout=0)

# fetch the compressed segy data, run gunzip and sfsegyread
# the parameter usedatapath=0 is required to elliminate the symbolic link
# that make gunzip fail (on my MacBook) 
for filename in ['Model94_shots','velocity']:
    #filename='Model94_shots'
    #         Model94_shots.segy.gz
    #segyname=Model94_shots.segy
    Fetch(filename+'.segy.gz',dir='bpmodel94',
       server='https://s3.amazonaws.com',top='open.source.geoscience/open_data',
       usedatapath=0)

    Flow(filename+'.segy',
	 filename+'.segy.gz',
        '''
     	gunzip 
      	''')
    Flow([filename+'.rsf' ,filename+'_hdr.rsf',
      	  filename+'.thdr',filename+'.bhdr'],
         filename+'.segy',
         '''
      	 sfsegyread tfile=${TARGETS[1]} 
      	   hfile=${TARGETS[2]}  bfile=${TARGETS[3]} 
      	 ''')


End()
