from rsfproj import *

private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

gath = 'gather_@'

Fetch(gath,'bp',private)

Flow('gath','./'+gath,
     '''
     echo in=$SOURCE
     n1=140 n2=80
     d1=1  d2=1
     o1=0  o2=0
     label1=z label2=h
     data_format=xdr_float |
     dd form=native 
     ''',stdin=0)

Plot('gath','grey pclip=100 title="Offset Gather" ')

Flow('agath','gath','slant adj=y p0=-1.6 np=64 dp=0.05')

Plot('agath','grey title="Angle Gather" label2="tan" ')

Result('gath','gath agath','SideBySideAniso')

Flow('zero','agath','math output=0')

Flow('seis','agath zero','seislet dip=${SOURCES[1]} adj=y inv=y')

Flow('clean','seis zero','cut f2=8 | seislet dip=${SOURCES[1]}')

Plot('clean','grey title="Cleaned Angle Gather" label2="tan" ')

Flow('cgath','clean','slant adj=n nx=80 x0=0 dx=1')

Plot('cgath','grey pclip=100 title="Cleaned Offset Gather" ')

Result('clean','cgath clean','SideBySideAniso')

End()
