from rsfbook import *

Papers(copyr='Madagascar Community',
       group='Madagascar Documentation',
       papers=Split('''
       rsf/paper.tex
       rsf/install.tex
       rsf/prog.tex
       rsf/format.tex
       rsf/tour.tex
       rsf/api.tex
       rsf/demo.tex
       scons/paper.tex
       '''),
       authors={'scons':'Sergey Fomel and Gilles Hennenfent'},
       line='\\url{http://rsf.sourceforge.net/}',
       fig=('rsf/sfmath','rose','width=0.5\\textwidth'))
       
End(use='hyperref,color,amsmath,fancybox,jfc',
    include='\\newcommand{\\RSF}{../../..}')

