from rsf.book import *

Papers(copyr='Madagascar Community',
       group='Madagascar Documentation',
       papers=Split('''
       school2012/tutorial.tex
       school/articleWSI.tex
       school2009/paper.tex
       rsf/tour.tex
       rsf/demo.tex
       scons/paper.tex
       '''),
#       manual/manual.tex
       authors={'scons':'Sergey Fomel and Gilles Hennenfent',
                'manual-manual': 'Mohammad Akbar Zuberi, Tariq Alkhalifah, and Christos Saragoitis',
                'school-articleWSI':'Paul Sava'},
       line='\\url{http://ahay.org/}',
       fig=('rsf/rsftour','overplot','width=0.75\\textwidth'))
       
End(use='hyperref,color,amsmath,amssymb,fancybox,jfc,desclist,makeidx',
    include='\\newcommand{\\RSF}{../../..}\n\\makeindex\\setcounter{tocdepth}{1}')

