from rsf.proj import *

Fetch('data-BP2.HH','bp')
Flow('data','data-BP2.HH','dd form=native')

# convolution using 1-D helix FFT
Flow('mult','data',
     '''
     pad n1=4000 | put n2=1 n1=2992000 |
     rtoc | fft3 axis=1 pad=1  | 
     math output="input*input" |
     fft3 axis=1 inv=y | real  | 
     put n1=4000 n2=748 | window n1=1216
     ''')

Flow('left', 'mult','window min2=0 | byte')
Flow('right','data','window min2=0 | byte')

Result('BP2','left right',
       '''
       merge axis=2 nspace=1 ${SOURCES[1]} |
       grey wanttitle=n wantaxis2=n label1=Time unit1=s crowd=0.87
       ''',vppen='xsize=6 ysize=8')

End()
