import os, sys

try:
    import bldutil
    glob_build = True # scons command launched in RSFSRC
    srcroot = '../..' # cwd is RSFSRC/build/user/psava
    Import('env bindir pkgdir')
except:
    glob_build = False # scons command launched in the local directory
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug() # Debugging flags for compilers
    bindir = pkgdir = None

targets = bldutil.UserSconsTargets()

# C mains
targets.c = '''
off2abs off2abs3
icor xcor2d tcor ucor 
laps2d laps3d
ic sic sic3d lstk
wigner wdf
srmig3 srmod3 zomig3 camig3 
stack3
hwt3d int3d rrt3d
shift fft3d
randcut
encode shot2grid
boxfilter
awefd lwefd
awefd2d awefd3d ewefd2d ewefd3d
anifd2d
hic2ang
wei
'''

# paradd

targets.build_all(env, glob_build, srcroot, bindir, pkgdir)
