import os, sys

try:
    import bldutil
    glob_build = True # scons command launched in RSFSRC
    srcroot = '../..' # cwd is RSFSRC/build/user/psava
    Import('env bindir libdir pkgdir')
    env = env.Clone()
except:
    glob_build = False # scons command launched in the local directory
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug() # Debugging flags for compilers
    bindir = libdir = pkgdir = None
    SConscript(os.path.join(srcroot,'su/lib/SConstruct'))

targets = bldutil.UserSconsTargets()

# C mains
targets.c = '''
off2abs off2abs3
icor xcor2d tcor ucor 
cicold2d eicold2d
laps2d laps3d
ic sic sic3d lstk
wigner wdf
srmig3 srmod3 zomig3 camig3 
stack3
hwt3d int3d rrt3d
shift fft3d
randcut
encode shot2grid
boxfilter
lwefd2d
ewefd2d ewefd3d
hdefd
emfdm2d
hic2ang
zowei wei weigwf weiajs weiajw
ttifd2d ttifd3d
srbin3d
cicop2d cicop3d
eicop2d eicop3d
aweop2d aweop3d
accumulate
decibel
itrack2d itrack3d
injop2d injop3d
transp12
esou epot
regrid1d regrid2d regrid3d
getattr
'''

# vse
# awefd2d awefd3d

# Python targets
targets.py = '''
corop
pwave3d
ocor3d
findmax
checkerboard
'''

dynlib = env.get('DYNLIB','')

env.Prepend(LIBS=[dynlib+'su'])

targets.build_all(env, glob_build, srcroot, bindir, libdir, pkgdir)
