#!/bin/csh
#$ -N rtm1 
#$ -pe 1way 288 
#$ -q normal
#$ -o rtm1.o$JOB_ID
#$ -l h_rt=24:00:00
#$ -V
#$ -cwd
#   <------ You MUST Specify a Project String ----->
#$ -A TCCS 


setenv OMP_NUM_THREADS 12 

ibrun tacc_affinity $RSFROOT/bin/sfffdrtm  source=source.rsf vel=vel3.rsf dt=0.0004 nt=7260 sht=0  isz=2 nbt=75 nbb=74 nbl=82 nbr=81 ct=0.002 cb=0.002 cl=0.002 cr=0.002 geo=geo.rsf irz=3  nr=96 err=0.000001 factor=1.0 ax=2 az=2 jm=15  tskip=0 jr=2 
