from rsf.proj import *
###############First of all, please mkdir DATA IMAG#######################
sys.path.append('..')
import marmousi

marmousi.getvel('vel')
Result('vel','grey min2=0 max2=9.2 min1=0 max1=3 scalebar=y color=j allpos=y title="Velocity Model" bias=1.5 barreverse=y')

marmousi.get_zodata('exp')
Result('exp','grey title="Exploding Reflector Data" ')

Flow('vel2','vel','transp | scale dscale=0.5') 
Result('vel2','grey color=j allpos=y bias=1.5 title="Migration Velocity" transp=n')

Flow('zomig','exp vel2',
     '''
     spline n1=7001 o1=0 d1=0.0005 |
     reverse which=1 |
     transp |
     ffd0 nbt=56 nbb=57 nbl=50 nbr=49
     vel=${SOURCES[1]}
     ''')
Result('zomig',
       '''
       grey transp=n title="Exploding Reflector Migration" 
       label1=Distance unit1=km label2=Depth unit2=km
       ''')
Flow('vel3','vel','transp | remap1 o1=0 d1=0.0125 n1=737') 
Result('vel3','grey scalebar=y barreverse=y min1=0 max1=9.2 min2=0 max2=3 transp=y color=j allpos=y bias=1.5 title="Migration Velocity" transp=n')

# Impulse response
Flow('spike','exp','spike k1=2001 k2=1151 | smooth rect1=3 rect2=3 repeat=3')

Flow('ffd-impres','spike vel2',
     '''
     spline n1=7001 o1=0 d1=0.0005 |
     reverse which=1 |
     transp |
     ffd0 nbt=56 nbb=57 nbl=50 nbr=49
     vel=${SOURCES[1]}
     ''')

Result('ffd-impres','grey title="Impulse Response" unit2=km')


nt=7260
dt=0.0004
Flow('source',None,
     '''
     spike n1=%d d1=%g k1=100 |
     ricker1 frequency=20
     '''%(nt,dt))
Result('source','graph  title="Source Wavelet" ')


marmousi.get_shots('shots')

Result('shots','byte | grey3 flat=n frame1=250 frame2=80 frame3=100 title=Shots')
######### Acquisition Geometry parameters #########
#Source location# 
Flow('geo',None,
     '''
     echo n1=4 n2=240 data_format=ascii_int esize=4 in=geo
     | dd form=native
     ''')
##########Split shot gathers to DATA/########
for s in range(0,240):
    shot= 'DATA/shot_'+str(240+s*2)
    Flow(shot,'shots',
         '''
         window n3=1 f3=%d | scale dscale=0.0001 |
         spline n1=7260 d1=0.0004 o1=0
         '''%(s))
#############qsub rtm1.sge##########
###############Images will appear in IMAG/ ############
#######################################################
#######################################################
#######################################################
#############Modeling##########
########## mkdir SHOT ##############
nt=18001
dt=0.00025
Flow('sourceshot',None,
     '''
     spike n1=%d d1=%g k1=200 |
     ricker1 frequency=30
     '''%(nt,dt))
Result('sourceshot','graph  title="Source Wavelet" ')
######### Modeling Geometry parameters #########
#Source location, receiver starting location, streamer length, record starting# 
Flow('geoshot',None,
     '''
     echo n1=461 data_format=ascii_int esize=4 in=geoshot
     | dd form=native
     ''')
Flow('geoshot_1','geoshot','window f1=4 | window n1=230')
Flow('geoshot_2','geoshot','window f1=234')
############ qsut geoshot_1.sge geoshot_2.sge #########
########## Shot gathers will be generated in SHOT/ #########
End()
