import os
from rsftex import *

os.environ['PSTEXPENOPTS'] = 'color=y fat=3 invras=y'

End(use='hyperref,amsmath,amsfonts,fancybox',options='10pt',
    include='''
    \\newcommand{\\prog}[1]{
    \\noindent\\fbox{
    \\parbox{\\textwidth}{
    \\input{sf#1}
    }}}
    ''')
