#!/bin/csh
#$ -N rtm 
#$ -pe 1way 72 
#$ -q normal
#$ -o rtm.o$JOB_ID
#$ -l h_rt=24:00:00
#$ -V
#$ -cwd
#   <------ You MUST Specify a Project String ----->
#$ -A TCCS 


setenv OMP_NUM_THREADS 12 

ibrun tacc_affinity $RSFROOT/bin/sfffdrtm  source=source.rsf vel=vel.rsf dt=0.0012 nt=3161 sht=0  isz=0 nbt=55 nbb=56 nbl=57 nbr=57 ct=0.002 cb=0.002 cl=0.002 cr=0.002 geo=geo.rsf irz=0  nr=256 err=0.000001 factor=1.0 ax=2 az=2 jm=10  tskip=0 jr=2 
