/* This file is automatically generated. DO NOT EDIT! */

#ifndef _lapfill_h
#define _lapfill_h

#include <rsf.h>

void lapfill_init (int m1, int m2 /* model size */, 
		   bool grad1     /* gradient (or Laplacian) */);
/*< initialize >*/

void lapfill_close (void);
/*< free allocated storage >*/

void lapfill(int niter   /* number of iterations */, 
	     float* mm   /* model [m1*m2] */, 
	     bool *known /* mask for known data [m1*m2] */);
/*< interpolate >*/

#endif
