/* This file is automatically generated. DO NOT EDIT! */

#ifndef _wilson_h
#define _wilson_h

#include <rsf.h>

#include "helix.h"

void wilson_init( int nmax /* maximum data size */) ;
/*< initialize >*/

float wilson_factor(int niter /* number of iterations */, 
		    float s0  /* zero-lag auto-correlation */, 
		    filter ss /* input auto-correlation */, 
		    filter aa /* output factor */, 
		    bool verb /* verbosity flag */, 
		    float tol /* tolerance */);
/*< Factor >*/

void wilson_close( void) ;
/*< free allocated storage >*/

#endif
