#!/bin/csh
#$ -N rtm
#$ -pe 1way 360 
#$ -q normal
#$ -o rtm.o$JOB_ID
#$ -l h_rt=5:00:00
#$ -V
#$ -cwd
#   <------ You MUST Specify a Project String ----->
#$ -A TCCS 


setenv OMP_NUM_THREADS 12 

ibrun tacc_affinity $RSFROOT/bin/sfffdrtmto  source=source.rsf vel=velocityabc.rsf dt=0.001 nt=8036 sht=35  nbt=100 nbb=100 nbl=100 nbr=99 ct=0.005 cb=0.005 cl=0.005 cr=0.005 geo=geo.rsf nr=481 err=0.000001 factor=1.0 ax=2 az=2 jm=10  tskip=0 jr=1 left=500 right=500 
