from rsfproj import *
from math import *
from string import *

alpha = pi/6
a = tan(alpha)

# Make a reflector model 
Flow('refl',None,
     '''
     math n1=901 o1=0 d1=0.01 output="sqrt(1+(x1*%g)^2)" 
     ''' % a)
Flow('model','refl',
     '''
     unif2 n1=201 d1=0.01 v00=1,2 |
     put label1=Depth unit1=km label2=Lateral unit2=km  |
     smooth rect1=10
     ''')

# Plot model
Result('model',
       '''
       window n2=301 |
       grey color=j allpos=y title=Model bias=1 scalebar=y 
       barreverse=y barlabel=Velocity barunit=km/s 
       ''')

# Reflector dip
Flow('dip','refl','math output="%g*x1/input" ' % (a*a))

# Kirchoff modeling
Flow('shot','refl dip',
     '''
     kirmod nt=1501 ns=1 s0=1 ds=0.5 nh=501 dh=0.01 h0=-0.5
     twod=y vel=1 freq=5 dip=${SOURCES[1]} verb=y
     ''')
Plot('shot',
     '''
     window max2=3.5 |
     grey title="0 km Depth" 
     label1=Time unit1=s label2=Offset unit2=km
     labelsz=10 titlesz=15 grid=y
     ''')

# Double Fourier transform

Flow('kw','shot','fft1 | fft3 axis=2')

# Extrapolation filters

dx = 0.01
dz = 1

dx2 = 2*pi*dx
dz2 = 2*pi*dz
a = 0.5*dz2/(dx2*dx2)

Flow('exact','kw',
     'math output="exp(I*sqrt(x1*x1-x2*x2)*%g)" ' % dz2)

Flow('approximate','kw',
     '''
     math output="exp(I*x1*%g)* 
     (x1+0.01+I*(cos(x2*%g)-1)*%g)/
     (x1+0.01-I*(cos(x2*%g)-1)*%g)" 
     ''' % (dz2,dx2,a,dx2,a))

# Extrapolation

for case in ('exact','approximate'):
    Flow('phase-'+case,case,
         '''
         window n1=1 min1=5 min2=-2 max2=2 | 
         math output="log(input)" | sfimag
         ''')
    Flow('angle-'+case,'phase-'+case,
         '''
         math output="%g*asin(x1/5)" |
         cmplx $SOURCE
         ''' % (180/pi))

    Flow('shot-'+case,['kw',case],
         '''
         add mode=p ${SOURCES[1]} | 
         fft3 axis=2 inv=y | fft1 inv=y
         ''')
    Plot('shot-'+case,
         '''
         window max2=3.5 |
         grey title="%g km Depth (%s)" 
         label1=Time unit1=s label2=Offset unit2=km
         labelsz=10 titlesz=15 grid=y
         ''' % (dz, capitalize(case)))

Result('shot','shot shot-exact shot-approximate',
       'SideBySideAniso')

Result('phase','angle-exact angle-approximate',
       '''
       cat axis=2 ${SOURCES[1]} | 
       graph title=Phase dash=0,1 
       label1="Angle From Vertical" unit1="\^o\_"
       ''')

End()
