from rsfproj import *

stack = 'diffr.CMPstack.su'

private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

Fetch(stack,'cassis',private)
Flow('stack tstack',stack,
     '''
     segyread tape=$SOURCE tfile=${TARGETS[1]} su=y endian=0 |
     put label1=Time unit1=s label2=Midpoint unit2=km
     o2=5 d2=0.0125
     ''',stdin=0)

Flow('vlf','stack',
     '''
     pad n2=1024 | cosft sign2=1 | 
     stolt vel=1.4 nf=4 | spray axis=2 n=1 o=0 d=1 |
     fourvc nv=200 dv=0.01 v0=1.4 verb=y |
     cosft sign3=-1 | window n3=981
     ''')

Flow('pat','vlf','patch verb=y w=1251,100,200')

Flow('foc','pat',
     '''
     focus dim=3 rect1=100 rect3=20 |
     math output="1/abs(input)" 
     ''')

End()
