import sys, os, string, re
sys.path.append('../..')
import configure

try: # distribution version
    Import('env')
    env = env.Copy()
    root = env.get('RSFROOT')
    libdir = os.path.join(root,'lib')
    incdir = os.path.join(root,'include')
except: # local version
    root = None
    env = Environment()
    opts=Options('../../config.py')
    configure.options(opts)
    opts.Update(env)
    SConscript('../../filt/lib/SConstruct')

env.Prepend(CPPPATH=['../../include'],
            LIBPATH=['../../lib'],
            LIBS=['drsf'])

if 'matlab' in env.get('API',[]):
    mex = env.get('MEX')
    suffix = env.get('MEXSUFFIX')

    for inp in Split('par dim read write create'):
        cfile = 'rsf_' + inp

        if mex:
            mfile = env.Command(cfile+suffix,
                                cfile+'.c',
                                "%s CFLAGS='%s %s -fPIC' "
                                "$SOURCE %s %s -output $TARGET" %
                                (mex,env['_CPPINCFLAGS'],env['CCFLAGS'],
                                 env['_LIBDIRFLAGS'], env['_LIBFLAGS']))

        if root:
            env.Install(libdir,mfile)
    
