from rsfproj import *

def velplot(title,label1='Depth (kft)'):
    return '''
    grey color=j allpos=y title="%s" scalebar=y
    barlabel="Velocity (kft/s)"
    label1="%s" label2="Lateral (kft)"
    barreverse=y pclip=100 
    ''' % (title,label1)

def graph(transp,o2,d2,n2,col,fat,extra=''):
    return '''
    graph transp=%d yreverse=y pad=n min2=%g max2=%g
    plotcol=%d plotfat=%d wantaxis=n wanttitle=n %s
    ''' % (transp,o2,o2+(n2-1)*d2,col,fat,extra)

def wiggle(title):
    return  '''
    wiggle transp=y yreverse=y poly=y xpos=${SOURCES[1]}
    title="%s" label2="Half-Offset (kft)" zplot=0.5
    wherexlabel=t wheretitle=b
    ''' % title

Flow('modl',None,
     '''
     spike n1=200 o1=-8 d1=0.08 n2=4
     nsp=4 k2=1,2,3,4 mag=2.2,3.5,5,7
     ''')
Flow('refl',None,
     '''
     spike n1=200 n2=4 nsp=4 k2=1,2,3,4
     mag=0.0909091,0.1428570,0.1111110,0.2000000
     ''')
Flow('mod1','modl','window min1=0')

Flow('unif','mod1','unif2 n1=150 d1=0.05 v00=5,6,8,10,15')
Result('modl','unif',velplot('Model'))

Flow('mod2','unif','math output=5+2*x1')

Plot('modl','mod2',velplot('True Model'))
Plot('modla','mod1',graph(0,0,0.05,150,0,20,'scalebar=y'))
Plot('modlb','mod1',graph(0,0,0.05,150,7,5,'scalebar=y'))
Result('modl2','modl modla modlb','Overlay')

Flow('clean','modl refl',
     '''
     kirmod nt=501 dt=0.004 freq=25 refl=${SOURCES[1]}
     ns=1 s0=2 ds=-0.1
     nh=241 h0=-12 dh=0.1
     vel=5 gradz=2 type=v
     ''')
Flow('data','clean',
     '''
     noise rep=y seed=2004 range=0.0002 |
     ricker1 frequency=25 |
     add $SOURCE 
     ''')

Result('data','grey title=CMP')


End()
