from rsfproj import *

# Fetch the velocity model from the data server
###############################################
vstr = 'sigsbee2a_stratigraphy.sgy'
Fetch(vstr,'sigsbee')
Flow('zvstr tzvstr ./shead ./bshead',vstr,
     '''
     segyread
     tape=$SOURCE
     tfile=${TARGETS[1]}
     hfile=${TARGETS[2]}
     bfile=${TARGETS[3]}
     ''',stdin=0)

Flow('vel','zvstr',
     '''
     put d1=0.025 o2=10.025 d2=0.025 |
     window f1=200 |
     scale dscale=0.001
     ''')
Plot('vel',
     '''
     grey wanttitle=n color=j allpos=y 
     label1="Depth (kft)" label2="Lateral (kft)"
     screenratio=0.3125 screenht=4 labelsz=4
     ''')

# Compute traveltimes by solving the eikonal equation
#####################################################

eikonal = 'eikonal yshot=40 zshot=5 br1=5 br2=5'

Flow('eiko','vel',eikonal)
Plot('eiko',
     '''
     contour nc=30 dc=0.2 plotcol=7
     wantaxis=n wanttitle=n
     screenratio=0.3125 screenht=4
     ''')

Result('eiko','vel eiko','Overlay')

samples = range(2,50)

errs = []
spaces = []

for sample in samples:

    # Subsample velocity and traveltime
    ###################################

    # Solve the eikonal equation
    ############################

    # Compute error
    ###############

    pass

# Concatenate results
#####################

# Plot error versus spacing
###########################
    
End()
