import os, sys

try:
    import bldutil
    glob_build = True # scons command launched in RSFSRC
    srcroot = '../..' # cwd is RSFSRC/build/user/fbroggin
    Import('env bindir pkgdir')
except:
    glob_build = False # scons command launched in the local directory
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug() # Debugging flags for compilers
    bindir = pkgdir = None

targets = bldutil.UserSconsTargets()

# C mains
targets.c = '''
autofocusing
awefd2d_fo
'''

targets.build_all(env, glob_build, srcroot, bindir, pkgdir)
