from rsf.proj import *

sys.path.append('..')
import constant

constant.get_zodata('data')
Result('data','grey title="Zero Offset" ')

Flow('vel','data','math output=1')

Flow('mig','data vel','kirchnew velocity=${SOURCES[1]} adj=1')

Result('mig','window min2=0 max2=1.5 | grey title="Kirchhoff Migration" ')

Flow('inv err','data vel','kirchinv velocity=${SOURCES[1]} niter=10 ps=1 err=${TARGETS[1]}')

Result('mig','window min2=0 max2=1.5 | grey title="Kirchhoff Migration" ')

Result('inv','window min2=0 max2=1.5 | grey title="Kirchhoff Inversion" ')

Result('err','graph labelsz=10 titlesz=12 unit1= unit2= title="Misfit error"')

# new codes test
dir = '/home/yujin/RSFSRC/user/seisinv/'

Flow('inv_sparse err_sparse','data vel',dir+'sfkirchinvs velocity=${SOURCES[1]} niter=2 liter=5 ps=1 err=${TARGETS[1]} verb=1')

Result('inv_sparse','window min2=0 max2=1.5 | grey title="Kirchhoff Inversion with Sparsity Promotion" ')

Result('err_sparse','graph labelsz=10 titlesz=12 unit1= unit2= title="Misfit error KISP"')

# Impulse response

Flow('imp','data','spike k1=501 k2=175 | ricker1 frequency=10')

Flow('imig','imp vel','kirchnew velocity=${SOURCES[1]} adj=1')

Flow('iinv ierr','imp vel','kirchinv velocity=${SOURCES[1]} niter=5 ps=1 err=${TARGETS[1]}')

Flow('iinv_sparse ierr_sparse','imp vel',dir+'sfkirchinvs velocity=${SOURCES[1]} niter=2 liter=5 ps=1 verb=1 err=${TARGETS[1]}')

Result('imig','window max1=3 | grey title="Kirchhoff Migration Impulse Response" ')

Result('iinv','window max1=3 | grey title="Kirchhoff Inversion Impulse Response"')

Result('ierr','graph labelsz=10 titlesz=12 unit1= unit2= title="Misfit error"')

Result('iinv_sparse','window max1=3 | grey title="Kirchhoff Inversion Impulse Response"')

Result('ierr_sparse','graph labelsz=10 titlesz=12 unit1= unit2= title="Misfit error"')

End()
