from rsfproj import *

import math

for case in ('sin','cos'):
    Flow(case,None,
         'math n1=360 d1=1 o1=0 output="%s(%g*x1)" ' % (case,math.pi/180))
Flow('one','sin','scale dscale=0')

points = '''
cat axis=2 ${SOURCES[1]} | transp | dd type=complex |
graph symbol=o plotcol=7 wanttitle=n min1=-2 max1=2 min2=-2 max2=2
scalebar=y wantaxis=n
'''

Plot('points','cos sin',points)
Flow('points','cos sin one','cat axis=2 ${SOURCES[1:3]} | transp')
Flow('dist','points','distance n1=401 n2=401 o1=-2 o2=-2 d1=0.01 d2=0.01')

dist = '''
grey color=j scalebar=y min1=-2 max1=2 min2=-2 max2=2
title=Distance allpos=y pclip=100 transp=n yreverse=n
'''

Plot('dist',dist)
Result('dist','dist points','Overlay')

for case in ('sin','cos'):
    Flow(case+'10',None,
         'math n1=27 d1=10 o1=0 output="%s(%g*x1)" ' % (case,math.pi/180))
Flow('one10','sin10','scale dscale=0')

Plot('points10','cos10 sin10',points)
Flow('points10','cos10 sin10 one10','cat axis=2 ${SOURCES[1:3]} | transp')
Flow('dist10','points10','distance n1=401 n2=401 o1=-2 o2=-2 d1=0.01 d2=0.01')

Plot('dist10',dist)
Result('dist10','dist10 points10','Overlay')

End()
