from rsf.proj import *

# files have names like:
#https://s3.amazonaws.com/open.source.geoscience/open_data/newzealand/Taranaiki_Basin/PARIHAKA-3D/Parihaka_PSTM_full_angle.sgy

# first, look at the pdf files
pdfread = WhereIs('acroread') or WhereIs('kpdf') or WhereIs('evince') or \
    WhereIs('xpdf') or WhereIs('gv') or WhereIs('open')

if pdfread:
   file='G3D1206-002release'
   Fetch('%s.pdf'%file,dir='g3d1206-002a',
         server='https://s3.amazonaws.com',
         top='open.source.geoscience/open_data/boem')
   Flow(file,file+'.pdf',
         pdfread + ' $SOURCE',stdin=0,stdout=0)

file='G3D1206_002_L87_080'
Fetch('%s.sgy'%file,dir='g3d1206-002a',
       server='https://s3.amazonaws.com',
       top='open.source.geoscience/open_data/boem',
       usedatapath=1)
#https://s3.amazonaws.com/open.source.geoscience/open_data/boem/g3d1206-002a/G3D1206_002_L87_080.sgy
Flow(['%s.rsf'%file,'%s_hdr.rsf'%file,
      '%s.thdr'%file,'%s.bhdr'%file],
     '%s.sgy'%file,
     '''
     sfsegyread
        tfile=${TARGETS[1]} 
        hfile=${TARGETS[2]}  
        bfile=${TARGETS[3]}
      ''')
Flow('%sheaderattr.txt'%file,'%s_hdr.rsf'%file,
        'sfheaderattr > $TARGET && /bin/cat $TARGET',stdout=-1)


#< G3D1206_002_L87_080_hdr.rsf sfheaderattr
#91 headers, 311640 traces
#******************************************************************************* 
#     key     	            min     	              max    	          mean
#------------------------------------------------------------------------------- 
#tracl       0              1 @ 0	           530 @ 529	         265.5
#tracr       1              1 @ 0	           530 @ 529	         265.5
#fldr        2              1 @ 0	           530 @ 529	         265.5
#tracf       3              2 @ 0	             2 @ 0	             2
#ep          4              1 @ 0	             1 @ 0	             1
#cdp         5              1 @ 0	           530 @ 529	         265.5
#cdpt        6              1 @ 0	             1 @ 0	             1
#trid        7              1 @ 0	             1 @ 0	             1
#duse       10              1 @ 0	             1 @ 0	             1
#scalel     19              1 @ 0	             1 @ 0	             1
#scalco     20              1 @ 0	             1 @ 0	             1
#sx         21         486113 @ 270299	        499351 @ 0	        492732
#sy         22         -90287 @ 0	        -75598 @ 311110	      -82942.4
#gx         23         486113 @ 270299	        499351 @ 0	        492732
#gy         24         -90287 @ 0	        -75598 @ 311110	      -82942.4
#ns         38            450 @ 0	           450 @ 0	           450
#dt         39          10000 @ 0	         10000 @ 0	         10000
#shnum      75     1065353216 @ 0	    1065353216 @ 0	   1.06535e+09
#unknown    85             64 @ 0	           651 @ 311110	         357.5
#******************************************************************************* 

#sftahread input=migrated.rsf | sftahgethw key=sx,gx,offset >/dev/null
# x coordinate must be divided by 10000 scalel and scaleco are both -10000
# group interval and group interval are 25 m 

   
End()

