from rsf.proj import *

Fetch('Parihaka_PSTM_full_angle.sgy',dir='PARIHAKA-3D',
          server='http://s3.amazonaws.com',
	  top='open.source.geoscience/open_data/newzealand/Taranaiki_Basin',
	  usedatapath=1)

#Fetch('Kerry3D.segy',dir='new-zealand-kerry3d',
#          server='http://s3.amazonaws.com',
#          top='open.source.geoscience/open_data')


#https://s3.amazonaws.com/open.source.geoscience/open_data/newzealand/Taranaiki_Basin/PARIHAKA-3D/Parihaka_PSTM_full_angle.sgy

#        key1=iline1
#        iline1=220 
Flow(['migrated.rsf','migrated_hdr.rsf',
      'migrated.thdr','migrated.bhdr'],
     'Parihaka_PSTM_full_angle.sgy',
     '''
     sfsegyread
        tfile=${TARGETS[1]} 
        hfile=${TARGETS[2]}  
	bfile=${TARGETS[3]} 
     ''')

Flow('headerattr.txt','migrated_hdr.rsf',
     'sfheaderattr > $TARGET && /bin/cat $TARGET',stdout=-1)

#sftahread input=migrated.rsf | sftahgethw key=sx,gx,offset >/dev/null
# x coordinate must be divided by 10000 scalel and scaleco are both -10000
# group interval and group interval are 25 m 
#sfheaderattr <migrated_hdr.rsf 
#91 headers, 1038162 traces
#*******************************************************************************# 
#     key     	            min     	              max    	          mean
#-------------------------------------------------------------------------------# 
#scalco     20              1 @ 0	             1 @ 0	             1
#ns         38           1168 @ 0	          1168 @ 0	          1168
#dt         39           3000 @ 0	          3000 @ 0	          3000
#cdpx       71        2565251 @ 1037036	       2589585 @ 1130	   2.57742e+06
#cdpy       72        6254630 @ 0	       6281620 @ 1038161   6.26814e+06
#iline      73           1735 @ 0	          2657 @ 1037036        2196.5
#xline      74           4200 @ 0	          5325 @ 1130	       4762.49
#******************************************************************************* 

# near trace gather
Flow(['image.rsf','image_hdr.rsf'],['migrated.rsf','migrated_hdr.rsf'],
     '''
     sftahread \
          input=${SOURCES[0]} \
	  sort="iline1 cdp" \
	  verbose=1 \
     | sftahwrite \
          output=${TARGETS[0]} \
          label2="xline" o2=4200 n2=1126 d2=1 \
          label3="iline" o3=1736 n3=922 d3=1
	  verbose=1
     ''',stdout=0, stdin=0)
       
Result("image","sfwindow j3=50 | sfgrey title='Parihaka 3d'")
Result("image3d","image",
       '''
       byte 
       | grey3 frame1=600 frame2=550 frame3=450 title='Parihaka 3D'
       ''')

       
End()
