from rsfproj import *

###########################################################################

import os
private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

for dat in ('curve','linear','random','marm'):
    input = 'input.%s.segy' % dat
    Fetch(input,'ray',private)
    Flow([dat,'./A'+dat,'./B'+dat],input,
         'segyread tape=$SOURCE read=d hfile=${TARGETS[1]} bfile=${TARGETS[2]}',
         stdin=0)

Flow('curve2','curve','window min1=1.2 max1=2 | bandpass fhi=60')
Plot('curve','curve2',
     'grey clip=0.02 yreverse=y transp=y poly=y title=Input')

Flow('left','curve2','window n2=15')
Flow('right','curve2','window f2=15')

Flow('ldip2','left',
     'twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n | window f3=1') 
Flow('ldip1','left ldip2',
     'dip2 dip0=${SOURCES[1]} order=3 nj=4 eps=10 gauss=n')
Flow('ldip','ldip1',
      'transp | spline n1=60 o1=0 d1=0.25 | transp')

Flow('rdip2','right',
     'twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n') 
Flow('rdip1','right rdip2',
     'dip2 dip0=${SOURCES[1]} order=3 nj=4 eps=10 gauss=n')
Flow('rdip','rdip1',
      'transp | spline n1=180 o1=15 d1=0.25 | transp')

Flow('left4 lones4','left','lpad jump=4 mask=${TARGETS[1]}')
Flow('ldeal','left4 ldip lones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y')

Flow('right4 rones4','right','lpad jump=4 mask=${TARGETS[1]}')
Flow('rdeal','right4 rdip rones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y')

Flow('deal','ldeal rdeal','cat axis=2 ${SOURCES[1]}')
Plot('deal',
     'grey clip=0.02 yreverse=y transp=y poly=y title=Interpolated')

Result('curve-deal','curve deal','OverUnderAniso')

Flow('linear2','linear','window min1=0.5 max1=2.7 | bandpass fhi=60')
Plot('linear','linear2',
     'grey yreverse=y transp=y poly=y title=Input')

Flow('lindip','linear2','twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n')
Flow('lindip2','lindip',
     'transp | spline n1=240 o1=0 d1=0.25 | transp')

Flow('lin4 linones4','linear2','lpad jump=4 mask=${TARGETS[1]}')
Flow('lindeal','lin4 lindip2 linones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y')
Plot('lindeal','grey yreverse=y transp=y poly=y title=Interpolated')

Result('linear-deal','linear lindeal','SideBySideAniso')

Flow('random2','random','window')
Plot('random','random2',
     'grey yreverse=y transp=y poly=y title=Input')

Flow('randip','random2','twodip2 order=3 nj1=4 nj2=4 eps=20 gauss=n')
Flow('randip2','randip',
     'transp | spline n1=240 o1=0 d1=0.25 | transp')

Flow('ran4 ranones4','random2','lpad jump=4 mask=${TARGETS[1]}')
Flow('randeal','ran4 randip2 ranones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y')
Plot('randeal','grey yreverse=y transp=y poly=y title=Interpolated')

Result('random-deal','random randeal','OverUnderAniso')

Flow('marm2','marm','window | bandpass fhi=30')
Plot('marm','marm2',
     'grey yreverse=y transp=y poly=y title=Input')

Flow('mleft','marm2','window n2=16')
Flow('mright','marm2','window f2=16')

Flow('mldip2','mleft',
     'twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n')
Flow('mldip0','mldip2','window f3=1')
Flow('mldip1','mleft mldip0',
     'twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n dip2=${SOURCES[1]}')
Flow('mldip','mldip1',
     'transp | spline n1=64 o1=0 d1=0.25 | transp')

Flow('mrdip2','mright',
     'twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n')
Flow('mrdip0','mrdip2','window n3=1')
Flow('mrdip1','mright mrdip0',
     'twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n dip1=${SOURCES[1]}')
Flow('mrdip','mrdip1',
     'transp | spline n1=96 o1=16 d1=0.25 | transp')

Flow('mleft4 mlones4','mleft','lpad jump=4 mask=${TARGETS[1]}')
Flow('mldeal','mleft4 mldip mlones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y')

Flow('mright4 mrones4','mright','lpad jump=4 mask=${TARGETS[1]}')
Flow('mrdeal','mright4 mrdip mrones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y')

Flow('marmdip0','mldip1 mrdip1','cat axis=2 ${SOURCES[1]}')
Flow('mdip1','marmdip0','window n3=1')
Flow('mdip2','marmdip0','window f3=1')

Flow('marmdip','marm2 mdip1 mdip2',
     '''
     twodip2 order=3 nj1=4 nj2=4 eps=10 gauss=n niter=10
     dip1=${SOURCES[1]} dip2=${SOURCES[2]}
     ''')
Flow('marmdip4','marmdip','transp | spline n1=160 o1=0 d1=0.25 | transp')

Flow('marm4 marmones4','marm2','lpad jump=4 mask=${TARGETS[1]}')
Flow('marmdeal','marm4 marmdip4 marmones4',
     'planemis2 dip=${SOURCES[1]} mask=${SOURCES[2]} order=3 verb=y prec=y')
Plot('marmdeal','grey yreverse=y transp=y poly=y title=Interpolated')

Result('marm-deal','marm marmdeal','OverUnderAniso')

Flow('marmcomp','marmdeal marmdip4',
     'pwdsigk dips=${SOURCES[1]} verb=y eps=10')
Plot('mcomp1','marmcomp','window f3=1 | grey title="First Component" ')
Plot('mcomp2','marmcomp','window n3=1 | grey title="Second Component" ')

Result('marm-comp','mcomp1 mcomp2','OverUnderAniso')

###########################################################################
End()
