#############################################################################
###################### COMMON DEFINITIONS - DO NOT ALTER ####################
#############################################################################
from rsf.proj import *
from rsf.recipes.iwave import getFlowSignature
WORKPATH        = os.getenv('DATAPATH')
# todo: WORKPATH should be checked
#Decider('timestamp-match')
#############################################################################
###################### END COMMON DEFINITIONS ###############################
#############################################################################

######################## LOCAL DEFINITIONS ##################################

######## abbreviations for commands used in flows - put these first, if
######## you use abbreviations. Note that Madagascar commands do not 
######## require abbreviations 
# Example:
#          CWPROOT         = os.getenv('CWPROOT')
#          ...
#          sunull          = os.path.join(CWPROOT,'bin/sunull')
CWPROOT         = os.getenv('CWPROOT')
sunull          = os.path.join(CWPROOT,'bin/sunull')
sushw           = os.path.join(CWPROOT,'bin/sushw')
suchw           = os.path.join(CWPROOT,'bin/suchw')
sugain          = os.path.join(CWPROOT,'bin/sugain')
suwaveform      = os.path.join(CWPROOT,'bin/suwaveform')
supsimage       = os.path.join(CWPROOT,'bin/supsimage')
IWAVE           = os.getenv('NEWIWAVE')
stdmdl          = os.path.join(IWAVE,'demo/main/standardmodel.x')
towed_array     = os.path.join(IWAVE,'trace/main/towed_array.x')
#acd             = os.path.join(IWAVE,'acd/main/acd.x')
acd             = os.path.join(IWAVE,'newacd/main/acd.x')

######### fetch list - non-reproducible data fetched from web archive.
# the format for this dictionary is 
#    filename : [<subdir of "data" directory in archive>, <archive URL>]
# Example: 
# fetches = {
#            'line_fix.su' : ['marmousi', 'http://www.trip.caam.rice.edu'],
#            'velocity.HH' : ['marmousi', 'http://www.trip.caam.rice.edu'],	
#           }
fetches = {
           'vel_4layer.HH': ['obs', 'http://www.trip.caam.rice.edu']
          }
for file in fetches.keys():
    Fetch(file,fetches[file][0],server=fetches[file][1]) 

######### non-IWAVE flows - include these in standard Madagascar form
# sunull writes to stdout but does not read from stdin, so set
# stdin=0
Flow('hdr12000.su', None,
     sunull + ' nt=651 ntr=400 dt=0.008 | ' + 
     sushw + ' key=sx a=12000 c=0 j=400 | ' + 
     sushw + ' key=gx a=5000 b=25 j=400 | ' + 
     sushw + ' key=delrt a=0 | ' +  
     sushw + ' key=selev a=-1875 | ' + 
     sushw + ' key=gelev a=-6 | ' + 
     sushw + ' key=scalel a=0 | ' + 
     sushw + ' key=scalco a=0 | ' + 
     suchw + ' key1=offset key2=gx key3=sx b=1 c=-1 > ${TARGETS[0]} ',
     stdin=0)
Flow('hdr8-12km.su', None,
     sunull + ' nt=651 ntr=4800 dt=0.008 | ' + 
     sushw + ' key=sx a=8000 c=400 j=400 | ' + 
     sushw + ' key=gx a=5000 b=25 j=400 | ' + 
     sushw + ' key=delrt a=0 | ' +  
     sushw + ' key=selev a=-1875 | ' + 
     sushw + ' key=gelev a=-6 | ' + 
     sushw + ' key=scalel a=0 | ' + 
     sushw + ' key=scalco a=0 | ' + 
     suchw + ' key1=offset key2=gx key3=sx b=1 c=-1 > ${TARGETS[0]} ',
     stdin=0)

# sfadd writes output to stdout, so it must be left active - 
# however there is not pipe input to this command, so stdin=0
Flow('csq_4layer','vel_4layer.HH',
     'dd form=native | sfadd mode=p ${SOURCES[0]} ${SOURCES[0]} | sfput data_type=csq ')

# smooth csq_4layer to make migration velocity model
Flow('csq_4layersm','csq_4layer','smooth rect1=50 rect2=50 repeat=4')
Flow('csq_4layersm2','csq_4layer','smooth rect1=5 rect2=5 repeat=4')
Flow('dcsq_4layer', ['csq_4layer', 'csq_4layersm2'],
     'add mode=a scale=1,-1 < csq_4layer.rsf csq_4layersm2.rsf') 

# create base wavelet (just time series, without source position
# information) via suwaveform
Flow('wavelet_base.su','',
     suwaveform + ' type=gaussd fpeak=5 ns=101 | ' + 
     sushw + ' key=delrt  a=-100 | ' +  
     sugain + ' scale=1.e6 > ${TARGETS[0]} ',
     stdin=0)

# add source coordinates from hdrfile to source AND receiver 
# coordinates from wavelet to create "dressed" wavelet for array
# source option in iwave. Note that iwave reads a source GATHER by
# detecting new source coordinates (sx, sy, selev) but assigns source
# trace GRID POSITIONS in the array by receiver coordinates (gx, gy, 
# gelev). The towed array app sets these coordinates up so that each 
# shot may have an array of sources, with the source traces in the 
# same position relative to the data source coordinates - hence 
# "towed_array".

# use naming convention: time series stored in wavelet_base, 
# headers for experiment foo stored in hdrfoo.su, wavelet in
# waveletfoo.su

for foo in ['12000', '8-12km']:
    Flow('wavelet' + foo + '.su', ['wavelet_base.su', 'hdr' + foo + '.su'],
         towed_array + 
         '''
         data=${SOURCES[1]} 
         src=${SOURCES[0]} 
         towed=${TARGETS[0]}
         ''',
         stdin=0, stdout=0)

# initial data - near-impulse in u0, u1=0 - very wierd, should be fixed!!
Flow('init',None,'makevel n1=416 n2=800 d1=25 d2=25 dlens=200 tlens=200 v000=0 vlens=100 x1lens=1875 x2lens=12000 | sfput id1=0 id2=1 id3=2 dim=2 gdim=3 n3=1 o3=0 d3=1')

# movie-init output file
t=Flow(['movieinit.work', 'movieinit.rsf'],['init.rsf','csq_4layer.rsf'],
	'''				
	sfmakevel n1=416 n2=800 n3=33 d1=25 d2=25 d3=160 v000=0  | 
	sfput id1=0 id2=1 id3=2 dim=2 gdim=3 > movieinit.rsf; 
	/bin/rm -rf movieinit.work; 
	/bin/mkdir movieinit.work; 
	cd movieinit.work;
	'''
	+  acd  + ' ' +
	'deriv=0 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layer.rsf init=../init.rsf ' + 
        'sampord=1 movie=../movieinit.rsf',
	stdin=0,stdout=0)
Clean(t,'movieinit.work')

# movie-src output file
t=Flow(['moviesrc.work', 'moviesrc.rsf'],['wavelet12000.su','csq_4layer.rsf'],
	'''
	sfmakevel n1=416 n2=800 n3=33 d1=25 d2=25 d3=160 v000=0  | 
	sfput id1=0 id2=1 id3=2 dim=2 gdim=3 > moviesrc.rsf; 
	/bin/rm -rf moviesrc.work; 
	/bin/mkdir moviesrc.work; 
	cd moviesrc.work;
	'''
	+  acd  + ' ' +
	'deriv=0 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layer.rsf source=../wavelet12000.su ' + 
        'sampord=1 movie=../moviesrc.rsf',
	stdin=0,stdout=0)
Clean(t,'moviesrc.work')

# trace-src output file
t=Flow(['shot12000.work', 'shot12000.su'],['wavelet12000.su','csq_4layer.rsf'],
	'''
	/bin/cp hdr12000.su shot12000.su;
	/bin/rm -rf shot12000.work; 
	/bin/mkdir shot12000.work; 
	cd shot12000.work;
	'''
	+  acd  + ' ' +
	'deriv=0 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layer.rsf source=../wavelet12000.su ' + 
        'sampord=1 data=../shot12000.su',
	stdin=0,stdout=0)
Clean(t,'shot12000.work')

# linearized modeling
t=Flow(['born12000.work', 'born12000.su'],['wavelet12000.su','csq_4layersm.rsf','dcsq_4layer.rsf'],
	'''
	/bin/cp hdr12000.su born12000.su;
	/bin/rm -rf born12000.work; 
	/bin/mkdir born12000.work; 
	cd born12000.work;
	'''
	 +  acd  + ' ' +
	'deriv=1 adjoint=0 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layersm.rsf csq_d1=../dcsq_4layer.rsf source=../wavelet12000.su ' + 
        'sampord=1 data=../born12000.su',
	stdin=0,stdout=0)
Clean(t,'born12000.work')

# rtm
t=Flow(['migr12000.work', 'migr12000.rsf'],['born12000.su'],
	'''
	sfscale < dcsq_4layer.rsf > migr12000.rsf dscale=0.0;
	/bin/rm -rf migr12000.work; 
	/bin/mkdir migr12000.work; 
	cd migr12000.work;
	'''
	 +  acd  + ' ' +
	'deriv=1 adjoint=1 nsnaps=10 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layersm.rsf csq_b1=../migr12000.rsf source=../wavelet12000.su ' + 
        'sampord=1 data=../born12000.su',
	stdin=0,stdout=0)
Clean(t,'migr12000.work')

# 12 shot "line"
t=Flow(['line8-12km.work', 'line8-12km.su'],['wavelet8-12km.su','csq_4layer.rsf'],
	'''
	/bin/cp hdr8-12km.su line8-12km.su;
	/bin/rm -rf line8-12km.work; 
	/bin/mkdir line8-12km.work; 
	cd line8-12km.work;
	'''
	 +  acd  + ' ' +
	'deriv=0 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layer.rsf source=../wavelet8-12km.su ' + 
        'sampord=1 data=../line8-12km.su',
	stdin=0,stdout=0)
Clean(t,'line8-12km.work')

# 12 shot linearized simulation
t=Flow(['born8-12km.work', 'born8-12km.su'],['wavelet8-12km.su','csq_4layersm.rsf','dcsq_4layer.rsf'],
	'''
	/bin/cp hdr8-12km.su born8-12km.su;
	/bin/rm -rf born8-12km.work; 
	/bin/mkdir born8-12km.work; 
	cd born8-12km.work;
	'''
	 +  acd  + ' ' +
	'deriv=1 adjoint=0 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layersm.rsf csq_d1=../dcsq_4layer.rsf source=../wavelet8-12km.su ' + 
        'sampord=1 data=../born8-12km.su',
	stdin=0,stdout=0)
Clean(t,'born8-12km.work')

# rtm
t=Flow(['migr8-12km.work', 'migr8-12km.rsf'],['born8-12km.su'],
	'''
	sfscale < dcsq_4layer.rsf > migr8-12km.rsf dscale=0.0;
	/bin/rm -rf migr8-12km.work; 
	/bin/mkdir migr8-12km.work; 
	cd migr8-12km.work;
	'''
	 +  acd  + ' '
	'deriv=1 adjoint=1 nsnaps=10 order=2 cfl=0.5 cmin=1.0 cmax=5.0 ' +
        'csq=../csq_4layersm.rsf csq_b1=../migr8-12km.rsf source=../wavelet8-12km.su ' + 
        'sampord=1 data=../born8-12km.su',
	 stdin=0,stdout=0)
Clean(t,'migr8-12km.work')

Result('csq_4layer', 'csq_4layer', 'put label1=Depth unit1=m label2=Distance unit2=m label=V_p^2 unit=m^2/ms^2 | grey color=c mean=y title="Atlantis Cartoon" scalebar=y barreverse=y')

Result('csq_4layersm', 'csq_4layersm', 'put label1=Depth unit1=m label2=Distance unit2=m label=V_p^2 unit=m^2/ms^2 | grey color=c mean=y title="MigVel - Atlantis Cartoon" scalebar=y barreverse=y')

Result('dcsq_4layer', 'dcsq_4layer', 'put label1=Depth unit1=m label2=Distance unit2=m label=V_p^2 unit=m^2/ms^2 | grey color=c mean=y title="Delta V_p^2 - Atlantis Cartoon" scalebar=y barreverse=y')

Result('gauss', 'init', 'put label1=Depth unit1=m label2=Distance unit2=m label=Pressure unit=GPa | grey color=c mean=y clip=100 title="Gaussian Data t=0.0 s" scalebar=y barreverse=y')

Result('frameinit', 'movieinit', 'window f3=21 n3=1 |put label1=Depth unit1=m label2=Distance unit2=m label=Pressure unit=GPa | grey color=c mean=y clip=300 title="Gaussian data t=3.2 s" scalebar=y barreverse=y')

Result('wavelet','wavelet_base.su', 'suread endian=0 read=data < $SOURCE | put label1=Time label2=Pressure unit1=s unit2=GPa title="Gaussian deriv fmax=5 Hz" unit=GPa |sfgraph')

Result('framesrc', 'moviesrc', 'window f3=21 n3=1 |put label1=Depth unit1=m label2=Distance unit2=m label=Pressure unit=GPa | grey color=c mean=y clip=1.e+8 title="Point source 5 Hz t=3.2 s" scalebar=y barreverse=y')

Result('shot12000','shot12000.su', 'suread endian=0 read=data < $SOURCE | put label1=Time label2=Distance d2=0.025 o2=5 unit1=s unit2=km title="Node at 12 km" label=Pressure unit=GPa |sfgrey scalebar=y barreverse=y')

Result('born12000','born12000.su', 'suread endian=0 read=data < $SOURCE | put label1=Time label2=Trace unit1=s title="Born x_s=12000 m" unit=GPa | sfgrey')

Result('migr12000', 'migr12000', 'put label1=Depth unit1=m label2 = Distance unit2=m label=V_p^2 unit=m^2/ms^2 | grey color=c mean=y title="RTM of Born Shot x_s = 12000" clip=1.e+12')

Result('line8-12km','line8-12km.su', 'suread endian=0 read=data < $SOURCE | put label1=Time label2=Node d2=0.4km o2=8 unit1=s unit2=km title="Nodes @0.4km" label=Pressure unit=GPa |sfgrey scalebar=y barreverse=y')

Result('born8-12km','born8-12km.su', 'suread endian=0 read=data < $SOURCE | put label1=Time label2=Trace unit1=s title="Born x_s=8-12km" unit=GPa | sfgrey')

Result('migr8-12km', 'migr8-12km', 'put label1=Depth unit1=m label2 = Distance unit2=m label=V_p^2 unit=m^2/ms^2 | grey color=c mean=y title="RTM of Born Shot x_s = 8-12km" clip=1e+12')

End()

