from rsf.proj import *

def plot(title):
    return '''
    grey wantaxis1=n label1=Sample label2=Trace title="%s"
    labelsz=12 titlesz=15 crowd1=0.9
    ''' % title

Flow('signal',None,'make second=n n1=75 n2=32 t1=2')
Plot('signal',plot('Signal'))

Flow('make',None,'make second=y n1=75 n2=32 t1=2 | put o1=0 d1=1 o2=0 d2=1')
Plot('make',plot('Signal+Noise'))

Flow('pq','make','twodip2 verb=y gauss=n')
Flow('rec','make pq',
     	'''
     	mcaseislet dips=${SOURCES[1]} 
	verb=y order=1 type=b eps=0.01 niter=20 pclip=5 pscale=100 
     	''')

Flow('rec1','rec','window n3=1')
Flow('rec2','rec','window f3=1')
Plot('rec1',plot('comp1'))
Plot('rec2',plot('comp2'))
Result('signalnoise','signal make rec1 rec2', 'SideBySideAniso')

End()

