from rsf.proj import *


Flow('vel',None,
     	'''
     	math output=2.0 n1=200 n2=200 d1=0.005 d2=0.005
     	label1=x1 unit1=km label2=x2 unit2=km 
     	''')


Flow('wav','vel','Testfd2d nt=1000 dt=0.001')


Result('wav',
       '''
       grey color=j  title="wavefield snap" scalebar=y
       ''')




End()
