"--------------- universal VPLOT filter options -------------------------------",
" in=[stdin](file)   | endpause=[y,n](d)| interact=[null](output_file)",
" pause=[0](secs)    | shade=[y,n]      | style=[standard,rotated]",
" fat=[0]            | wantras=[y,n](d) | erase=[y,n,once,literal]",
" fatmult=[1.0]      | overlay=[n,y]    | size=[rel,abs](d)",
" scale=[1.0]        | frame=[n,y]      | rotate=0 (degrees)",
" xscale=[1.0]       | mono=[n,y](d)    | dither=1(0=no 1=rn 2=od 3=fs 4=ht)(d)",
" yscale=[1.0]       | window=[y,n]     | pixc=[1.0](d)  greyc=[1.0](d)",
" hshift=[0.0](inch) | echo=[n,y] (d)   | xcenter,ycenter= (inch)",
" vshift=[0.0](inch) | break=[b,e,i]    | xwmin,ywmin,xwmax,ywmax= (inch)",
" txscale=[1.0]      | invras=[y,n]     | dashscale=[1.0]",
" txfont=[0](0-16)(d)| txsquare=[y,n]   | mkscale=[1.0]",
" cachepipe=[n,y]    | serifs=[y,n]     |              ",
