from rsfproj import *
import zomig


#v(x,z)=2+2exp(-x^2-(y-2)^2), -3<=x<=3, 0<=t<=1
#vf=v found, 300x300
#ve= v exact, 300x300
#vd = the input data, 300x200

xmax=10
tmax=1
zmax=2.3383

nx=150
nt=75
nz=75

dx = 1.0*xmax/(nx-1)
dt = 2.0*tmax/(nt-1)
dz = 1.0*zmax/(nz-1)

for case in ('vf','ve','vd'):
    intime = (case == 'vd')
    
    Fetch(case+'.dat','geolet')
    Flow(case,case+'.dat',
         '''
         echo in=$SOURCE
         n1=%d o1=0 d1=%g
         n2=%d o2=0 d2=%g
         label1=Lateral unit1=km
         label2=%s unit2=%s
         label=Velocity unit=km/s
         data_format=ascii_float |
         dd form=native |
         transp
         ''' % (nx,dx,
                (nz,nt)[intime],
                (dz,dt)[intime],
                ('Depth','Time')[intime],
                ('km','s')[intime]),
         stdin=0)


def zgrey(title):
    return '''
    grey color=j allpos=y bias=2 clip=1.2
    title="%s" scalebar=y bartype=v barreverse=y
    screenwd=%g screenht=%g 
    labelsz=6 minval=2 maxval=3.2 wanttitle=y
    barlabel=Velocity barunit=km/s wanttitle=n
    ''' % (title,1.4*xmax,1.4*zmax)

Result('ve',zgrey('Interval Velocity'))
Plot('vf',zgrey('Estimated Interval Velocity'))

Result('vd',
       '''
       grey color=j allpos=y scalebar=y bias=2 barreverse=y
       barlabel=Velocity barunit=km/s bartype=v pclip=100
       wanttitle=y title="Dix Velocity (in Time)" minval=2 maxval=3.2
       ''')

Result('vd2','vd',
       '''
       time2depth velocity=$SOURCE nz=%d dz=%g z0=0 intime=y |
       put label1=Depth unit1=km |
       ''' % (nz,dz) + zgrey('Dix Velocity in Depth'))

for case in ('xstar','ystar'):
    Fetch(case+'.dat','geolet')
    Flow(case,case+'.dat',
         '''
         echo in=$SOURCE
         n1=150 n2=150
         data_format=ascii_float |
         dd form=native |
         transp
         ''',stdin=0)


Plot('rays','xstar ystar',
     '''
     cmplx ${SOURCES[:2]} | window j2=2 |
     graph yreverse=y scalebar=y bartype=v
     screenwd=%g screenht=%g wanttitle=n
     min1=0 max1=%g min2=0 max2=%g pad=n
     wantaxis=n plotcol=7
     ''' % (1.4*xmax,1.4*zmax,xmax,zmax),stdin=0)

Result('vf','vf rays','Overlay')

End()
