from rsfproj import *

Fetch('french.asc','french')

Flow('french','french.asc','dd form=native | transp | scale dscale=2')
Result('french',
       '''
       grey allpos=y bias=1000 scalebar=n barlabel="Depth (m)"
       screenratio=1 title="French model"
       ''')

Flow('refl','french',
     '''
     remap1 n1=161 o1=0 d1=51.325 | transp |
     remap1 n1=161 o1=0 d1=51.325 | transp
     ''')

Flow('dipx','refl','smooth rect1=5 | deriv')
Flow('dipy','refl','transp | smooth rect1=5 | deriv | transp')

Result('french3','refl',
       '''
       unif3 v00=1,2 n1=401 d1=10.265 |
       byte allpos=y bias=1 |
       grey3 color=j title="French model" label1="Depth (m)"
       frame1=175 frame2=60 frame3=80 flat=n 
       ''')

Flow('shot3','refl dipx dipy',
     '''
     kirmod3 nt=601 dt=0.010265 vel=2000
     dipx=${SOURCES[1]} dipy=${SOURCES[2]}
     h0x=-6159 dhx=102.65 nhx=121
     h0y=-6159 dhy=102.65 nhy=121
     nsx=1 s0x=4 dsx=51.325
     nsy=1 s0y=4 dsy=51.325 freq=5 
     ''')

Result('shot3',
       '''
       byte gainpanel=all |
       grey3 title="3-D shot" label1="Time (s)"
       frame1=300 frame2=61 frame3=61 flat=n
       ''')

End()
