<allshots.su suwind key=fldr min=18 max=21 | suximage perc=90 title=check18 f2=1 &

<allshots.su suwind key=fldr min=1041 max=1044 | suximage perc=90 title=check1041 f2=1 &

<allshots.su suwind key=fldr min=1838  max=1841 | suximage perc=90 title=check1838 f2=1 &

<allshots.su suwind key=fldr min=2197  max=2201 | suximage perc=90 title=check2197 f2=1 &

<allshots.su suwind key=fldr min=2470  max=2473 | suximage perc=90 title=check2470 f2=1 &


