from rsf.suproj import *
import os

# Download SEGY data
server=os.environ.get('RSF_DATASERVER','http://www.ahay.org')
Fetch('data2013.sgy','kfupm',server=server)

# Convert to SU
Flow('data ./binary ./header','data2013.sgy',
     'segyread tape=$SOURCE verbose=1 endian=0 | segyclean',
     stdin=0)

# Gain using AGC
Flow('data-agc','data','sugain agc=1 wagc=0.5')

# Gain using t^2
Flow('data-tm','data','sugain agc=0 tpow=2 qclip=0.95 qbal=1')

# Display first 6 shot records
display6 = 'suwind key=ep min=1 max=6 | suxwigb'

for data in Split('data data-agc data-tm'):
    Result(data,display6)

# Take Fourier transform and compute amplitude spectrum
Flow('data-tm-as','data-tm','suspecfx')
Result('data-tm-as',display6)

# Filter data to remove ground-roll
Flow('data-tm-filt','data-tm','sufilter f=15,20,50,60')
Result('data-tm-filt',display6)

# Autocorrelation
Flow('data-tm-filt-ac','data-tm-filt','suacor ntout=1001 sym=0')
Result('data-tm-filt-ac',display6)

# Spiking deconvolution
Flow('data-tm-filt-dec','data-tm-filt',
     'supef minlag=0.002 maxlag=0.2 pnoise=0.001 mincorr=0 maxcorr=3')
Result('data-tm-filt-dec',display6)

End()
