from rsf.proj import *

# files have names like:
#https://s3.amazonaws.com/open.source.geoscience/open_data/stratton/segy/cdp_gathers/cdpgathers_142-200.sgy
# file names can be 
# cdpgathers_142-200.sgy
files=['cdpgathers_2-80','cdpgathers_82-140','cdpgathers_142-200','cdpgathers_202-290','cdpgathers_290-310','cdpgathers_601-630']
filesrsf=[]
filesrsf_hdr=[]
for file in files:
    filesrsf.append('%s.rsf'%file)
    filesrsf_hdr.append('%s_hdr.rsf'%file)
    Fetch('%s.sgy'%file,
          dir='stratton/segy/cdp_gathers',
          server='http://s3.amazonaws.com',
	  top='open.source.geoscience/open_data',
	  usedatapath=1)
    Flow(['%s.rsf'%file,
          '%s_hdr.rsf'%file,
          '%s.thdr'%file,
          '%s.bhdr'%file],
         '%s.sgy'%file,
         '''
         sfsegyread
             tfile=${TARGETS[1]} 
             hfile=${TARGETS[2]}  
	     bfile=${TARGETS[3]} 
         ''')
# i'll process files[0:4] files[4:6] have funny o1 and fldr,cdp headers
#do not make sense.
  
print('filesrsf=',filesrsf)
print('filesrsf_hdr=',filesrsf_hdr)
print(len(filesrsf))
Flow('cdpgathers_all.rsf',filesrsf,
     '''
     sfcat ${SOURCES[0:4]} axis=2
     ''',stdin=0)
Flow('cdpgathers_all_hdr.rsf',filesrsf_hdr,
     '''
     sfcat ${SOURCES[0:4]} axis=2
     ''',stdin=0)


Flow('cdpgathers_all.txt','cdpgathers_all_hdr.rsf',
         'sfheaderattr > $TARGET && /bin/cat $TARGET',stdout=-1)

# well 9 (the one with the vsp) is at iline 200, xline 118.
Flow('gatheril200xline118.rsf gatheril200xline118_hdr.rsf',
     'cdpgathers_all.rsf cdpgathers_all_hdr.rsf',
     '''
     sftahsort input=${SOURCES[0]}    \
          sort="fldr:200,200 cdp:118,118 offset" \
     | sftahwindow tmax=1.7 \
     | sftahheadermath output=fldr outputkey=iline
     | sftahheadermath output=cdp   outputkey=xline
     | sftahwrite output=${TARGETS[0]} mode=seq
     ''',stdin=0,stdout=0)
Result('gatheril200xline118w','gatheril200xline118',
       'sfwindow min1=.600 | sfwiggle transp=y yreverse=y')
Result('gatheril200xline118','gatheril200xline118',
       'sfwindow min1=.600 | sfgrey transp=y yreverse=y')

End()
