from rsfproj import *

Flow('r',None,'spike n1=201 nsp=4 k1=25,75,125,175 mag=1,-1,0.5,-0.5 d1=1 label1=Sample unit1=')
Flow('d','r','math output="-sin(0.05*x1)" ')
Flow('n','d r','add mode=p ${SOURCES[1]} | noise seed=2007 var=0.004')

Result('dat','n d r','cat axis=2 ${SOURCES[1:3]} | dots labels=numerator:denominator:ratio gaineach=n yreverse=n')

Flow('r0','r','math output=1')
eps = 0.008

for i in range(10):
    r0 = 'r%d' % i
    r  = 'r%d' % (i+1)
    Flow(r,['n','d',r0],'math d=${SOURCES[1]} r=${SOURCES[2]} output="input*d*r*r/(d*d*r*r+%g)" ' % eps)

Result('rat','r1 r2 r3 r10','cat axis=2 ${SOURCES[1:4]} | dots labels=iter=1:iter=2:iter=3:iter=10 gaineach=n yreverse=y')

Fetch('marmvel.hh','marm')
Flow('trace','marmvel.hh','dd form=native | window n2=1')
Flow('refl','trace','depth2time velocity=$SOURCE nt=1251 dt=0.002 | ai2refl | scale axis=1 | put label1=Time unit1=s')

Flow('den','refl','math output="-sin(10*x1)" ')
Flow('num','den refl','add mode=p ${SOURCES[1]} | noise seed=2007 var=0.0004')

Result('mdat','num den refl','cat axis=2 ${SOURCES[1:3]} | dots labels=numerator:denominator:reflectivity gaineach=n yreverse=n title=')

Flow('refl0','refl','math output=1')
eps = 0.001

for i in range(10):
    r0 = 'refl%d' % i
    r  = 'refl%d' % (i+1)
    Flow(r,['num','den',r0],'math d=${SOURCES[1]} r=${SOURCES[2]} output="input*d*r*r/(d*d*r*r+%g)" ' % eps)

Result('mrat','refl1 refl2 refl3 refl10','cat axis=2 ${SOURCES[1:4]} | dots labels=iter=1:iter=2:iter=3:iter=10 gaineach=n yreverse=y title=')


End()
