from rsfproj import *

grey = 'grey allpos=y pclip=100 wantaxis=n screenratio=1 title=%s'

for case in ('A','B','F','G'):
    Fetch(case+'.rsf','blur')
    case2 = string.lower(case*2)
    Flow(case2,case+'.rsf','dd form=native')
    Result(case2,grey % case)

# simple inversion
Flow('inv','gg aa bb',
     '''
     kron adj=y inv=y mat1=${SOURCES[1]} mat2=${SOURCES[2]}
     eps=0.01 niter=25
     ''')
Result('inv',grey % 'Inversion')

End()
