/* This file is automatically generated. DO NOT EDIT! */

#ifndef _fft3_h
#define _fft3_h


int fft3_init(bool cmplx1        /* if complex transform */,
	      int pad1           /* padding on the first axis */,
	      int nx,   int ny,   int nz   /* input data size */, 
	      int *nx2, int *ny2, int *nz2 /* padded data size */);
/*< initialize >*/


void fft3(float *inp      /* [n1*n2*n3] */, 
	  sf_complex *out /* [nk*n2*n3] */);
/*< 3-D FFT >*/


void ifft3_allocate(sf_complex *inp /* [nk*n2*n3] */);
/*< allocate inverse transform >*/


void ifft3(float *out      /* [n1*n2*n3] */, 
	   sf_complex *inp /* [nk*n2*n3] */);
/*< 3-D inverse FFT >*/

#endif
