from rsf.proj import *
from rsf.recipes.galilee import Galilee

def plot(title,allpos=0):
    return '''
    grey allpos=%d pclip=94
    crowd=.82 title="%s" yreverse=n transp=n
    label2="north-south (km)" label1="west-east (km)"
    ''' % (allpos,title)

Galilee('mesh')
Plot('mesh',plot('Binned',1))

Flow('fill','mesh','lapfill grad=y niter=20')
Plot('fill',plot('Missing filled',1))
Plot('cros','fill',
     '''window j2=20 |
     graph yreverse=y crowd=.82 label1="west-east (km)" label2="depth (m)"
     wherexlabel=t
     ''')
Plot('ruf2','fill','igrad | ' + plot('Filled and d/dx'))

Result('locfil','mesh fill cros ruf2','TwoRows')

###########################################################################
End()
