from rsf.proj import *

#Medium test model
Flow('grad',None,'math n1=128 n2=512 output="0.5+x1*0.005"')
Result('grad','grey color=g label1="Depth" unit1="km" label2="Width" unit2="km" scalebar=y barreverse=y barlabel="Velocity" barunit="km/s" screenratio=0.3 screenht=3 barlabelsz=4 labelsz=4. title=""')
Flow(['times','rays','ctime'],'grad','sfgpurayt bs=16 ord=6 sx=1 sz=0 ray=${TARGETS[1]} ctime=${TARGETS[2]}')
Plot('rays','window max3=0 max2=400 j2=20 | graph wantaxis1=n yreverse=y labelsz=4. scalebar=y screenratio=0.3 screenht=3 min2=-0.5 max2=127.5 min1=0 max1=512 title=""')
Plot('times','transp | grey color=g label1="Depth" unit1="km" label2="Width" unit2="km" scalebar=y barreverse=y barlabel="Traveltime" barunit="ms" labelsz=4. screenratio=0.3 screenht=3 title=""')
Result('timesrays','times rays','Overlay')

End()
