from rsf.tex import *

End(lclass='geophysics',use='amsmath,amssymb,listings,multirow,array',
    color='''
    vp0 epsi del the vp-hess epsilon-hess delta-hess 
    ElasticxKS ElasticzKS ElasticPxKS ElasticPzKS ElasticSxKS ElasticSzKS
    ElasticxFD ElasticzFD ElasticPxFD ElasticPzFD ElasticSxFD ElasticSzFD
    ElasticxPSLR ElasticzPSLR
    ElasticPxPSLR ElasticPzPSLR ElasticSxPSLR ElasticSzPSLR
    ElasticxPSLR1 ElasticzPSLR1 ElasticPxPSLR1 ElasticPzPSLR1 ElasticSxPSLR1 ElasticSzPSLR1
    ElasticxPSLRInterfC ElasticzPSLRInterfC 
    ElasticxKSInterfC   ElasticzKSInterfC 
    ElasticxKSSInterfC  ElasticzKSSInterfC
    ElasticxFDInterfC   ElasticzFDInterfC
    ElasticxKSSInterf   ElasticzKSSInterf
    ElasticxPSLR1Interf  ElasticzPSLR1Interf 
    ElasticPxPSLR1Interf ElasticPzPSLR1Interf
    ElasticSxPSLR1Interf ElasticSzPSLR1Interf
    ElasticPxPSLRInterf  ElasticPzPSLRInterf
    ElasticSxPSLRInterf  ElasticSzPSLRInterf
    ElasticxPSLRInterf   ElasticzPSLRInterf
    ''')
