#include "../../api/f90/cfortran.h"

#include <rsf.h>

#include "vplot.h"

#ifdef f2cFortran /* f2c adds an extra underscore */
#undef fcallsc
#define fcallsc(UN,LN) append_fcallsc(_,_,UN,LN)
#endif 

FCALLSCSUB0(vp_init,VP_INIT,vp_init)
FCALLSCFUN0(INT,vp_getint,SF_GETINT,vp_getint)
FCALLSCSUB1(vp_putint,VP_PUTINT,vp_putint,INT)
FCALLSCSUB1(vp_putfloat,VP_PUTFLOAT,vp_putfloat,FLOAT)
FCALLSCSUB1(vp_putfloat0,VP_PUTFLOAT0,vp_putfloat0,FLOAT)
FCALLSCSUB0(vp_egroup,VP_EGROUP,vp_egroup)
FCALLSCSUB0(vp_erase,VP_ERASE,vp_erase)
FCALLSCSUB1(vp_fat,VP_FAT,vp_fat,INT)
FCALLSCSUB3(vp_fill,VP_FILL,vp_fill,FLOATV,FLOATV,INT)
FCALLSCSUB3(vp_ufill,VP_UFILL,vp_ufill,FLOATV,FLOATV,INT)
FCALLSCSUB6(vp_area,VP_AREA,vp_area,FLOATV,FLOATV,INT,INT,INT,INT)
FCALLSCSUB6(vp_uarea,VP_UAREA,vp_uarea,FLOATV,FLOATV,INT,INT,INT,INT)
FCALLSCSUB4(vp_coltab,VP_COLTAB,vp_coltab,INT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB7(vp_gtext,VP_GTEXT,vp_gtext,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,STRING)
FCALLSCSUB7(vp_ugtext,VP_UGTEXT,vp_ugtext,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,STRING)
FCALLSCSUB4(vp_hatchload,VP_HATCHLOAD,vp_hatchload,INT,INT,INT,INTV)
FCALLSCSUB1(vp_message,VP_MESSAGE,vp_message,STRING)
FCALLSCSUB2(vp_move,VP_MOVE,vp_move,FLOAT,FLOAT)
FCALLSCSUB2(vp_umove,VP_UMOVE,vp_umove,FLOAT,FLOAT)
FCALLSCSUB2(vp_orig,VP_ORIG,vp_orig,FLOAT,FLOAT)
FCALLSCSUB2(vp_uorig,VP_UORIG,vp_uorig,FLOAT,FLOAT)
FCALLSCSUB5(vp_patload,VP_PATLOAD,vp_patload,INT,INT,INT,INT,INTV)
FCALLSCSUB2(vp_pendn,VP_PENDN,vp_pendn,FLOAT,FLOAT)
FCALLSCSUB2(vp_upendn,VP_UPENDN,vp_upendn,FLOAT,FLOAT)
FCALLSCSUB0(vp_penup,VP_PENUP,vp_penup)
FCALLSCSUB3(vp_pline,VP_PLINE,vp_pline,FLOATV,FLOATV,INT)
FCALLSCSUB3(vp_upline,VP_UPLINE,vp_upline,FLOATV,FLOATV,INT)
FCALLSCSUB3(vp_plot,VP_PLOT,vp_plot,FLOAT,FLOAT,LOGICAL)
FCALLSCSUB3(vp_uplot,VP_UPLOT,vp_uplot,FLOAT,FLOAT,LOGICAL)
FCALLSCSUB2(vp_draw,VP_DRAW,vp_draw,FLOAT,FLOAT)
FCALLSCSUB2(vp_udraw,VP_UDRAW,vp_udraw,FLOAT,FLOAT)
FCALLSCSUB5(vp_pmark,VP_PMARK,vp_pmark,INT,INT,INT,FLOATV,FLOATV)
FCALLSCSUB0(vp_purge,VP_PURGE,vp_purge)
FCALLSCSUB2(vp_rascoltab,VP_RASCOLTAB,vp_rascoltab,INT,STRING)


#define vp_raster_STRV_A1 NUM_ELEM_ARG(5)
FCALLSCSUB10(vp_raster,VP_RASTER,vp_raster,STRINGV,LOGICAL,INT,INT,INT,FLOAT,FLOAT,FLOAT,FLOAT,INT)

#define vp_uraster_STRV_A1 NUM_ELEM_ARG(5)
FCALLSCSUB10(vp_uraster,VP_URASTER,vp_uraster,STRINGV,LOGICAL,INT,INT,INT,FLOAT,FLOAT,FLOAT,FLOAT,INT)

FCALLSCSUB2(vp_scale,VP_SCALE,vp_scale,FLOAT,FLOAT)
FCALLSCSUB4(vp_stretch,VP_STRETCH,vp_stretch,FLOAT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB1(vp_style,VP_STYLE,vp_style,INT)
FCALLSCSUB5(vp_text,VP_TEXT,vp_text,FLOAT,FLOAT,INT,INT,STRING)
FCALLSCSUB5(vp_utext,VP_UTEXT,vp_utext,FLOAT,FLOAT,INT,INT,STRING)
FCALLSCSUB3(vp_tfont,VP_TFONT,vp_tfont,INT,INT,INT)
FCALLSCSUB2(vp_tjust,VP_TJUST,vp_tjust,INT,INT)
FCALLSCSUB4(vp_clip,VP_CLIP,vp_clip,FLOAT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB4(vp_uclip,VP_UCLIP,vp_uclip,FLOAT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB2(vp_where,VP_WHERE,vp_where,FLOATV,FLOATV)
FCALLSCSUB1(vp_color,VP_COLOR,vp_color,INT)
FCALLSCSUB5(vp_arrow,VP_ARROW,vp_arrow,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB5(vp_uarrow,VP_UARROW,vp_uarrow,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB4(vp_dash,VP_DASH,vp_dash,FLOAT,FLOAT,FLOAT,FLOAT)
FCALLSCSUB3(vp_setdash,VP_SETDASH,vp_setdash,PFLOAT,PFLOAT,INT)
FCALLSCSUB1(vp_bgroup,VP_BGROUP,vp_bgroup,STRING)
FCALLSCSUB0(vp_break,VP_BREAK,vp_break)

/* 	$Id$	 */
