src = "axis coltab device gainpar genpen plot polygon stdplot vplot"

sources = map(lambda x: x+'.c',Split(src)) 
includes = map(lambda x: x+'.h',Split(src))

env = Environment(CCFLAGS='-std=gnu9x -Wall -pedantic -g',
                  CPPPATH='../../seis/rsf')

env.StaticLibrary('librsfplot',sources)
env.Command('rsfplot.h',includes,"cat $SOURCES > $TARGET")


