from rsfproj import *
from rwedemo import *
import zomig, pplot

par = {
    'nz':300,  'dz':0.010,    'oz':0,     # CC axis 1
    'nt':350,  'dt':0.005,    'ot':1.5,   # RC axis 1
    'nx':360,  'dx':0.020,    'ox':0,     # CC axis 2
    'ng':300,  'dg':0.020,    'og':0.2,     # RC axis 2
    'nT':1600, 'dT':0.004,    'oT':0,      'kT':800,    # time
    'tmx':10,'eps':0.0000001, 'verb':'y','nrmax':1,
    'ow':1, 'incore':'y',
    'spx':150
    }

# compute parameters
param(par)
# velocity
Flow('vv',None,
     '''
     spike
     n1=%(nz)d o1=%(oz)g d1=%(dz)g
     n2=%(nx)d o2=%(ox)g d2=%(dx)g |
     math output=2-0.05*x1-0.05*x2 |
     put label1=z label2=x
     ''' % par)
Flow('va',None,
     '''
     spike nsp=2 mag=-0.5,+1.5
     n1=%(nz)d o1=%(oz)g d1=%(dz)g k1=51,51 l1=100,100
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=51,201 l2=100,250 |
     smooth rect1=31 rect2=71
     ''' % par)

Flow('vb',None,
     '''
     spike nsp=1 mag=-1
     n1=%(nz)d o1=%(oz)g d1=%(dz)g k1=145 l1=155
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=130 l2=170 |
     smooth rect1=21 rect2=21 |
     scale axis=123
     ''' % par)

Flow('vel','vv vb',
     '''
     math
     a=${SOURCES[0]}
     b=${SOURCES[1]}
     output="a+b"
     ''')
Plot('vel',cgrey('allpos=y bias=0.7 pclip=100',par))

# smooth velocity for HWT
Flow('vsm','vv va',
     '''
     math
     v=${SOURCES[0]}
     a=${SOURCES[1]}
     output="v+a"
     ''')

# ------------------------------------------------------------
# wavefronts (by HWT)

Flow('mzs',None,'spike nsp=1 mag=0 n1=%(ng)d d1=%(dg)g o1=%(og)g | math output="0"'  % par)
Flow('mxs',None,'spike nsp=1 mag=0 n1=%(ng)d d1=%(dg)g o1=%(og)g | math output="x1"' % par)
Flow('mrs',None,'spike nsp=1 mag=0 n1=%(ng)d d1=%(dg)g o1=%(og)g | math output="1"'  % par)
Flow('sou','mxs mzs','cat axis=2 space=n ${SOURCES[1]} | transp | dd type=complex | window') 

Flow('hwt','vsm sou',
     '''
     hwtex verb=n sou=${SOURCES[1]}
     nt=%(nt)d ot=%(ot)g dt=%(dt)g
     ''' % par)
# coordinate system: rays(g,t)
Flow('cos','hwt','window min2=%(ot)g n2=%(nt)d' % par)

# coordinate system plot
cos('cos',5,10,par)
Result('cos','vel cos','Overlay')

# slowness
slow('sloCC','sloRC','vel','cos',par)
Result('sloRC','transp |'
       + rgrey('pclip=100 color=j allpos=y bias=0.5',par))

# ------------------------------------------------------------
# coordinate system coefficients (A,B,M=mask) and references (A,B)
abm('abmRC','abrRC','sloRC','cos',par)
abmplot('abmRC',par)

# ------------------------------------------------------------
# time data CC: (t,x)
Flow('datCC',None,
     '''
     spike nsp=1 mag=1
     n1=%(nT)d o1=%(oT)g d1=%(dT)g k1=%(kT)d
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=%(spx)d l2=%(spx)d |
     ricker1 frequency=10 |
     smooth rect2=1 |
     put label1=t label2=x
     ''' % par )
Result('datCC','grey pclip=100 wanttitle=n')

# ------------------------------------------------------------
# frequency data RC: (g,w)
frq('frqRC','frqCC','datCC','cos',par)

# ------------------------------------------------------------
# WEM image CC: (z,x)
zomig.image('imgCC','sloCC','frqCC',par)
Plot  ('imgCC','window | transp |' + cgrey('title=CC pclip=99',par))
Result('imgCC',['imgCC','cos'],'Overlay')

# ------------------------------------------------------------
# RWE image
mig('migCC','migRC','frqRC','abmRC','abrRC','cos',par)
mod('modCC','modRC','migRC','abmRC','abrRC','cos',par)
Result('icomp','imgCC migCC-SSF migCC-F45','Movie')

pplot.p3x2('iall','imgCC'    ,'migCC-SSF','migCC-PSC',
                  'migCC-F15','migCC-F45','migCC-F60',0.4,0.4,-8,-12)

End()
