from rsfproj import *

private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

# Get data from the server

off = 'OFFSET30.segy'
Fetch(off,'total',private)

# Convert to RSF

Flow('toff hoff off.asc off.bin',off,
     '''
     segyread tape=$SOURCE
     tfile=${TARGETS[1]} hfile=${TARGETS[2]} bfile=${TARGETS[3]} |
     put o1=1
     ''',stdin=0)

Flow('tbin mask','toff','intbin xk=cdp mask=${TARGETS[1]} | window j3=2')
Flow('mask2','mask','window j2=2')

Result('tbin',
       '''
       byte gainpanel=all |
       grey3 frame1=500 frame2=350 frame3=78
       title=Binned
       ''')

Result('mask2',
       '''
       put d1=1 o1=8100 d2=2 o2=9758 |
       dd type=float |
       grey allpos=y transp=n yreverse=n
       label1=CDP label2=Line title=Mask
       ''')

# Geometry

Flow('mx','hoff','dd type=float | headermath output="(sx+gx)/2000" ')
Flow('my','hoff','dd type=float | headermath output="(sy+gy)/2000" ')

Flow('xy','mx my',
     '''
     cat axis=1 ${SOURCES[1]} |
     dd type=complex
     ''')

Result('xy',
       '''
       graph symbol=. plotcol=6
       title=Geometry label1=mx label2=my
       ''')

az = -0.24 # azimuth

Flow('xy2','xy','math output="input*exp(I*(%g))" ' % az)

Result('xy2',
       '''
       graph symbol=. plotcol=6 transp=y
       title=Geometry label1=my label2=mx
       ''')

# Binning with geometry
Flow('geom','xy2','dd type=float')
Flow('tran','toff','transp memsize=500')

Flow('tbin2 tfld','tran geom',
     '''
     bin head=${SOURCES[1]} fold=${TARGETS[1]}
     interp=1 xkey=1 ykey=0
     ny=157 nx=702 dy=0.025 dx=0.0125 y0=2337.72 x0=8836.93 |
     transp memsize=500 plane=23 | transp memsize=500 
     ''')

Result('tbin2',
       '''
       byte gainpanel=78 |
       grey3 frame1=500 frame2=210 frame3=78
       title=Binned
       ''')

# Estimate dips

# Coarse binning

Flow('tbin0 tfld0','tran geom',
     '''
     bin head=${SOURCES[1]} fold=${TARGETS[1]}
     interp=2 xkey=1 ykey=0
     ny=40 nx=177 dy=0.1 dx=0.05 y0=2337.72 x0=8836.93 |
     transp memsize=500 plane=23 | transp memsize=500 
     ''')

Result('tbin0',
       '''
       byte gainpanel=20 |
       grey3 frame1=500 frame2=53 frame3=20
       title="Coarse Binning"
       ''')

Flow('miss0','tfld0','spray axis=1 n=1000 d=0.003 o=1')

Flow('dip0','tbin0 miss0',
     '''
     dip rect1=10 rect2=5 rect3=3
     mask=${SOURCES[1]}
     ''')

Result('idip0','dip0',
       '''
       window n4=1 |
       byte gainpanel=20 bar=idip |
       grey3 frame1=500 frame2=53 frame3=20
       title="Inline Dip" scalebar=y color=j
       ''')
Result('xdip0','dip0',
       '''
       window f4=1 |
       byte gainpanel=20 bar=idip |
       grey3 frame1=500 frame2=53 frame3=20
       title="Crossline Dip" scalebar=y color=j
       ''')

# Interpolate dips

Flow('dip01','dip0',
     '''
     transp memsize=500 |
     remap1 n1=352 d1=0.025 |
     transp memsize=500 |
     transp plane=13 memsize=500 |
     remap1 n1=79 d1=0.05 |
     transp plane=13 memsize=500 |
     scale dscale=0.5
     ''')

Flow('idip01','dip01','window n4=1')
Flow('xdip01','dip01','window f4=1')

# Medium binning

Flow('tbin1 tfld1','tran geom',
     '''
     bin head=${SOURCES[1]} fold=${TARGETS[1]}
     interp=2 xkey=1 ykey=0
     ny=79 nx=352 dy=0.05 dx=0.025 y0=2337.72 x0=8836.93 |
     transp memsize=500 plane=23 | transp memsize=500 
     ''')

Result('tbin1',
       '''
       byte gainpanel=39 |
       grey3 frame1=500 frame2=105 frame3=39
       title="Medium Binning"
       ''')

Flow('miss1','tfld1','spray axis=1 n=1000 d=0.003 o=1')

Flow('dip1','tbin1 miss1 idip01 xdip01',
     '''
     dip rect1=10 rect2=10 rect3=5
     mask=${SOURCES[1]} idip=${SOURCES[2]} xdip=${SOURCES[3]}
     ''')

Result('idip1','dip1',
       '''
       window n4=1 |
       byte gainpanel=39 bar=idip |
       grey3 frame1=500 frame2=105 frame3=39
       title="Inline Dip" scalebar=y color=j
       ''')
Result('xdip1','dip1',
       '''
       window f4=1 |
       byte gainpanel=39 bar=idip |
       grey3 frame1=500 frame2=105 frame3=39
       title="Crossline Dip" scalebar=y color=j
       ''')

# Interpolate dips

Flow('dip12','dip1',
     '''
     transp memsize=500 |
     remap1 n1=792 d1=0.0125 |
     transp memsize=500 |
     transp plane=13 |
     remap1 n1=157 d1=0.025 |
     transp plane=13 |
     scale dscale=0.5
     ''')

Flow('idip12','dip12','window n4=1 | patch w=1000,157,157')
Flow('xdip12','dip12','window f4=1 | patch w=1000,157,157')
Flow('miss','tfld','spray axis=1 n=1000 d=0.003 o=1 | patch w=1000,157,157')
Flow('pbin2','tbin2','patch w=1000,157,157')

Flow('dip2','pbin2 miss idip12 xdip12',
     '''
     dip rect1=10 rect2=20 rect3=10
     mask=${SOURCES[1]} idip=${SOURCES[2]} xdip=${SOURCES[3]}
     ''')

Flow('idip','dip2','window n4=1 squeeze=n | patch inv=y weight=y dim=3')
Flow('xdip','dip2','window f4=1 squeeze=n | patch inv=y weight=y dim=3')

Result('idip',
       '''
       byte gainpanel=78 bar=idip |
       grey3 frame1=500 frame2=210 frame3=78
       title="Inline Dip" scalebar=y color=j
       ''')
Result('xdip',
       '''
       byte gainpanel=78 bar=idip |
       grey3 frame1=500 frame2=210 frame3=78
       title="Crossline Dip" scalebar=y color=j
       ''')

End()
