from rsf.tex import *
import os, sys
os.environ['PSTEXPENOPTS']='color=y fat=3 fatmult=1.5 serifs=n'

End(lclass='geophysics',options='reproduce',color='ALL',hires='ALL',use='hyperref,listings,moreverb,amsmath,amsfonts')
