from rsfproj import *
import zomig

for case in ('vxz','_levset'):
    Fetch('elf%s.dat' % case,'masha')

nt=800
dt=0.004

nx=1000
dx=13.3333

nz=1000
dz=5.005

xmax = 13319.9667
zmax = 3200
zmax = 2000

## Flow('elfh','elfh.dat',
##      '''
##      echo in=$SOURCE
##      n1=%d o1=0 d1=%g
##      n2=%d o2=0 d2=%g
##      label1=Lateral unit1=m
##      label2=Time unit2=s
##      label="Dix Velocity" unit="km/s"
##      data_format=ascii_float |
##      dd form=native |
##      transp 
##      ''' % (nx,dx,nt,dt),stdin=0)  

Flow('elfvxz','elf_levset.dat',
     '''
     echo in=$SOURCE
     n1=%d o1=0 d1=%g
     n2=%d o2=0 d2=%g
     label1=Lateral unit1=m
     label2=Depth unit2=m
     label=Velocity unit="km/s"
     data_format=ascii_float |
     dd form=native |
     transp 
     ''' % (nx,dx,nz,dz),stdin=0)  

## Flow('melf','elfvxz',
##      '''
##      mask max=10 |
##      sfdd type=float |
##      smooth rect1=40 rect2=40 |
##      mask max=0.01
##      ''')

## Flow('vxz','elfvxz melf',
##      '''
##      miss3 mask=${SOURCES[1]} rect1=20 rect2=20 
##      ''')


Flow('vxz','elfvxz','window max1=%g' % zmax)

for coord in ('x','z'):
    dat = 'elf%s.dat' % coord
    Fetch(dat,'masha')
    Flow(coord,dat,
         '''
         echo in=$SOURCE
         n2=800 n1=1000
         data_format=ascii_float |
         dd form=native 
         ''',stdin=0)

for coord in ('x0','t0'):
    dat = 'good%s.dat' % coord
    Fetch(dat,'masha')
    Flow(coord,dat,
         '''
         echo in=$SOURCE
         n1=%d o1=0 d1=%g
         n2=%d o2=0 d2=%g
         label1=Lateral unit1=m
         label2=Depth unit2=m
         label=Velocity unit="km/s"
         data_format=ascii_float |
         dd form=native |
         transp 
         ''' % (nx,dx,nz,dz),stdin=0)

Flow('coord','t0 x0',
     'scale dscale=2 | cat axis=3 ${SOURCES[1]} | transp plane=23 | transp')
    
Fetch('elf-fmg.rsf','masha')
Flow('fmg','elf-fmg.rsf','dd form=native')
Flow('fmg2','fmg coord',
     'inttest2 interp=spline nw=4 coord=${SOURCES[1]}')

Plot('fmg2',
     '''
     window max1=%g | agc |
     grey title="Prestack Migration Time -> Depth"
     label1=Depth unit1=m label2=Lateral unit2=m
     ''' % zmax)

#       screenht=%g screenwd=%g labelsz=4 titlesz=4
#       ''' % (zmax,0.001*zmax,0.001*xmax))

## Result('elfh',
##        '''
##        grey color=j scalebar=y barreverse=y allpos=y bias=1400
##        title="Dix Velocity"
##        ''')

Plot('elfvxz','vxz',
     '''
     grey color=j scalebar=y allpos=y bias=1400
     wanttitle=y barlabel=Velocity barunit=km/s
     screenht=%g screenwd=%g bartype=v labelsz=4 titlesz=4
     title="Estimated Interval Velocity" barreverse=y
     ''' % (0.001*zmax,0.001*xmax))

Plot('rays','x z',
     '''
     cmplx ${SOURCES[:2]} | transp | window j2=10 |
     graph wanttitle=n yreverse=y min1=0 max1=%g min2=0 max2=%g
     plotcol=7 scalebar=y wantaxis=n
     screenht=%g screenwd=%g bartype=v  
     ''' % (xmax,zmax,0.001*zmax,0.001*xmax),stdin=0)

Result('elfvxz','elfvxz rays','Overlay')

Fetch('elf-stk2.rsf','masha')
Flow('stk','elf-stk2.rsf','dd form=native')

Result('elfstk','stk',
       '''
       grey title=Stack
       label1=Time unit1=s label2=Lateral unit2=m
       ''')

par = {
    'nx':nx,'ox':0,'dx':dx,
    'nt':nt,'ot':0,'dt':dt,
    'nz':351,'oz':0,'dz':dz,
    #
    'nw':201, 'ow':0, 'dw':0.625,'jw':1,
    #
    'verb':'y','eps':0.01,'nrmax':10
    }

Flow('slo','vxz',
     '''
     transp plane=12 |
     transp plane=23 |
     math "output=1/input" |
     put label1=x label2=y label3=z
     ''')

zomig.wflds ('dat','stk',par)
zomig.image('img','slo','dat',par)

Plot('img',
     '''
     window |
     transp | agc |
     grey title="Post-Stack Depth Migration"
     label1=Depth unit1=m label2=Lateral unit2=m
     ''')

Result('img','img','Overlay')
Result('fmg2','fmg2','Overlay')

#     screenht=%g screenwd=%g labelsz=4 titlesz=4
#       ''' % (0.001*zmax,0.001*xmax))


Result('elfimg','img fmg2','OverUnderAniso') 

End()
