from rsfproj import *

t0 = 0.6
v0 = 1500
nt = 1001

shifts = []
for case in 'pzxy':
    tag = string.upper(case)
    sgy = 'rec_gather_%s.sgy' % tag
    Fetch(sgy,'ninec')
    Flow([case,'./h'+case,'./b'+case,'t'+case],sgy,
         '''
         segyread tape=$SOURCE hfile=${TARGETS[1]}
         bfile=${TARGETS[2]} tfile=${TARGETS[3]} |
         put o3=0 label1=Time unit1=s label2=Offset unit2=m
         ''',stdin=0)

    offset = 'offset'+case
    Flow(offset,'t'+case,'dd type=float | headermath output=sy-gy')

    datum = 'datum'+case
    Flow(datum,offset,
         '''
         math output="sqrt(%g+input*input*%g)"
         ''' % (t0*t0,1./(v0*v0)))

    dat = 'dat'+case
    Flow(dat,[case,datum],'datstretch datum=${SOURCES[1]}')

    bin='bin'+case
    Flow(bin,[case,offset],
         '''
         transp |
         bin1 head=${SOURCES[1]} x0=-2500 nx=101 dx=50 interp=2 |
         transp
         ''')
    Result(bin,'grey title="%s Component" ' % tag)

    red='red'+case
    Flow(red,[dat,offset],
         '''
         transp |
         bin1 head=${SOURCES[1]} x0=-2500 nx=101 dx=50 interp=2 |
         transp
         ''')
    Result(red,'grey title="Reduced %s Component" ' % tag)

    if case != 'p':
        shifts.append(red)
        for s in range(1,11):
            shift = '%s-%d' % (case,s)
            Flow(shift,red,'window f1=%d | pad end1=%d' % (s,s))
            shifts.append(shift)
            
            shift = '%s+%d' % (case,s)
            Flow(shift,red,'window n1=%d | pad beg1=%d' % (nt-s,s))
            shifts.append(shift)

Flow('shifts',shifts,'cat ${SOURCES[1:%d]}' % len(shifts))

Flow('flt pre','shifts redp',
     'lpf match=${SOURCES[1]} pred=${TARGETS[1]} rect1=20 rect2=10')

Flow('fltz','flt','window n3=21')
Flow('redz2','shifts fltz','window n3=21 | add mode=p ${SOURCES[1]} | stack axis=3 norm=n')

Flow('fltx','flt','window f3=21')
Flow('redx2','shifts fltx','window f3=21 | add mode=p ${SOURCES[1]} | stack axis=3 norm=n')

Flow('pz','redp redz2','add scale=1,-1 ${SOURCES[1]}')
Result('pz','grey title="P+Z" ')

End()
