from rsfproj import *

grey = '''
grey labelrot=0 wheretitle=t wherexlabel=b
titlesz=18 crowd1=0.9 crowd2=0.9 wantaxis=n
'''

sfdip = 'dip niter=40 verb=y liter=100 rect1=3 rect2=3 '

title = {'2': '(b) No bounds',
         '+': '(c) Positive dip',
         '-': '(d) Negative dip'}

bound = {'2': '',
         '+': 'pmin=0',
         '-': 'pmax=0'}

for case in ('fabric','sfbay'):    
    Fetch(case+'.h','textures')
    Flow(case,case+'.h','dd form=native')

Flow('alias',None,
     'aliasp cycles=25 | window min1=200 max1=500 | put d1=0.004 o1=0.')

for case in ('fabric','sfbay','alias'):
    Plot(case,grey + ' title="(a) Input Data" ')

    dip = case+'-dip'
    
    Flow(dip+'2',case,sfdip)
    Flow(dip+'+',case,sfdip + ' pmin=0')
    Flow(dip+'-',case,sfdip + ' pmax=0')

    dips = []
    for sign in ('2','+','-'):
        dip1 = dip+sign
        dips.append(dip1)
        Flow(dip1,case,sfdip + bound[sign])
        Plot(dip1,grey + ' color=j clip=2 title="%s" ' % title[sign])

    Result(case,[case,]+dips,'SideBySideAniso')

End()
