###########################################################################
import sys, os, math

sys.path.append(os.path.join(os.environ.get('RSFROOT'),'lib'))

##########################################################################

from rsfproj import *
Book()

###########################################################################

for dip in [0,20,40,60]:
    model = 'dip%d' % dip
    Flow(model,None,
         '''
         spike n1=101 d1=0.04 |
         headermath output='1+T*%g' |
         unif2 n1=101 d1=0.05 v00=1,2
         ''' % math.tan(math.pi*dip/180.))
    Result(model,model,
           '''
           grey label1="Depth (km)" label2="Distance (km)"
           title="%d-degree Model"
           color=j allpos=y bias=1 screenratio=1.25
           ''' % dip)

############################################################################

End()
