from rsfproj import *

Flow('mat0',None,
     '''
     echo
     1 1 1 0
     1 2 0 0
     1 3 1 0
     1 4 0 1
     1 5 1 1
     in=$TARGET
     data_format=ascii_float
     n1=4
     n2=5
     ''')
Flow('mat','mat0','dd form=native')

Flow('y0',None,
     '''
     echo 3 3 5 7 9
     in=$TARGET
     data_format=ascii_float
     n1=5
     ''')
Flow('y','y0','dd form=native')

Flow('x0',None,'spike n1=4')

Flow('x','y mat0 x0',
     'conjgrad matmult mat=${SOURCES[1]} mod=${SOURCES[2]} niter=6')

End()
