import bldutil

Import('env bindir pkgdir')

scripts = '''
tkvpconvert vpannotate vplot2eps vplot2png vplot2gif vplot2avi vpconvert
'''

for src in Split(scripts):
    bldutil.py_install(src, env, pkgdir)
    env.Command(src,src+'.py','cp $SOURCE $TARGET')
    env.Install(bindir,src)
