import os, sys

try:
    import bldutil
    glob_build = True # scons command launched in RSFSRC
    srcroot = '../..' # cwd is RSFSRC/build/user/psava
    Import('env bindir libdir pkgdir')
except:
    glob_build = False # scons command launched in the local directory
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug() # Debugging flags for compilers
    bindir = libdir = pkgdir = None
    
targets = bldutil.UserSconsTargets()

# C mains
targets.c = '''
convolve2 ederiv2d ederiv3d ederiv3dfilters ewefd2 ewefd2dtti
ewefd3dtti stiff3d
'''

targets.build_all(env, glob_build, srcroot, bindir, libdir, pkgdir)
