from rsfproj import *

for case in ('ref','mod'):
    sgy = 'pluto1.5_%s.sgy' % case
    Fetch(sgy,'pluto')

    Flow([case,case+'.asc',case+'.bin'],sgy,
         '''
         segyread tape=$SOURCE read=d
         hfile=${TARGETS[1]} bfile=${TARGETS[2]} |
         cut n1=50
         ''',stdin=0)

Flow('mod2','mod','window f1=100 | pad end1=100')

def grey(title):
    return '''
    grey title="%s" label1=Time unit1=s label2=Trace
    ''' % title

Result('ref',grey('Reference'))
Result('mod',grey('Model'))

screen = ' wanttitle=n screenht=7.68 screenratio=0.5625 labelsz=5'

Result('ref2','ref','window max1=6 | ' + grey('') + screen)

nt = 1126

shifts = ['mod']
for s in range(1,11):
    shift = 'shift-%d' % s
    Flow(shift,'mod','window f1=%d | pad end1=%d' % (s,s))
    shifts.append(shift)

    shift = 'shift+%d' % s
    Flow(shift,'mod','window n1=%d | pad beg1=%d' % (nt-s,s))
    shifts.append(shift)
Flow('shifts',shifts,'cat ${SOURCES[1:%d]}' % len(shifts))

Flow('flt pre','shifts ref',
     'lpf match=${SOURCES[1]} pred=${TARGETS[1]} rect1=20 rect2=10 niter=400')
Flow('sig','ref pre','add scale=1,-1 ${SOURCES[1]}')

Result('pre',grey('Matched Multiples'))
Result('sig',grey('Estimated Signal'))

Result('sig2','sig','window max1=6 | ' + grey('') + screen)

Result('zero','flt','window n3=1 f3=10 | %s color=j' % grey('Zero Coefficient'))
Result('csum','flt','stack axis=3 norm=n | %s color=j' % grey('Coefficient Sum'))

End()
