from rsf.proj import *

# download well-log data
Fetch('L-30.las','1406_Make_a_synthetic',
      server='https://raw.githubusercontent.com',
      top='seg/tutorials/master')

# Convert to RSF
Flow('L-30','L-30.las','las2rsf $SOURCE $TARGET',stdin=0,stdout=-1)

# Examine with "< L-30.rsf sfheaderattr segy=n desc=y"

# Mask bad values
Flow('mask1','L-30','headermath segy=n output=RHOB | mask min=0')
Flow('mask2','L-30','headermath segy=n output=DT   | mask min=0')
Flow('mask','mask1 mask2','mul ${SOURCES[1]}')

scale = dict(RHOB=1000,DT=3.28084,DEPT=1/3.28084) # convert to SI units
threshold = dict(RHOB=100,DT=10)

for case in ('DT','RHOB','DEPT'):
     # Extract values
     Flow(case,'L-30 mask',
          '''
          headermath segy=n output=%s | 
          headerwindow mask=${SOURCES[1]} | window |
          scale dscale=%g | 
          put o1=3058.5 d1=0.5 label1=Depth unit1=ft
          ''' % (case,scale[case]))

     # Clip spikes
     if case != 'DEPT':
          despike = case+'-despike'
          Flow(despike,case,'despike wide=13')
          
          spikemask = case+'-spikemask'
          Flow(spikemask,[despike,case],
               '''
               math orig=${SOURCES[1]} output="abs(input-orig)" |
               mask min=%g
               ''' % threshold[case])

          Flow(despike+'2',[spikemask,despike,case],
               '''
               dd type=float |
               math orig=${SOURCES[2]} filt=${SOURCES[1]}
               output="input*filt+(1-input)*orig"
               ''')
          Result(case,[case,despike+'2'],
                 '''
                 cat axis=2 ${SOURCES[1]} |
                 graph title=%s
                 ''' % case)

# Compute time-to-depth relationship

log_start_time = 0.410553230106 # (s)

Flow('tdr','DT-despike','causint | math output="%g+(%g)*input" ' % (log_start_time,2*0.1524/1e6))

Result('tdr','graph title=Time yreverse=y transp=y')

# Compute acoustic impedance

Flow('z','RHOB slowness','math rho=${SOURCES[0]} slow=${SOURCES[1]} output="1e6*rho/slow" ')

# Compute reflection coefficient series

Flow('rc','z','ai2refl')

# Plots

Flow('dz','DEPT','igrad')
Flow('slowness','DT-despike dz','div ${SOURCES[1]} | clip2 lower=1000')

Plot('slowness','DEPT slowness',
     '''
     cmplx ${SOURCES[1]} | window n1=21692 |
     graph transp=y yreverse=y min1=500 max1=4500 grid=y plotfat=3
     title=function unit1=m label2="P-wave slowness" unit2="\F10 m\F3 m/s" labelsz=12 titlesz=15
     ''')

Plot('twt','DEPT tdr',
     '''
     cmplx ${SOURCES[1]} | window n1=21692 |
     graph transp=y yreverse=y min1=500 max1=4500 grid=y plotfat=3
     title=integral unit1=m label2="two-way time" unit2="s" labelsz=12 titlesz=15
     ''')

Plot('impedance','DEPT z',
     '''
     cmplx ${SOURCES[1]} | window n1=21692 |
     graph transp=y yreverse=y min1=500 max1=4500 grid=y plotfat=3
     title=impedance unit1=m label2= unit2="kg/(m\^2\_s)" labelsz=12 titlesz=15
     ''')

Plot('reflectivity','DEPT rc',
     '''
     cmplx ${SOURCES[1]} | window n1=21692 |
     graph transp=y yreverse=y min1=500 max1=4500 grid=y plotfat=3
     title=reflectivity unit1=m label2= unit2= labelsz=12 titlesz=15
     ''')

Result('four','slowness twt impedance reflectivity','SideBySideAniso')

# add labels for well tops

End()
