from rsf.proj import *
from rsf.recipes.beg import server

Fetch('kjnmo.HH','kjar',server)
Flow('kjnmo','kjnmo.HH','dd form=native')

# comment this out on CD-ROM to escape SDA dependence.
#${CDDATA}/kjnmo.H archive: ${DAVID}  Bigcable.x
#	< ${DAVID} Window min1=2.0 | Bigcable.x | Window f3=50 n3=375 | Nmo v=2.05|Window max1=2.6| Tpow tpow=2 > ${CDDATA}/kjnmo.H out=${CDDATA}/kjnmo.F

Flow('kjamp','kjnmo',
     'mul $SOURCE | stack axis=1 norm=n | math output="sqrt(input)" ')

Result('kjamp',
       'grey pclip=100 crowd1=.84 crowd2=.80 title="Amp(raw)" allpos=y')

Flow('log0','kjamp',
     '''
     math output="log(abs(input)+1.e-35)/log(10)" 
     ''')

# subtract average
Flow('slog0','log0',
     '''
     stack axis=2 | stack axis=1 |
     spray axis=1 n=48  d=0.05  o=-2.591 |
     spray axis=2 n=375 d=0.025 o=1.25 |
     add scale=-1,1 $SOURCE
     ''')

Plot('slog0',
     '''
     grey crowd1=.84 crowd2=.80 title="Amp(raw)"
     ''')

Flow('myk0','slog0','xtomo niter=10')

Plot('myk0',
     '''
     grey crowd1=.84 crowd2=.80 title="Tomo(amp)"
     ''')

Result('kartom0','slog0 myk0','OverUnderAniso')

End()
