from rsf.proj import *
from rsf.recipes.beg import server

for case in ('ai','vp1'):
    Fetch(case+'.HH','cretaceous',server)
    Flow(case,case+'.HH','dd form=native')

    Result(case,'byte gainpanel=all mean=y | grey3 color=j frame1=100 frame2=100 frame3=500 title=%s' % case.upper())

End()
