from rsftex import *

mainfile = 'manual'

Paper(mainfile,lclass='book',options='11pt,a4paper',
      use=['amssymb,amsmath,dsfont,desclist,geometry,url,makeidx',          
           '[dvips, bookmarks, hyperindex=true, colorlinks=false, linktocpage=true]hyperref'],
      include='\makeindex\setcounter{tocdepth}{1}')

#      include=r'\makeindex\setcounter{tocdepth}{1}')
#      include=r'\makeindex')

