/* This file is automatically generated. DO NOT EDIT! */

#ifndef _trackserv_h
#define _trackserv_h


#if defined(__APPLE__)&& defined(__MACH__)
#include <GLUT/glut.h>
#else
#include <GL/glut.h>
#endif


#include "trackball.h"


typedef struct _RSFTrackballData RSFTrackballData;


struct _RSFTrackballData {
    float     begin_x, begin_y;  /* position of mouse */
    float     zoom;
    float     dx, dy;
    float     quat[4]; /* orientation of object */
    float     dquat[4];
    GLdouble  shift_wx, shift_wy;
    GLdouble  last_wx, last_wy;
    GLfloat   near_plane, far_plane;
    GLfloat   translate;
    GLfloat   world_width, world_height;
    GLint     screen_width, screen_height;
    GLfloat   m[4][4]; /* Rotation matrix */
    void(*motion_callback)(RSFTrackballData*, int, int);
    int       redraw; /* if 1 - needs redraw after motion_callback); */
    int       reshape; /* if 1 - needs reshape after mouse_callback); */
};


void rsf_trackball_mouse_event (RSFTrackballData *data, int button, int state, int x, int y);
/*< event >*/


void rsf_trackball_init (RSFTrackballData *data);
/*< initialize >*/

#endif
