#!/bin/csh
#$ -N rtm 
#$ -pe 1way 600 
#$ -q normal
#$ -o rtm.o$JOB_ID
#$ -l h_rt=24:00:00
#$ -V
#$ -cwd
#   <------ You MUST Specify a Project String ----->
#$ -A TCCS 


setenv OMP_NUM_THREADS 12 

ibrun tacc_affinity $RSFROOT/bin/sfffdrtm  source=source.rsf vel=vel22.rsf dt=0.001 nt=12057 sht=56  isz=1 nbt=119 nbb=120 nbl=142 nbr=141 ct=0.002 cb=0.002 cl=0.002 cr=0.002 geo=geo.rsf irz=1  nr=348 err=0.000001 factor=1.0 ax=2 az=2 jm=15 sht=56 tskip=2200 
