from rsf.proj import *

###############################################################################
data='../SEGY/shots.rsf'
SConscript('../SEGY/SConstruct')

# Passband filter the data
Flow('shot0',data,
     '''
     bandpass flo=20 fhi=180 
     | pow pow1=2
     ''', split=[3,4791])

Flow('band_mpi',data,
     'bandpass flo=20 fhi=180', 
     split=[3,'mpi'],np=5)
Flow('shot_mpi','band_mpi',
     'pow pow1=2',
     split=[3,'mpi'],np=5)

Flow('shot_omp',data,
     '''
     bandpass flo=20 fhi=180 
     | pow pow1=2
     ''',split=[3,'omp'])

##################
# common offset
##################
Flow('near_offset','shot0','window n2=1')
Plot('near_offset','grey title="Near Offset section"')

Flow('far_offset','shot0','window n2=1 f2=119')

###############################
# Pick Sea Floor for near offset
################################
Flow('window','near_offset','window min1=.01 max1=1.7')

Flow('pick','near_offset',
     '''
     window min1=.01 max1=1.7 
     | envelope | transp| pick smooth=n vel0=1.57
     ''')

Plot('window','grey')

Plot('pick','graph yreverse=y min2=.01 max2=1.7 pad=n wanttitle=n wantaxis=n')

Plot('pick0','pick','graph yreverse=y min2=0 max2=3 pad=n wanttitle=n wantaxis=n')

# sea floor overlayed over the windowed time samples
Result('sf','window pick','Overlay')

# sea floor overlayed over the near offset section
Result('sfbig','near_offset pick0','Overlay')

#################################
# create mute for above sea floor
#################################
ns=4791
Flow('mute','pick',
     '''
     spray axis=1 n=120 d=12.5 o=29.25 label=Offset unit=m
     | spray axis=1 n=3000  d=.001 o=0 label=time unit=s
     | math output="input-x1-.03"
     | mask max=0
     | dd type=float
     | smooth rect1=7 rect2=5
     | nmostretch inv=y half=n v0=1500
     ''')
#     ''',split=[1,'omp'],reduce="cat axis=3",np=10)
#     ''',split=[1,ns],reduce="cat axis=3")

mute='mute'
# apply mute above sea floor
############################
Flow('shot', [data, mute],
     '''
     bandpass flo=20 fhi=180
     | mul ${SOURCES[1]}
     ''')
End()

