from rsf.proj import *
from rsf.gallery import constant

constant.get_zodata('data')
Result('data','grey title="Zero Offset" ')

nx = 351

Flow('fft','data','cosft sign2=1')

Flow('stolt','fft','stolt vel=1',split=[2,'omp'])

Flow('mig','stolt','cosft sign2=-1')

constant.zo_image('mig')

# Impulse response

constant.get_impulse('imp','data')

Flow('ifft','imp','cosft sign2=1')

Flow('istolt','ifft','stolt vel=1',split=[2,'omp'])

Flow('imig','istolt','cosft sign2=-1')

constant.impulse_response('imig')

End()
