from rsf.proj import *

# Download data
Fetch('apr18.h','seab')
Flow('data','apr18.h','dd form=native')

# Bin to regular grid
Flow('bin','data',
     '''
     window n1=1 f1=2 | math output='(2978-input)/387' |
     bin head=$SOURCE niter=150 nx=160 ny=160 xkey=0 ykey=1
     ''')

Result('init','bin','grey transp=n yreverse=n label1=longitude label2=latitude wanttitle=n')

Flow('pef lag','bin','hpef lag=${TARGETS[1]} a=5,3 niter=50')
Flow('interp','bin pef','miss filt=${SOURCES[1]} niter=100')

Result('pef','interp','grey transp=n yreverse=n label1=longitude label2=latitude wanttitle=n')

End()
