from rsf.proj import *

Flow('qdome',None,'qdome n1=200 d1=.008')

Flow('lomx lagx','qdome',
     'lopef a=7,2,1 w=20,5,3 center=3,0,0 lag=${TARGETS[1]}')
Flow('lomy lagy','qdome',
     'lopef a=7,1,2 w=20,5,3 center=3,0,0 lag=${TARGETS[1]}')

for case in ('x','y'):
    decon = 'qdome'+case
    Flow(decon,['qdome','lom'+case],'decon filt=${SOURCES[1]}')

Flow('qdomer','qdomex qdomey',
     '''
     math rx=${SOURCES[0]} ry=${SOURCES[1]}
     output="sqrt(rx*rx+ry*ry)"
     ''')

for case in ('','x','y'):
    Flow('qdome'+case+'B','qdome'+case,'byte gainpanel=all')
Flow('qdomerB','qdomer','byte gainpanel=all allpos=y')

Flow('all','qdomeB qdomexB qdomeyB','merge axis=2 ${SOURCES[1:3]}')
Result('qdomesico','all','window f3=24 n3=1 | grey title=LOMOPLAN')
Result('qdometoco','all','window f1=60 n1=1 | grey title=LOMOPLAN transp=n')
Result('qdometora','qdomeB qdomerB',
       '''
       merge axis=2 ${SOURCES[1]} |
       window f1=60 n1=1 |
       grey title=LOMOPLAN transp=n
       ''')

End()
