# reverse-time migration of sigsbee2a dataset
# cartesian and nonorthogonal tau coordinate

from rsf.proj import *
import tau

# ================================ #
# parameters                       #
# ================================ #

pseudo  = True
forward = True
backward= True

num_nodes = 256
num_procs = 244

shot0 = 256
jshot = 1
nshot = num_procs

# ================================ #
# preprocessing                    #
# ================================ #

tau.get_velo('velo')
tau.get_sour('sour')

tau.grey_velo('velo')
tau.graph_sour('sour')

if pseudo:
    tau.get_vmap('vmap','velo')
    tau.get_tau('tau','vmap')
    tau.get_sigm('sigm','tau')
    tau.mapping('Velo','velo','tau',inv=False)
    tau.mapping('VElo','Velo','tau',inv=True)
    tau.mapping('Sigm','sigm','tau',inv=False)
    tau.mapping('Vmap','vmap','tau',inv=False)

    tau.grey_velo('vmap')
    tau.cont_tau('tau','velo')
    tau.grey_sigm2('sigm','Sigm')
    tau.grey_velo4('velo','Velo','VElo')
        
tau.set_shot(shot0,nshot,jshot)
tau.get_dataset('dataset')
tau.get_data('data','dataset')
# tau.grey_data('data') # long time

if pseudo:
    tau.plot_survey('Velo')
else:
    tau.plot_survey('velo')

# ================================ #
# job scripts                      #
# ================================ #

if pseudo:
    tau.set_job('sigsbeeT_256_499')
else:
    tau.set_job('sigsbeeC_256_499')

files = ['sour']
if pseudo:
    files.extend(['Velo','Vmap','Sigm']) # 'data'
	# avoid reproducing large data.bin 
else:
    files.extend(['velo','data']) 
# tau.swapbyte(files)

tau.make_par(forward,backward,pseudo)
tau.make_job(num_procs,num_nodes,pseudo)

Flow('isomig','velo sour',
     '''
     mpirtmiso tau=1
     nz=751 z0=0 dz=0.0067 zs=0.00508 zr=0.00508
     eps=1 mode=0
     nx=3201 x0=0 dx=7.62
     nt=37501 dt=0.00032
     j3=15
     bzl=40 bzh=40 bxl=40 bxh=40
     czl=4e-05 czh=2e-05 cxl=2e-05 cxh=2e-05
     ns=244 s0=11986.3 ds=45.72
     nh=348 h0=0       dh=22.86
     nH=64 dH=1
     nC=3  dC=800 C0=800
     velo=${SOURCES[0]} sour=${SOURCES[1]}
     ''',stdin=0,stdout=-1)

End()

###      wall time   forward   backward  total   ###
# sigsbeeT_000_255 : ??        ??        13h09min  #
# sigsbeeC_000_255 : ??        ??        18h37min  #



