from rsf.book import *

report = (('Optimization','cdstep stack forwd spitz oc2 pwd bspl'),
          ('Helix Transform','precon findif burg specfac plane steer lines texture helft'),
          ('Imaging','fat stoltst antial angle'),
          ('Traveltimes','waverays lineiko huygens fmeiko fmsec'),
          ('Azimuth Moveout','oc1 norm fkamo'),
          ('Velocities','vc1 velspec vc2 banana fractal'),
          ('AVO \& Elasticity','avo'))

Papers(authors={'precon':'Sergey Fomel and Jon Claerbout',
                'norm': 'Sergey Fomel and Norman Bleistein',
                'rwe':'Paul Sava and Sergey Fomel',
                'stoltst':'Sergey Fomel and Louis Vaillant',
                'burg':'''Sergey Fomel and Paul Sava and James Rickett and Jon F. Claerbout'''},
       copyr='Stanford University',
       group='Stanford Exploration Project',
       line='Selected papers',
       papers=report)

End(use='hyperref,listings,amsmath',
    include=r'''
    \newcommand{\RSF}{../../..}
    \newlength{\boxwidth}
    \setlength{\boxwidth}{\textwidth}
    \addtolength{\boxwidth}{-20pt} 
    \setlength{\fboxsep}{10pt}
    \newcommand{\boxit}[1]{\noindent\fbox{\parbox{\boxwidth}{#1}}}
    ''')
