#!/bin/bash
#SBATCH -J mpifwi       	# Job name
#SBATCH -o mpifwi.%j.out   	# Name of stdout output file(%j expands to jobId)
#SBATCH -e mpifwi.%j.err   	# Name of stderr output file(%j expands to jobId)
#SBATCH -p normal           	# Submit to the 'normal' or 'development' queue
#SBATCH -N 2                	# Total number of nodes requested (16 cores/node)
#SBATCH -n 32                	# Total number of mpi tasks requested=? mpirank
#SBATCH -t 00:20:00         	# Run time (hh:mm:ss) - 1.5 hours
#SBATCH -A Madagascar-workshop  # Allocation name to charge job against

export OMP_NUM_THREADS=8

# Run the mpi application
scons NP=2
