const char * sdoc[] = {
"Driver for Basic Acoustic Least-Squares Waveform Inversion ",
"driven by IWAVE Acoustic Wave Equation Simulator",
"  ",
"Authors: William W. Symes and Dong Sun", 
" ",
"2009-11",
" ",
"Usage: ",
"   ",
"   \"asginv.x par=[name of parameter file]\"",
"   ",
"Command name (asginv.x) is a standin for any valid form of invocation,",
"including mpirun or mpiexec, with appropriate path information. ",
" ",
"User Notes (08/11): ",
"  <i>   currently only 2 dimensional case is available",
"  <ii>  this driver doesn't adopt any regularization. (asginv_regs.cc",
"        demonstrates how to adopt given or user-defined regularization",
"        in ls-inversion);",
"  <iii> for the time being, all computations involving Born simulation",
"        and its adjoint action could only use staggered grid finite difference",
"        scheme of order 2 in time and 4 in space, derived from pressure-velocity",
"        form of acoustodynamics. Either pressure-free (reflecting) or absorbing",
"        (PML) boundary condition on each boundary face of simulation hypercube",
"  ",
"************************************************************************* ",
"***                          PARAMETER TABLE                          *** ",
"************************************************************************* ",
"  ",
"[NOTE: if no value is given, then user must supply a value; otherwise,",
" given value serves as default, with exception of bound files - see note",
" below]",
"   ",
"------------------------------------------------------------------------",
"Model Info:",
"   init_bulkmod = ",
"                  [string] - existing RSF header file for initial bulkmodulus, ",
"                  also defines grid for pressure (and, indirectly, all other ",
"                  spatial grids)",
"  init_buoyancy = ",
"                  [string] - existing RSF header file for initial buoyancy, ",
"        bulkmod = ",
"                  [string] - RSF header file for estimated bulkmodulus, ",
"       buoyancy = ",
"                  [string] - RSF header file for estimated buoyancy 1/rho, ",
"   grad_bulkmod = ",
"                  [string] - RSF header file for bulkmodulus gradient ",
"                  component",
"  grad_buoyancy = ",
"                  [string] - RSF header file for buoyancy gradient ",
"                  component",
"     ub_bulkmod = ",
"                  [string] - RSF header file for upper bound bulkmodulus      ",
"     lb_bulkmod = ",
"                  [string] - RSF header file for lower bound bulkmodulus      ",
"    ub_buoyancy = ",
"                  [string] - RSF header file for upper bound buoyancy      ",
"    lb_buoyancy = ",
"                  [string] - RSF header file for lower bound buoyancy      ",
"[NOTE: if bound files not given (lines removed from table or quoted), then",
" const bound vectors defined from values of max, min of velocity and density;", 
" these may be provided here (see below) or use defaults inherited from IWAVE] ",
" ",
"------------------------------------------------------------------------",
"Trace Info:",
"       datafile = ",
"                  [string] - existing target SU (SEGY) trace - headers",
"                  define acquisition geometry. Required headers: ns, dt,",
"                  delrt, gx, gy, gelev, sx, sy, selev",
" final_datafile = ",
"                  [string] - predicted data from estimated model",
"     mute_slope = 0.0",
"                  [float] mute slope (ms/m)",
"    mute_zotime = 0.0",
"                  [float] mute zero-offset time (ms)",
"     mute_width = 0.0",
"                  [float] width of mute zone (ms)",
" [NOTE: linear mute is applied to predicted and observed data in formation of ",
"  mean square error function]",
" ",
"------------------------------------------------------------------------",
"Source Info,",
"         source = ",
"                  [string] name of source SU file",
"        srctype = ",
"                  [string] - valid types are point or array",
"        sampord = 0",
"                  [int] - spatial interpolation order for sampling (traces)",
"                  and adjoint sampling (source),",
"                  either 0 (greatest-integer sampling) or 1 (multilinear sampling)",
"   ",
"------------------------------------------------------------------------",
"UMin Info",
"        uminpar = uminpar.dat",
"                  [string] - name of umin parameter file",
" ",
"------------------------------------------------------------------------",
"Checkpoint Info [passed to IWaveOp]",
"         nsnaps = 3",
"                  [int] - number of buffers (simultaneously stored checkpoints)",
"   maxbuffernum = 0",
"                  [int] - maximum number of in-core buffers - when nsnaps > ",
"                  maxbuffernum, disk files will be used to store some checkpoints",
"       ",
"------------------------------------------------------------------------",
"FD Info [passed to IWAVE]",
"          order = 1         ",
"                  [int] half-order of spatial differentiator",
"           cmax = CMAX_DEF",
"                  [float] maximum permitted velocity (m/ms)",
"           cmin = CMIN_DEF",
"                  [float] minimum permitted velocity (m/ms)",
"           dmax = DMAX_DEF",
"                  [float] maximum permitted density (kg/m^3)",
"           dmin = DMIN_DEF",
"                  [float] minimum permitted density (kg/m^3)",
"            cfl = CFL_DEF",
"                  [float] relative CFL number, fraction of max stable step",
"       ",
"[NOTE: defaults for velocity, density, cfl defined in IWAVE (asg/include/defaults.h)]",
"       ",
"------------------------------------------------------------------------",
"PML Info [passed to IWAVE]",
"         ",
"         fpeak = FPEAK_DEF",
"                 [float] nominal central frequency for",
"                 wavefield, used only to calibrate thickness of PML layers. ",
"     npml_ampl = 10.3616",
"                 [float] - damping factor in absorbing layers",
"           nl1 = 0.0",
"                 [float] - thickness (in wavelengths at fpeak and cmax) of left",
"                 absorbing layer for axis 1",
"           nr1 = 0.0",
"                 [float] - thickness (in wavelengths at fpeak and cmax) of right",
"                 absorbing layer for axis 1",
"           nl2 = 0.0",
"                 [float] - thickness (in wavelengths at fpeak and cmax) of left",
"                 absorbing layer for axis 2",
"           nr2 = 0.0",
"                 [float] - thickness (in wavelengths at fpeak and cmax) of right",
"                 absorbing layer for axis 2",
"           nl3 = 0.0",
"                 [float] - thickness (in wavelengths at fpeak and cmax) of left",
"                 absorbing layer for axis 3",
"           nr3 = 0.0",
"                 [float] - thickness (in wavelengths at fpeak and cmax) of right",
"                 absorbing layer for axis 3",
"     ",
"------------------------------------------------------------------------",
"MPI Info [passed to IWAVE]",
"       mpi_np1 = 1",
"                 [int] - number of domains along axis 1    ",
"       mpi_np2 = 1",
"                 [int] - number of domains along axis 2    ",
"       mpi_np3 = 1",
"                 [int] - number of domains along axis 3    ",
"       partask = 0",
"                 [int] - when set, load as many simulations as possible given",
"                 size of MPI_COMM_WORLD; when unset, one simulation at a time",
"     ",
"------------------------------------------------------------------------",
"Dump Info [passed to IWAVE]",
"       dump_pi = 0",
"                 [int] - dump parallel/dom decomp info",
"      dump_lda = 0",
"                 [int] - dump grid data for allocated arrays, including ",
"                 ghost cell zones",
"      dump_ldc = 0",
"                 [int] - dump grid data for arrays updated in this process, ",
"                 not including ghost cells",
"      dump_lds = 0",
"                 [int] - dump grid data for send arrays",
"      dump_ldr = 0,",
"                 [int] - dump grid data for receive arrays",
"     dump_term = 0",
"                 [int] - dump trace sampling data",
"     printact  = 0",
"                 [int] - timestep action output: 0 - no output, ",
"                 1 - timestep number, 2 - detailed actions within timestep.",
  NULL };
