const char * sdoc[] = {
" Driver for Least-Squares Waveform Inversion driven by IWAVE Acoustic Wave Equation Simulator, Version ?",
"  ",
"  ",
" Purpose: Solve the acoustic waveform inversion in 1, 2 or 3 spatial dimensions (currently only 2 dimensional case is available), output predicted model, predicted data, initial and final gradient, inversion history, etc. ",
" ",
" Authors: William W. Symes and Dong Sun", 
" ",
" May 2011",
" ",
" Usage: ",
"   ",
"   asginv.x par=[name of parameter file]",
"   ",
" Command name (asginv.x) is a standin for any valid form of invocation,",
" including mpirun or mpiexec, with appropriate path information. ",
" ",
" User Notes: ",
"  <i> this driver doesn't adopt any regularization. (asginv_regs.cc demenstrates how to adopt given or user-defined regularization in ls-inversion);",
"  <ii> for the time being, all computations involving Born simulation and its adjoint action could only use staggered grid finite difference scheme of order 2 in time and 4 in space, derived from pressure-velocity form of acoustodynamics. Either pressure-free (reflecting) or absorbing (PML) boundary condition on each boundary face of simulation hypercube;",
"  <iii> for the time being, only constant density case is fully functional. Extra scaling operator is needed for full acoustic inversion.",
" ",
" ",
"   Parameter Table ",
"   ",
"   Required parameter ",
"     datafile = [string] - name of (existing) target SU (SEGY) trace - headers",
"                define acquisition geometry. Required headers: ns, dt,",
"                delrt, gx, gy, gelev, sx, sy, selev",
"   ",
"     ",
"       bulkmod = [string] - RSF header file for true material bulkmodulus, ",
"           also defines computational grid for pressure",
"       buoyancy  = [string] - RSF header file for true material buoyancy 1/rho, ",
"   init_bulkmod = [string] - RSF header file for initial bulkmodulus, ",
"   init_buoyancy = [string] - RSF header file for initial buoyancy, ",
" uminpar = [string] - optimization par file",
" ",
"  Checkpoint Info ",
" ",
"     nsnaps = [int]   - number of snaps in checkpointing computation,",
" ",
"     maxbuffernum = [int]  - maximum number of state-buffers alowed in checkpointing computation -",
"       when nsnaps > maxbuffernum, disk files will be used to store some of the checkpoints,",
"    ",
"   Optional parameters ",
"     ",
"     direct_datafile =  [string] - name of (existing) SU (SEGY) trace containing direct-waves ",
"  ",
"     Model Info",
"     ",
"        extended_mod = [int] - 0, standard model; 1, extended model,",
"     Background material parameters (based on which window op and direct-waves are computed; default value: init_bulkmod/init_buoyancy),",
" ",
"   bg_bulkmod = [string] - RSF header file for background bulkmodulus ",
"   bg_buoyancy = [string] - RSF header file for background buoyancy, ",
"  Model Bound Info ",
" ",
"     ub_bulkmod_val = [int] - upper bound for bulkmodulus      ",
"     lb_bulkmod_val = [int] - lower bound for bulkmodulus      ",
"     ub_buoyancy_val = [int] - upper bound for bulkmodulus      ",
"     ub_buoyancy_val = [int] - lower bound for bulkmodulus      ",
"        ",
"   Output Flags ",
"     dump_model_history = [int] - 0, no output; 1, output final model, ",
"     dump_data_history = [int]  - 0, no output; 1, output final data ",
"     dump_grad_history = [int] - 0, no output; 1, output initial and final gradient, ",
" ",
"     final_bulkmod = [string] - RSF header file for final bulkmodulus, ",
"     final_data = [string] - SU file for final predicted data,",
"   ",
"     Source Information,",
"       ",
"       source    = [string] name of source SU file",
" ",
"       srctype   = point or array - source type (if choose array, one must provide source SU file) ",
"     ",
"     Spatial interpolation order for sampling (traces) and adjoint sampling (source),",
"     either 0 (greatest-integer sampling) or 1 (multilinear sampling)",
"       ",
"     sampord   = [int] [Default = 0].",
"       ",
"     Finite difference scheme ",
"                   ",
"       cmax = [float] [Default=5 m/ms] maximum permitted velocity",
"       ",
"       cmin = [float] [Default=0.2*cmax] minimum permitted velocity",
"       ",
"       cfl = [float] CFL number [Default=0.4]",
"       ",
"       scheme_phys, scheme_npml = 24 ",
"       [Note: at this tim, 24 is the only available scheme for inversion] - time and space orders for physical, PML domains.",
"       ",
"       ",
"       PML Info ",
"         ",
"         fpeak = [float] [Default=0.01KHz] nominal central frequency for",
"         wavefield, used only to calibrate thickness of PML layers. As with",
"         ",
"         npml_ampl = [float], [Default = 10.3616], - damping factor in",
"         absorbing layers",
"         ",
"         nl1,nr1 = [float], [float] [Defaults = 0.0, 0.0], for axis 1;",
"         nl2,nr2 = [float], [float] [Defaults = 0.0, 0.0], for axis 2;",
"         nl3,nr3 = [float], [float] [Defaults = 0.0, 0.0], for axis 3 - ",
"         Thicknesses of left and right absorbing layers along each axis, in",
"         wavelengths at nominal peak frequency (fpeak) and maximum velocity",
"       ",
"     ",
"     Domain decomposition via MPI [See Notes on Modeling with IWAVE, below]:",
"       ",
"        mpi_np1   = [int] [Default = 1],",
"        mpi_np2   = [int] [Default = 1],",
"        mpi_np3   = [int] [Default = 1].-",
"        Numbers of domains along each axis.    ",
  " ",
"     ",
"     Threaded parallelism via OpenMP:",
"       ",
"       omp_nt    = [int] [Default = 1] number of OpenMP threads - significant ",
"       only if OpenMP is enabled.during install",
"       ",
"     ",
"     Dump Flags - switch verbose output, written to cout[rank] in working directory ",
"     (see Output in Notes, below):",
"       ",
"       ",
"       dump_pi   = [int] [Default = 0] - dump parallel/dom decomp info",
"       ",
"       dump_lda  = [int] [Default = 0] - dump grid data for allocated arrays, including ",
"                   ghost cell zones.",
"       ",
"       dump_ldc  = [int] [Default = 0] - dump grid data for arrays updated in this process ",
"                   (not including ghost cells).",
"       ",
"       dump_lds  = [int] [Default = 0] - dump grid data for send arrays",
"       ",
"       dump_ldr  = [int] [Default = 0] - dump grid data for receive arrays",
"       ",
"       dump_term = [int] [Default = 0] - dump trace sampling data",
"       ",
"       printact  = [int] [Default = 0] - timestep action output: 0 - no output, ",
"                   1 - timestep number, 2 - detailed actions within timestep.",
"       ",
" ",
" Alternate Use Cases",
" ",
" This section describes various alternative tasks implemented by asg.x, and ",
" corresponding parameter selection patterns.",
" ",
" ",
" Create/modify output data file: it is possible to take headers from one ",
" file of SEGY traces, yet write the output to another. To do this, specify ",
" the source of the trace headers as hdrfile, and the output data file as ",
" datafile (as in the typical use case):",
" ",
" hdrfile = [string]",
" datafile = [string]",
" ",
" In this case, the output file is overwritten in its entirety (including ",
" any SEGY header information).",
" ",
" ",
" Override of computed time steps:",
" ",
" nt   = <int> [Default: computed from hdrfile, cfl condition]",
" dt   = <float> [Default: computed from hdrfile, cfl condition]",
" ",
"  If present, nt and dt override the number of time samples ",
"  and time step computed from hdrfile and cfl, for BOTH",
"  internal simulator time stepping AND output traces - i.e.",
"  if this option is chosen, then output traces will have",
"  nt samples and time step dt, overriding the values from  ",
"  the input header file (though the source and receiver locations",
"  remain as determined by the input header file). Note that ",
"  either neither or both must be set. This option is ",
"  useful mostly for convergence studies, for precise",
"  control of time step. No stability checking is",
"  performed by the code in this case, so ensuring stability",
"  is entirely up to the user - caveat emptor! ",
" ",
" ............. Under Construction.............................. ",
" ",
  0 };
