from rsfproj import *

Flow('time',None,
     "spike n1=200 d1=1 o1=1 label1='Sample' | headermath output='N*0.4'")
Flow('head','time',"window n1=41 | math output='exp(0.25*input)+11'")
Flow('ideal','time',"math output='sin(input)*0.5'")
Flow('alias','head',"math output='sin(input)*0.5'")

doty = 'dots dots=0 connect=0 gaineach=0 constsep=1 strings=0 clip=1.2'

Flow('data',['alias','head'],'bin1 head=${SOURCES[1]} nx=200 dx=0.4 x0=0')
Plot('data','data',doty + ' strings=1 d1=1 o1=1')
Plot('ideal','ideal',doty + ' connect=1')
Plot('both','data ideal','Overlay')
Result('data','both data','SideBySideAniso')

doty = doty + ' connect=1 d1=1 o1=1'

name = 'if'
title = ['Regularization','Preconditioning']
for prec in [0,1]:
    iters = []
    res = name[prec] + 'm'
    labels = ''
    for niter in [2,4,8,16,300]:
        iter = res + str(niter)
        iters.append(iter)
        Flow(iter,['alias','head'],
             '''invbin1 head=${SOURCES[1]} nx=200 dx=0.4 x0=0
             filter=1 prec=%d niter=%d''' % (prec,niter))
        labels = labels + 'iter=%d:' % niter
    Plot(res,iters,
         '''
         cat axis=2 ${SOURCES[1:%d]} | %s connect=1 overlap=2
         title=%s labels=%s labelsz=10 
         ''' % (len(iters),doty,title[prec],labels))
Result('conv',['im','fm'],'SideBySideAniso')

###########################################################################

End()
