  " ",
  " ----------------------------- GRIDMASKOP -----------------------------------",
  " ",
  " Mask operator ",
  " set value outside the boundary specified by following parameters to zero.",
  " iwave/grid/include/gridops.hh",
  " ",
  " ---------------------- begin gridmaskop parameters -------------------------",
  " ",
    " swwi = 0.0      width at the start of dimension i, m",
    " ewwi = 0.0      width at the end   of dimension i, m",
    " i = 1, 2, or 3 ",
  " ",
  " ---------------------- end gridmaskop parameters ---------------------------",
