from rsf.proj import *

Fetch('wz.24.H','wz')

Flow('arctic','wz.24.H',
     'dd form=native | put label2=Offset unit2=km label1=Time unit1=s')
Plot('arctic','window max1=2.5 | grey title=Input')

Flow('pow','arctic','pow pow1=2')
Plot('pow','window max1=2.5 | grey title="sfpow pow1=2" ')

Flow('agc','arctic','agc rect1=100')
Plot('agc','window max1=2.5 | grey title="sfagc rect1=100" ')

Result('arctic','arctic pow agc','SideBySideAniso')

Flow('shagc','arctic','shapeagc rect1=100')
Plot('shagc','window max1=2.5 | grey title="sfshapeagc rect1=100" ')

Result('agc','agc shagc','SideBySideAniso')

End()
