from rsfproj import *
from rwedemo import *
import zomig

par = {
    'nz':751,  'dz':0.004,'oz':0,     # CC axis 1
    'nx':2301, 'dx':0.004,'ox':0,     # CC axis 2
    'nt':1500, 'dt':0.001,'ot':0,     # RC axis 1
    'ng':1024, 'dg':0.175,'og':-89.6, # RC axis 2
    'nT':2500, 'dT':0.001,'oT':0,       'kT':1000,    # time
    'tmx':10,'eps':0.0000001, 'verb':'y','nrmax':1,
    'ow':1, 'incore':'y',
    'spx':1250
    }

# compute parameters
param(par)

# ------------------------------------------------------------
Fetch(['marmvel.hh'],'marm')

# true velocity
Flow('vel','marmvel.hh',
     '''
     dd form=native |
     smooth rect1=5 rect2=5 |
     scale rscale=0.001 |
     put label1=z label2=x
     o1=%(oz)g d1=%(dz)g
     o2=%(ox)g d2=%(dx)g
     ''' % par)
Plot('vel',cgrey('allpos=y',par))

# smooth velocity
Flow('vsm','vel','smooth rect1=201 rect2=201')

# wavefronts (by HWT)
Flow('hwt','vsm',
     '''
     hwt2d verb=n xsou=5 zsou=0 
     nt=%(nt)d ot=%(ot)g dt=%(dt)g
     ng=%(ng)d og=%(og)g dg=%(dg)g
     ''' % par)

# coordinate system: rays(g,t)
Flow('cos','hwt','window min2=%(ot)g n2=%(nt)d' % par)

# coordinate system plot
cos('cos',25,25,par)
Result('cos','vel cos','Overlay')

# slowness
slow('sloCC','sloRC','vel','cos',par)
Result('sloRC','transp |'
       + rgrey('pclip=100 color=j allpos=y bias=0.18',par))

# ------------------------------------------------------------
# coordinate system coefficients (A,B,M=mask) and references (A,B)
abm('abmRC','abrRC','sloRC','cos',par)
abmplot('abmRC',par)

# ------------------------------------------------------------
# time data CC: (t,x)
Flow('datCC',None,
     '''
     spike nsp=1 mag=1
     n1=%(nT)d o1=%(oT)g d1=%(dT)g k1=%(kT)d
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=%(spx)d l2=%(spx)d|
     ricker1 frequency=10 |
     smooth rect2=10 |
     put label1=t label2=x
     ''' % par )
Result('datCC','grey pclip=100 wanttitle=n')

# ------------------------------------------------------------
# frequency data RC: (g,w)
frq('frqRC','frqCC','datCC','cos',par)

# ------------------------------------------------------------
# WEM image CC: (z,x)
zomig.image('imgCC','sloCC','frqCC',par)
Plot  ('imgCC','window | transp |'
       + cgrey('pclip=99 title=imgCC label1=z unit1=km label2=x unit2=km',par))
Result('imgCC',['imgCC','cos'],'Overlay')

# ------------------------------------------------------------
# RWE image
mig('migCC','migRC','frqRC','abmRC','abrRC','cos',par)
mod('modCC','modRC','migRC','abmRC','abrRC','cos',par)

Result('icomp','imgCC migCC-SSF migCC-F45','Movie')

End()
