##   Copyright (C) 2004 University of Texas at Austin
##  
##   This program is free software; you can redistribute it and/or modify
##   it under the terms of the GNU General Public License as published by
##   the Free Software Foundation; either version 2 of the License, or
##   (at your option) any later version.
##  
##   This program is distributed in the hope that it will be useful,
##   but WITHOUT ANY WARRANTY; without even the implied warranty of
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##   GNU General Public License for more details.
##  
##   You should have received a copy of the GNU General Public License
##   along with this program; if not, write to the Free Software
##   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
import os, string, re, glob, time, types

import SCons

# The following adds all SCons SConscript API to the globals of this module.
version = map(int,string.split(SCons.__version__,'.')[:3])
if version[0] == 1 or version[1] >= 97 or (version[1] == 96 and version[2] >= 90):
    from SCons.Script import *
else:
    import SCons.Script.SConscript
    globals().update(SCons.Script.SConscript.BuildDefaultGlobals())

import rsftex, rsfpath, sftour

#############################################################################
# CUSTOM BUILDERS
#############################################################################

command = r'\{(?:([^\}\{]*)(?:[^\{\}]*\{[^\}]*\}[^\{\}]*)*)\}'
# matches the contents of {} allowing a single level of nesting
# If an argument of has more than one level of nesting,
# this will not work (Joel)

re_author = re.compile(r'\\author\s*'+command)
re_title = re.compile(r'\\(?:title|chapter)\s*(?:\[[^\]]+\])?\s*'+command)
re_bioname = re.compile(r'{\\bf\s*([^\\\}]+)')

report = string.upper(os.path.basename(os.getcwd()))
group = re.sub('\d+$','',report)

misc = {'pub.tex': 'Articles published or in press',
        'phone.tex': '%s phone directory' % group,
        'bio.tex': 'Research personnel',
        'spons.tex': 'Sponsors'}

full = {
    'SEP': 'Stanford Exploration Project'
    }

prefs = ('abs','pref','ack')

def get_year(default):
    year = default
    if not year:
        year = time.localtime(time.time())[0]
        year = str(year)
        year = string.join([str(int(year)-1),year[-2:]],'-')
    return year

def paper_tag(paper):
    return (os.path.basename(os.path.dirname(paper)),
            re.sub('-paper$','',
                   re.sub(r'/([^/]+)\.tex$',r'-\1',paper)))

def get_author(source,default,tag):
    author = default.get(tag[1])
    if not author:
        paper = source.get_contents()
        # remove comments
        paper = re.sub(r'[%][^\n]+','',paper)
        author = re_author.search(paper)
        if author:
            author = author.group(1)
    if author:
        author = re.sub(r'(?:\,|\;|\\\&)',' and ',author)
        author = re.sub(r'\s+and(?:\s+and)*\s+',' and ',author)
        author = re.sub(r'^\s+','',author)
        author = re.sub(r'\s+$','',author)
    authors = author.split(' and ')
    if len(authors) < 3:
        return author
    else:
        return ', '.join(authors[:-1]) + ', and ' + authors[-1]

def get_authors(source,default):
    authors = {}
    for src in source:
        tag = paper_tag(str(src))
        author = get_author(src,default,tag)
        if author:
            print "%s: '%s'" % (tag[1],author)
            for person in re.split(r'\s*(?:[\,]|[\,]?\s*\band\b)\s*',author):
                names = string.split(person)
                if names:
                    person = names.pop(0) # first name
                    if names:
                        last = names.pop() # last name
                        person = string.join((person,last),'~')
                        authors[person]=last
    all = map(lambda k: (authors[k],k),authors.keys())
    all.sort()
    return all

def list_authors(all):
    lastone = all.pop()
    if len(all) == 0:
        author = lastone[1]
        print "The author is " + author
    elif len(all) == 1:
        firstone = all.pop()
        author = '%s and %s' % (firstone[1],lastone[1])
        print "The authors are " + author
    else:                
        author = string.join(map(lambda k: k[1],all),', ')
        author = '%s, and %s' % (author,lastone[1])
        print "The authors are " + author
    return author
    

def report_toc(target=None,source=None,env=None):
    "Build a table of contents from a collection of papers"
    sections = env.get('sections',{})
    authors = env.get('authors',{})
    book = env.get('book')
    if book:
        maketitle = ''
    else:
        maketitle = '\\maketitle'
    toc = open(str(target[0]),'w')
    toc.write(string.join(
        ['%% This file is automatically generated, DO NOT EDIT',
         '\\cleardoublepage',
         '\\renewcommand{\REPORT}{%s}' % report, 
         '\\maintitle{\REPORT\ --- TABLE OF CONTENTS}',
         maketitle,
         '%% start entries\n'],'\n'))
    if book:
        author = '\ '
    for src in source:
        tag = paper_tag(str(src))
        paper = src.get_contents()
        # remove comments
        paper = re.sub(r'[%][^\n]+','',paper)
        if not book:
            author = get_author(src,authors,tag)
        title = re_title.search(paper)
        if sections.has_key(tag[1]):
            toc.write('\n\\geosection*{%s}\n' % sections[tag[1]])
        if author and title:
            title = re.sub(r'\\',' ',title.group(1)) # remove line breaks 
            toc.write('\TOCentry[%s]{%s}{\pageref{%s.start}}\n' %
                      (author,title,tag[1]))
        else:
            print "Could not find author or title"
    toc.write('\n\\geosection*{\ }\n')
    year = get_year(env.get('year'))
    misc['pub.tex'] = '%s article published or in press, %s' % (group,year),
    misc['spons.tex'] = '%s sponsors for %s' % (group,year)
    map(lambda x:
        toc.write('\TOCentry{%s}{\pageref{%s.start}}\n' %
                  (misc[x],os.path.splitext(x)[0])),
        filter(os.path.isfile,misc.keys()))
    toc.write('\n\\cleardoublepage\n')
    toc.close()
    return 0

def report_tpg(target=None,source=None,env=None):
    "Build the title page"
    tpg = open(str(target[0]),'w')
    tpg.write('%% This file is automatically generated, DO NOT EDIT\n\n')
    tpg.write('\\maintitle{%s}\n' % \
              string.upper(env.get('group',full.get(group))))
    title = env.get('title1')
    if title:
        tpg.write('\\vfill\n\title{%s}\n' % title)
    authors = env.get('authors',{})
    tpg.write('\\mainauthor{%s}\n' % list_authors(get_authors(source,authors)))
    title = env.get('title2')
    if title:
        tpg.write('\\vfill\n\maintitle{%s}\n' % title)
    line = env.get('line')
    if line:
        tpg.write('\\vfill\n\\begin{center}\n'
                  '\\bfseries%%\n%s\n\\end{center}\n' % line)
    fig = env.get('fig')
    if fig:
        tpg.write('\\renewcommand{\\plotdir}{%s/Fig}\n'
                  '\\vfill\n\\begin{center}\n'
                  '\\plotbox{%s}{%s}\n\\end{center}\n' % tuple(fig))
    year = get_year(env.get('year'))
    copyr = env.get('copyr')
    tpg.write('\n\\newpage\\GEOcopyr{%s}{%s}\n' % (year,copyr))
    tpg.close()
    return 0

def thesis_tpg(target=None,source=None,env=None):
    "Build the title page for a thesis"
    tpg = open(str(target[0]),'w')
    tpg.write('%% This file is automatically generated, DO NOT EDIT\n\n')
    author = env.get('author')
    if author:
        tpg.write('\\vfill\n\\author{%s}\n' % author)
    title = env.get('title')
    if title:
        tpg.write('\\vfill\n\\title{%s}\n' % title)
    year = get_year(env.get('year'))
    tpg.write('\\copyrightyear{%s}\n' % year)
    tpg.write('\\dept{Geophysics}\n')
    tpg.close()
    return 0

def book_tpg(target=None,source=None,env=None):
    "Build the title page for a book"
    tpg = open(str(target[0]),'w')
    tpg.write('%% This file is automatically generated, DO NOT EDIT\n\n')
    author = env.get('author')
    if author:
        tpg.write('\\vfill\n\\author{%s}\n' % author)
    title = env.get('title')
    if title:
        tpg.write('\\vfill\n\\title{%s}\n' % title)
    fig = env.get('fig')
    if fig:
        tpg.write('\\renewcommand{\\plotdir}{%s/Fig}\n'
                  '\\vfill\n\\begin{center}\n'
                  '\\plotbox{%s}{%s}\n\\end{center}\n' % tuple(fig))
    year = get_year(env.get('year'))
    tpg.write('\\date{\\copyright\\ \\today}\n')
    tpg.write('\\maketitle\n')
    tpg.write('\\tableofcontents\n')
    tpg.close()
    return 0

def thesis_intro(target=None,source=None,env=None):
    "Build the introductory part of a thesis"
    intro = open(str(target[0]),'w')
    intro.write('%% This file is automatically generated, DO NOT EDIT\n\n')
    committee = env.get('committee')
    if committee:
        for i in range(4):
            if len(committee) > i:            
                intro.write('\\%s{%s}\n' %
                            (('principaladviser','firstreader','secondreader','thirdreader')[i],
                             committee[i]))
    intro.write('\\beforepreface\n')
    intro.write('\\newpage \\ \n')
    for pref in prefs:
        tex = pref+'.tex'
        if os.path.isfile(tex): # input if file exists
            print "Found %s" % tex
            intro.write('\\input{%s}\n' % pref)
    intro.write('\\afterpreface\n')
    intro.close()
    return 0

def report_bio(target=None,source=None,env=None):
    "Build author biographies"
    bio = open(str(target[0]),'w')
    bio.write('\\maintitle{Research Personnel}\n')
    bio.write('\\begin{bios}\n')
    bio.write('\\label{bio.start}\n')
    bios = env.get('bios')
    authors = env.get('authors',{})
    authors = get_authors(source,authors)
    for author in authors:
        name = author[1]
        biofile = bios.get(name)
        if biofile:
            pdf = os.path.splitext(biofile)[0]+'.pdf'
            if os.path.isfile(pdf):
                bio.write('\\item\\bioplot{%s}{%%\n' % pdf)
                thisbio = open(biofile)
                bio.writelines(thisbio.readlines())
                thisbio.close()
                bio.write('}\n')
            else:
                print 'No picture file for ' + name
        else:
            print 'No biography file for ' + name
    bio.write('\\end{bios}\n')
    bio.close()
    return 0

def include(file,sep=''):
    tex = file+'.tex'
    if os.path.isfile(tex):
        print "Found %s" % tex
        return '\\include{%s}\t%s\t\\newpage\n' % (file,sep)
    else:
        return ''

def report_all(target=None,source=None,env=None):
    "Build the main paper"
    all = open(str(target[0]),'w')
    grp = env.get('group',full.get(group))
    rep = env.get('report',report)
    map(all.write,
        ['%% This file is automatically generated, DO NOT EDIT\n\n',
         '\\renewcommand{\\REPORT}{%s}\n' % rep,
         '\\renewcommand{\\GROUP}{%s}\n' % grp,
         '\\renewcommand{\\thepage}{}\n',
         include('tpg','\\cleardoublepage'),
         include('preface'),
         '\\pagenumbering{roman}\n',
         '\\setcounter{page}{1}\n',
         include('toc'),
         include('intro'),
         '\\cleardoublepage\n',
         '\\pagenumbering{arabic}\n',
         '\\setcounter{page}{1}\n',
         '\\GEOheader{\\GROUP, Report \\REPORT, \\today}\n'
         ])
    all.write('%% start of paper list\n')
    resdirs = env.get('resdirs',{})
    for src in source:
        paper = str(src)
        tag = paper_tag(paper)
        stem = os.path.splitext(paper)[0]
        resdir = resdirs.get(tag[0],'Fig')
        all.write('\\setfigdir{%s}' % resdir)
        all.write('\\GEOpaper{%s}{%s}\t\\include{%s}\n' % (tag[0],tag[1],stem))
        all.write('\\cleardoublepage\n')
    all.write('%% end of paper list\n')
    for tex in misc.keys():
        all.write(include(os.path.splitext(tex)[0]))
    biblio = env.get('biblio')
    if biblio:
        all.write('\\newpage\n\\bibliographystyle{seg}\n\\bibliography{%s}\n'
                  % biblio)
    index = env.get('index')
    if index:
        map(all.write,
            ['\\cleardoublepage\n',
             '\\addcontentsline{toc}{chapter}{Index}\n',
             '\\index{index}\n',
             '\\printindex\n'])
    all.close()
    return 0

def tour(target=None,source=None,env=None):
    dirs = map(os.path.dirname,map(str,source))
    command = env.get('command')
    sftour.tour(dirs,command,0)
    return 0

Tour = Builder(action = Action(tour),varlist=['command'])

def Sections(report):
    sections = {}
    for section in report:
        first = Split(section[1])[0]
        sections[paper_tag(first)[1]]= section[0]
    return sections

class RSFReport(Environment):
    def __init__(self,**kw):
        apply(Environment.__init__,(self,),kw)
        self.Append(BUILDERS={'Tour':Tour})
        cwd = os.getcwd()
        # create a hierarcical structure
        self.tree = (os.path.basename(os.path.dirname(cwd)),
                     os.path.basename(cwd))
        self.doc = os.environ.get(
            'RSFDOC',os.path.join(os.environ.get('RSFROOT'),'doc'))
        for level in self.tree:
            if level:
                self.doc = os.path.join(self.doc,level)
        rsfpath.mkdir(self.doc)
        self.paper = 1
    def Papers(self,papers,**kw):
        # get list of papers
        if type(papers[0]) is types.TupleType:
            sections = Sections(papers)
            kw.update({'sections':sections})
            papers = Split(string.join(map(lambda x: x[1],papers)))
        for i in range(len(papers)):
            paper = papers[i]
            if paper[-4:] != '.tex':
                papers[i] = paper + '/paper.tex'
            elif '/' in paper:
                self.paper = 0
        # make table of contents
        kw.update({'action':Action(report_toc),
                   'varlist':['year','sections','authors']})
        apply(self.Command,('toc.tex',papers),kw)
        rsftex.Paper('toc',lclass='georeport',scons=0)
        map(lambda tex: self.Depends('toc.tex',tex),
            filter(os.path.isfile,misc.keys()))
        # make title page
        kw.update({'action':Action(report_tpg),
                   'varlist':['group','title1','authors','title2','line',
                              'fig','year','copyr']})
        apply(self.Command,('tpg.tex',papers),kw)
        rsftex.Paper('tpg',lclass='georeport',scons=0)
        # make biographies
        bios = kw.get('bios')
        biofiles = {}
        if bios:
            for biofile in glob.glob(os.path.join(bios,'*.bio')):
                bio = open(biofile)
                line = bio.readline()
                name = re_bioname.search(line)
                if name:
                    name = string.split(name.group(1))
                    biofiles[string.join([name[0],name[-1]],'~')] = biofile
                bio.close()
        if biofiles:
            kw.update({'action':Action(report_bio),
                       'varlist':['bios'],
                       'bios':biofiles})
            apply(self.Command,('bio.tex',papers),kw)
            self.Depends('bio.tex','tpg.tex')
            rsftex.Paper('bio',lclass='georeport',scons=0)
        # make report
        kw.update({'action':Action(report_all),'varlist':['group','resdirs']})
        self.papers = papers
        apply(self.Command,('book.tex',papers),kw)
        self.Depends('book.tex','toc.tex')
        self.Depends('book.tex','tpg.tex')
        if biofiles:
            self.Depends('book.tex','bio.tex')
        # Touring individual papers
        for target in ('html','pdf','install'):
            if self.paper:
                comm = 'scons -Q ' + target
            else:
                comm = map(lambda x: 'scons -Q %s.%s' % \
                           (os.path.splitext(os.path.basename(x))[0],target),
                           papers)
            self.Tour(target+'s',papers,command=comm)
    def Thesis(self,chapters,**kw):
        # get list of chapters
        for i in range(len(chapters)):
            chapter = chapters[i]
            # add suffix if missing
            if chapter[-4:] != '.tex':
                chapters[i] = chapter + '/paper.tex'
        # make title page
        kw.update({'action':Action(thesis_tpg),
                   'varlist':['author','title','year']})
        apply(self.Command,('tpg.tex',None),kw)
        rsftex.Paper('tpg',lclass='stanford-thesis',scons=0)
        # make introductory materials
        kw.update({'action':Action(thesis_intro),
                   'varlist':['committee']})
        apply(self.Command,('intro.tex',None),kw)
        rsftex.Paper('intro',lclass='stanford-thesis',scons=0)
        for pref in prefs:
            tex = pref+'.tex'
            if os.path.isfile(tex):
                self.Depends('intro.tex',tex)
        # make report
        kw.update({'action':Action(report_all),
                   'varlist':['group','resdirs','biblio','report']})
        self.papers = chapters
        apply(self.Command,('book.tex',chapters),kw)
        self.Depends('book.tex','tpg.tex')
        self.Depends('book.tex','intro.tex')
        for target in ('html','pdf','install'):	
            comm = 'scons -Q ' + target
            self.Tour(target+'s',chapters,command=comm)
    def Book(self,chapters,**kw):
        # get list of chapters
        for i in range(len(chapters)):
            chapter = chapters[i]
            # add suffix if missing
            if chapter[-4:] != '.tex':
                chapters[i] = chapter + '/paper.tex'
        # make table of contents
        kw.update({'action':Action(report_toc),
                   'varlist':['year','sections','book'],
                   'book':1})
        apply(self.Command,('toc.tex',chapters),kw)
        rsftex.Paper('toc',lclass='georeport',scons=0)
        # make title page
        kw.update({'action':Action(book_tpg),
                   'varlist':['author','title','fig']})
        apply(self.Command,('tpg.tex',None),kw)
        rsftex.Paper('tpg',lclass='georeport',options='book',scons=0)
        # make book
        kw.update({'action':Action(report_all),'varlist':['index']})
        self.papers = chapters
        apply(self.Command,('book.tex',chapters),kw)
        self.Depends('book.tex','tpg.tex')
        self.Depends('book.tex','intro.tex')
        for target in ('html','pdf','install'):	
            comm = 'scons -Q ' + target
            self.Tour(target+'s',chapters,command=comm)
    def End(self,lclass='georeport',**kw):
        kw.update({'lclass':lclass})
        apply(rsftex.Paper,('book',),kw)
        self.Alias('pdf','book.pdf')
        self.Depends('book.pdf','pdfs')
        self.Depends('book.pdf',self.papers)
        self.Alias('read','book.read')
        self.Alias('print','book.print')
        self.Alias('html','toc_html')
        self.Depends('toc_html/index.html','htmls')
        self.Depends('html','htmls')
        self.Install(self.doc,'book.pdf')
        html = os.path.join(self.doc,'index.html')
        self.Command(html,'toc_html/index.html',
                    'cd $SOURCE.dir && cp -R * $TARGET.dir && cd ..')
        self.Alias('www',self.doc)
        self.Depends('www','installs')
        self.Default('pdf')

# Default report
book = RSFReport()
def Papers(papers=glob.glob('[a-z]*/paper.tex'),**kw):
    return apply(book.Papers,(papers,),kw)
def Thesis(chapters=glob.glob('[a-z]*/paper.tex'),**kw):
    return apply(book.Thesis,(chapters,),kw)
def Book(chapters=glob.glob('[a-z]*/paper.tex'),**kw):
    return apply(book.Book,(chapters,),kw)
def End(lclass='georeport',**kw):
    return apply(book.End,(lclass,),kw)



