from rsf.proj import *

Fetch('Gulfnear.HH','mig')

Flow('gulflowb','Gulfnear.HH',
     '''
     dd form=native |
     window f2=200 n2=480 n1=1000 |
     bandpass flo=10 fhi=50
     ''')

Plot('Gulfdata','gulflowb',
     '''
     window f2=60 n2=360 max1=2.0 |
     pow pow1=0.5 | 
     grey label1=Time unt1=s label2=Midpoint unit2=m 
     labelfat=2 labelsz=4 titlefat=2 titlesz=5 
     xll=3.0 yll=5.28  xur=11.0 yur=9.77  title="(a)" 
     ''')

vwater=1500
alpha=460
beta=0.5
twater=0.20

Flow('water','gulflowb','window n2=1 | spike | cut max1=%g' % twater)

Flow('vel','water',
     '''
     math output="%g+input*(%g * abs(x1 - %g)^%g)" 
     ''' % (vwater,alpha,twater,beta))

Flow('Gulfmigaa4s','gulflowb vel','kirchnew velocity=${SOURCES[1]}')

Plot('Gulfmigaa','Gulfmigaa4s',
     '''
     window f2=60 n2=360 max1=2.0 | pow pow1=0.5 |
     grey label1=Time unt1=s wantaxis2=n
     labelfat=2 labelsz=4 titlefat=2 titlesz=5 
     xll=3.0 yll=0.32  xur=11.0 yur=4.81  title="(b)" 
     ''')

Result('Gulfaa','Gulfdata Gulfmigaa','Overlay')

End()
