from rsfproj import *

Flow('Ricker',None,
     '''spike n1=1024 | spectra |
     math output="x1*x1/1000" | math output="input*exp(-input)"
     ''')


Flow('ricker0 ricker1 ricker2','Ricker',
     '''
     rtoc | fft1 inv=y > ${TARGETS[1]} &&
     window < ${TARGETS[1]} n1=512  > ${TARGETS[2]} &&
     window < ${TARGETS[1]} n1=512 f1=512 | cat axis=1 ${TARGETS[2]} |
     window n1=41 f1=492
     ''')
Flow('integr','ricker0','causint')

Result('spec','ricker0 integr minphase',
       '''
       cat axis=2 ${SOURCES[1:3]} |
       pad n1=1024 |
       spectra |
       graph title=Spectrum label1="Frequency (Hz)" 
       ''')

Flow('minphase','Ricker',
     '''
     add mode=prod $SOURCE | kolmog spec=y | window n1=20 | pad n1=41 beg1=21
     ''')
Result('time','minphase ricker0',
       '''
       cat axis=2 ${SOURCES[1]} |
       dots labels=Min-phase:Zero-phase title="Ricker Wavelet" label1=" "
       ''')

###########################################################################
End()
