from rsf.proj import *

sys.path.append('..')
import gradient

gradient.zero_offset('zodata')

Result('zodata','grey title="Zero-Offset" ')

from rsf.recipes.tpx import TPX

vmin=1.5

TPX('tpx','zodata',nt=2001,np=351,p0=-1.9/vmin,nw=206)

Result('tpx',
       '''
       byte gainpanel=all |
       transp plane=23 |
       grey3 flat=n frame1=1000 frame2=150 frame3=150
       title=TPX
       ''')

Flow('xpt','tpx','transp plane=13 memsize=1000')

par = gradient.par

Flow('veloc','zodata',
     '''
     window n1=1 | spray axis=1 n=501 o=0 d=0.01 label=Depth unit=km | 
     math output="%(v0)g+%(gradx)g*x2+%(gradz)g*x1" | 
     put label=Velocity unit=km/s | transp
     ''' % par)

Flow('vgrad','zodata',
     '''
     window n1=1 | spray axis=1 n=501 o=0 d=0.01 label=Depth unit=km | 
     spike mag=%(gradx)g | transp
     ''' % par)

Flow('xpz','xpt veloc vgrad','oway1 velocity=${SOURCES[1]} vgrad=${SOURCES[2]}')

End()
