from rsfproj import *
# ------------------------------------------------------------
# PLOTTING
# ------------------------------------------------------------
def igrey(custom,par):
    return '''
    grey labelrot=n title=" " %s
    label1="z" label2="x"
    min1=%g max1=%g min2=%g max2=%g
    ''' % (custom,par['zmin'],par['zmax'],par['xmin'],par['xmax'])

def pgraph(args,par):
    return '''
    graph labelrot=n title=" " %s
    label1="z" label2="x"
    yreverse=y symbolsz=16 wantaxis=n
    min2=%g max2=%g min1=%g max1=%g
    ''' % (args,par['zmin'],par['zmax'],par['xmin'],par['xmax'])

def dgrey(args,par):
    return '''
    grey labelrot=n title=" " %s
    label1="t" label2="x"
    min2=%g max2=%g
    ''' % (args,par['xmin'],par['xmax'])
# ------------------------------------------------------------

# ------------------------------------------------------------
## 
 # Simple model
 ##
# ------------------------------------------------------------
par = {
    'nz':250, 'dz':2.5, 'oz':0,
    'nx':250, 'dx':4.0, 'ox':0,
    'nt':2000,'dt':0.00025,'ot':0, 'kt':200,
    'nw':60,  'ow':5,
    'nw':100, 'ow':0, 'jw':1,
    'tx':16, 'px':0, 'eps':0.01, 'nrmax':3,
    'kz':200,
    'ds':8, 'os':400, 'ns':1
    }
par['xmin']=par['ox']
par['xmax']=par['ox'] + (par['nx']-1) * par['dx']
par['zmin']=par['oz']
par['zmax']=par['oz'] + (par['nz']-1) * par['dz']

par['ft']=par['kt']*par['dt']
par['nwpad']=par['nt']/2 + 1

ns=1
os=400
ds=8

# ------------------------------------------------------------
# VELOCITY / SLOWNESS
# ------------------------------------------------------------
Flow('vel',None,
     '''
     spike nsp=3 mag=0,2000,0
           n1=%(nz)d d1=%(dz)g o1=%(oz)g
           k1=160,080,180
           l1=250,140,250
           label1="z"
           n2=%(nx)d d2=%(dx)g o2=%(ox)g
           k2=001,101,151
           l2=100,150,250
           label2="x"|
     math output="input + 2000"
     ''' % par)
Flow('s0','vel',
     '''
     transp |
     math "output=1/input" |
     spray axis=2 n=1 |
     put label2=y
     ''' % par )
# ------------------------------------------------------------
# REFLECTIVITY
# ------------------------------------------------------------
Flow('refl',None,
     '''
     spike nsp=3 mag=0,1,0
           n1=%(nz)d d1=%(dz)g o1=%(oz)g
           k1=160,080,180
           l1=160,080,180
           label1="z"
           n2=%(nx)d d2=%(dx)g o2=%(ox)g
           k2=001,101,151
           l2=100,150,250
           label2="x"
     ''' % par)
Flow('r0','refl',
     '''
     transp |
     spray axis=2 n=1 o=0 d=1 |
     put label2=y
     ''' % par)

Result('s0','s0','window      | transp |'+igrey('pclip=99 allpos=y color=j',par))
Result('r0','r0','window      | transp |'+igrey('pclip=100',par))

# ------------------------------------------------------------
# wavelet
Flow('ttt',None,
     '''
     spike nsp=1
     n1=%(nt)d d1=%(dt)g o1=%(ot)g k1=%(kt)d
     n2=1      d2=%(dx)g o2=%(os)g |
     ricker1 frequency=25 |
     put label1=t label2=x
     ''' % par)
Result('ttt','ttt','window | graph')

Flow('sou','ttt',
     '''
     fft1 |
     window squeeze=n n1=%(nw)d min1=%(ow)g j1=%(jw)d |
     put label1=w
     ''' % par )
Result('sou','sou','real | graph')
# ------------------------------------------------------------

Plot('vel','vel',igrey('pclip=100 bias=900 allpos=y',par))

# ------------------------------------------------------------

Flow('rs',None,'math n1=1 d1=0 o1=0 output=1')

for i in range(ns):
    o = os+i*ds
    par['o']=o
    
    zs = 'zs' + str(i)
    xs = 'xs' + str(i)

    zr = 'zr' + str(i)
    xr = 'xr' + str(i)    
    ss = 'ss' + str(i)
    rr = 'rr' + str(i)

    dd = 'dd' + str(i)
    ee = 'ee' + str(i)
    ww = 'ww' + str(i)
    sh = 'sh' + str(i)

    gg = 'gg' + str(i)

    Flow(zs,None,'math n1=1 d1=0 o1=0 output=0')
    Flow(xs,None,'math n1=1 d1=0 o1=0 output=%(o)g' % par)

    Flow(zr,None,'math n1=250 d1=%(dx)g o1=0 output="00"' % par )
    Flow(xr,None,'math n1=250 d1=%(dx)g o1=0 output="x1"' % par )

    Flow(ss,[xs,zs,'rs'],'cat axis=2 space=n ${SOURCES[0]} ${SOURCES[1]} ${SOURCES[2]} | transp ', stdin=0)
    Flow(rr,[xr,zr]     ,'cat axis=2 space=n ${SOURCES[0]} ${SOURCES[1]}               | transp ', stdin=0)

    Plot(ss,ss,'window n1=2 | dd type=complex | window | ' + pgraph('symbol=* plotcol=2',par))
    Plot(rr,rr,'window n1=2 | dd type=complex | window | ' + pgraph('symbol=. plotcol=1 symbolsz=.01',par))

    Result(gg,['vel',ss,rr],'Overlay')
    
    Flow([dd,ww],['ttt','vel',ss,rr],
     '''
     afdm2d verb=y abc=y free=n snap=y jsnap=100
         nbz=50 tz=0.006125
         nbx=50 tx=0.006125 
         vel=${SOURCES[1]}
         sou=${SOURCES[2]}
         rec=${SOURCES[3]}
         wfl=${TARGETS[1]}
     ''' % par)
    
    Plot(ww,ww,'window n3=1 f3=10 |' + igrey('pclip=100',par))
    Result(ww,[ww,ss,rr],'Overlay')
    
    Plot(dd,dd,'transp |' + dgrey('pclip=99',par))
    Result(dd,[dd,ss,rr],'Overlay')

# ------------------------------------------------------------

Flow('sdd','sou',
     '''
     pad beg2=100 n2out=%(nx)d |
     transp |
     spray axis=2 n=1 o=0 d=1 |
     put label1=x label2=y
     ''' % par )
Flow('srr www','sdd s0 r0',
     '''
     srmod readwrite=y verb=y eps=0.01 nr=5 dt=0.00005 tx=32 px=100
     slo=${SOURCES[1]}
     ref=${SOURCES[2]}
     www=${TARGETS[1]}
     ''')

Flow('trr','srr',
     '''
     window |
     transp |
     pad n1out=%(nwpad)d |
     fft1 inv=y |
     put label1=t
     ''' % par)

Plot('trr','trr',dgrey('pclip=100',par))
Result('trr',['trr','ss0','rr0'],'Overlay')

End()
