from rsfproj import *
import zomig,spmig,rweutil

par = {
    'nz':600,  'dz':0.010,    'oz':0,     # CC axis 1
    'nt':400,  'dt':0.010,    'ot':1.0,   # RC axis 1
    'nx':800,  'dx':0.020,    'ox':0,     # CC axis 2
    'ng':400,  'dg':0.200,    'og':-120,    # RC axis 2
    'ny':1,    'dy':1,        'oy':0,     # CC axis 3
    'nT':2000, 'dT':0.004,    'oT':0,     'kT':250, # time
    'tmx':10,'eps':0.0000001, 'verb':'y','nrmax':1,
    'ow':1, 'incore':'y',
    'xsou':19.5,'zsou':2.4,'ysou':0
    }
par['dw']=1/(par['nT']*par['dT'])
par['nw']=par['nT']/1000*25

#par['nw']=2
#par['ow']=3

par['spx']=10/par['dx']

# ------------------------------------------------------------
par['xmin']=par['ox']                             #-1
par['xmax']=par['ox'] + (par['nx']-1) * par['dx'] #+1
par['zmin']=par['oz']                             #-1
par['zmax']=par['oz'] + (par['nz']-1) * par['dz'] #+1
par['tmin']=par['ot']
par['tmax']=par['ot'] + (par['nt']-1) * par['dt']
par['gmin']=par['og']
par['gmax']=par['og'] + (par['ng']-1) * par['dg']
# ------------------------------------------------------------

def cgrey(custom,par):
    return '''
    grey labelrot=n wantaxis=y wanttitle=y
    title="" pclip=100 label1="z(m)" label2="x(m)" %s
    min1=%g max1=%g min2=%g max2=%g
    ''' % (custom,par['zmin'],par['zmax'],par['xmin'],par['xmax'])
def rgrey(custom,par):
    return '''
    grey labelrot=n wantaxis=y wanttitle=y
    title="" pclip=100 label1="t(s)" label2="g" %s
    min1=%g max1=%g min2=%g max2=%g
    ''' % (custom,par['tmin'],par['tmax'],par['gmin'],par['gmax'])

def cgraph(custom,par):
    return '''
    graph labelrot=n  %s
    yreverse=y wantaxis=n title=" " 
    min1=%g max1=%g min2=%g max2=%g min1=0
    ''' % (custom,par['xmin'],par['xmax'],par['zmin'],par['zmax'])

# ------------------------------------------------------------

# velocity
Flow('vel',None,
     '''
     spike
     n1=%(nz)d o1=%(oz)g d1=%(dz)g
     n2=%(nx)d o2=%(ox)g d2=%(dx)g |
     math output=2+0.5*x1-0.0*x2 |
     put label1=z label2=x
     ''' % par)
Plot('vel',cgrey('allpos=y bias=2',par))

# ------------------------------------------------------------

# wavefronts (by HWT)
Flow('hwt','vel',
     '''
     hwt2d verb=n
     xsou=%(xsou)g zsou=%(zsou)g
     nt=1000 ot=0 dt=%(dt)g
     ng=%(ng)d og=%(og)g dg=%(dg)g
     ''' % par)
# coordinate system: rays(g,t)
Flow('cos','hwt',
     '''
     window min2=%(ot)g n2=%(nt)d |
     reverse which=2 |
     put d2=%(dt)g o2=%(ot)g
     ''' % par)

Plot('wft','cos','window f1=10 j1=10 | transp |'
     + cgraph('plotcol=1',par))
Plot('ray','cos','window       j2=10 |'
     + cgraph('plotcol=2',par))
Result('cos','vel ray wft','Overlay')

# ------------------------------------------------------------

# slowness in CC
Flow('sloCC','vel',
     '''
     math output="1/input" |
     transp |
     spray axis=2 n=1 o=0 d=1 |
     put label1=x label2=y label3=z
     ''')
# slowness in RC
rweutil.C2Rimg('sloRC','sloCC','cos',par)
Result('sloRC','transp |'
       + rgrey('pclip=100 color=j allpos=y bias=0.201',par))

# coordinate system coefficients (A,B,M=mask)
# and references (A,B)
Flow(['abmRC','abrRC'],['cos','sloRC'],
     '''
     rweab naref=1 nbref=1
     slo=${SOURCES[1]} abr=${TARGETS[1]}
     ''')

Plot('aRC','abmRC','window n3=1 f3=0 | transp |'
     + rgrey('pclip=100 color=F allpos=n bias=1',par))
Plot('bRC','abmRC','window n3=1 f3=1 | transp |'
     + rgrey('pclip=100 color=F allpos=y bias=19',par))
Plot('mRC','abmRC','window n3=1 f3=2 | transp |'
     + rgrey('pclip=100 color=j allpos=y',par))
Result('abmRC','aRC bRC','SideBySideAniso')

# ------------------------------------------------------------
# modeling wavelet

Flow('wav',None,
     '''
     spike nsp=1 mag=1 
     n1=%(nT)d d1=%(dT)g o1=%(oT)g k1=%(kT)d
     n2=%(nx)d d2=%(dx)g o2=%(ox)g k2=%(spx)d
     n3=1    d3=%(dy)g   o3=0 |
     ricker1 frequency=5 |
     put label1=t label2=x label3=y 
     ''' % par )    
Result('wav','graph title=" " grid=y')

rweutil.t2w('wavCC','wav',par)
Result('wavCC','window | real | transp | grey pclip=100')

rweutil.C2Rdat('wavRC','wavCC','cos',par)
Result('wavRC','window n3=1 | real | transp |'
       + rgrey('title',par))

# ------------------------------------------------------------
# migration wavelet (impulse)

Flow('spk',None,
     '''
     spike nsp=1 mag=1 
     n1=%(nT)d d1=%(dT)g o1=%(oT)g k1=1
     n2=%(nx)d d2=%(dx)g o2=%(ox)g k2=%(spx)d
     n3=1    d3=%(dy)g   o3=0 |
     put label1=t label2=x label3=y 
     ''' % par )    
Result('spk','graph title=" " grid=y')

rweutil.t2w('spkCC','spk',par)
Result('spkCC','window | real | transp | grey pclip=100')

rweutil.C2Rdat('spkRC','spkCC','cos',par)
Result('spkRC','window n3=1 | real | transp |'
       + rgrey('title',par))

# ------------------------------------------------------------
# modeling reflectivity

Flow('refCC',None,
     '''
     spike nsp=1 mag=1
     n1=%(nz)d o1=%(oz)g d1=%(dz)g
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=750
     n3=%(ny)d o3=%(oy)g d3=%(dy)g |
     put label1=z label2=x label3=y |
     transp plane=12 | transp plane=23
     ''' % par)
Plot  ('refCC','window | transp |' + cgrey('pclip=100',par))
Result('refCC','refCC ray wft','Overlay')

rweutil.C2Rimg('refRC','refCC','cos',par)
Result('refRC','window | transp |' + rgrey('pclip=100',par))

# ------------------------------------------------------------
# SHOT-RECORD
# ------------------------------------------------------------

# data: R
rweutil.SPmod('spfRC','wavRC','refRC','abmRC','abrRC',par)
Result('spfRC','window n3=1 f3=20 | real | transp |'
       + rgrey('pclip=99',par))

# data: R -> C
rweutil.R2Cdat('spfCC','spfRC','cos',par)

# data: w -> t
rweutil.w2t('spdCC','spfCC',par)
Result('spdCC','grey pclip=100 wanttitle=n grid=y')

# data: t -> w
rweutil.t2w('spwCC','spdCC',par)
Result('cutCC','real | grey pclip=100 wanttitle=n grid=y')

# data: C -> R
rweutil.C2Rdat('spwRC','spwCC','cos',par)

# image: R
rweutil.SPmig('spiRC','spkRC','spwRC','abmRC','abrRC',par)
Result('spiRC','window | transp |' + rgrey('',par))

# image: R -> C
rweutil.R2Cimg('spiCC','spiRC','cos',par)
Plot  ('spiCC','window | transp |' + cgrey('',par))
Result('spiCC',['spiCC','ray','wft'],'Overlay')


# --------------
# frequency data CC: (x,w)
Flow('frqCC','spdCC',
     '''
     fft1 opt=n inv=n |
     window squeeze=n min1=%(ow)g j1=1 n1=%(nw)d |
     transp plane=12 | transp plane=23 |
     put label1=x label2=y label3=w
     ''' % par)
Result('frqCC','window | real | transp | grey pclip=100')

# frequency data RC: (g,w)
rweutil.C2Rdat('frqRC','frqCC','cos',par)
Result('frqRC',
       'window n3=1 f3=20 | real | transp |' + rgrey('',par))

# WEM image CC: (z,x)
spmig.image('imgCC','sloCC','spkCC','frqCC',par)
Plot  ('imgCC','window | transp |'+ cgrey('',par))
Result('imgCC',['imgCC','ray','wft'],'Overlay')
# --------------


# ------------------------------------------------------------
# ZERO-OFFSET
# ------------------------------------------------------------

# data; R
rweutil.ZOmod('zofRC','refRC','abmRC','abrRC',par)
Result('zofRC','window n3=1 f3=20 | real | transp |'
       + rgrey('pclip=99',par))

# data: R -> C
rweutil.R2Cdat('zofCC','zofRC','cos',par)

# data: w -> t
rweutil.w2t('zodCC','zofCC',par)
Result('zodCC','grey pclip=100 wanttitle=n grid=y')

# image: R
rweutil.ZOmig('zoiRC','zofRC','abmRC','abrRC',par)
Result('zoiRC','window | transp |' + rgrey('',par))

# image: R -> C
rweutil.R2Cimg('zoiCC','zoiRC','cos',par)
Plot  ('zoiCC','window | transp |' + cgrey('',par))
Result('zoiCC',['zoiCC','ray','wft'],'Overlay')

# ------------------------------------------------------------


End()
