from rsfproj import *
import zomig,rwezo

par = {
    'nz':350,  'dz':0.010,    'oz':0,     'lz':'label2=1 unit2=km',                # CC axis 1
    'nt':400,  'dt':0.005,    'ot':1.25,  'lt':'label1="\F10 t\F3 " unit1="s"',    # RC axis 1
    'nx':360,  'dx':0.020,    'ox':0,     'lx':'label2=x unit2=km',                # CC axis 2
    'ng':360,  'dg':0.250,    'og':-45,   'lg':'label2="\F10 g\F3 " unit2="\^o\_"',# RC axis 2
    'nT':1600, 'dT':0.004,    'oT':0,      'kT':800,    # time
    'tmx':10,'eps':0.0000001, 'verb':'y','nrmax':1,
    'ow':1, 'incore':'y',
    'spx':175
    }

# compute parameters
rwezo.param(par)

# velocity
Flow('vv',None,
     '''
     spike
     n1=%(nz)d o1=%(oz)g d1=%(dz)g
     n2=%(nx)d o2=%(ox)g d2=%(dx)g |
     math output=2-0.05*x1-0.05*x2 |
     put label1=z label2=x
     ''' % par)
Flow('vb',None,
     '''
     spike nsp=1 mag=-0.5
     n1=%(nz)d o1=%(oz)g d1=%(dz)g k1=145 l1=155
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=145 l2=155 |
     smooth rect1=21 rect2=11 |
     scale axis=123
     ''' % par)

Flow('vel','vv vb',
     '''
     math
     a=${SOURCES[0]}
     b=${SOURCES[1]}
     output="a+b"
     ''')
Plot('vel',rwezo.cgrey('allpos=y bias=0.7 pclip=100',par))

# smooth velocity for HWT
Flow('vsm','vv','smooth')

# ------------------------------------------------------------
# wavefronts (by HWT)
Flow('hwt','vsm',
     '''
     hwt2d verb=n
     xsou=3.5 zsou=-2.5
     nt=1000 ot=0 dt=%(dt)g
     ng=%(ng)d og=%(og)g dg=%(dg)g
     ''' % par)
# coordinate system: rays(g,t)
Flow('cos','hwt','window min2=%(ot)g n2=%(nt)d' % par)

# coordinate system plot
rwezo.cos('cos',10,20,par)
Result('cos','vel cos','Overlay')

# slowness
rwezo.slow('sloCC','sloRC','vel','cos',par)
Result('sloRC','transp |'
       + rwezo.rgrey('pclip=100 allpos=y bias=0.51',par))

# ------------------------------------------------------------
# coordinate system coefficients (A,B,M=mask) and references (A,B)
rwezo.abm('abmRC','abrRC','sloRC','cos',par)
rwezo.abmplot('abmRC',par)

# ------------------------------------------------------------
# time data CC: (t,x)
Flow('datCC',None,
     '''
     spike nsp=1 mag=1
     n1=%(nT)d o1=%(oT)g d1=%(dT)g k1=%(kT)d
     n2=%(nx)d o2=%(ox)g d2=%(dx)g k2=%(spx)d l2=%(spx)d |
     ricker1 frequency=10 |
     smooth rect2=1 |
     put label1=t label2=x
     ''' % par )
Result('datCC','grey pclip=100 wanttitle=n')

# ------------------------------------------------------------
# frequency data RC: (g,w)
rwezo.frq('frqRC','frqCC','datCC','cos',par)

# ------------------------------------------------------------
# WEM image CC: (z,x)
zomig.image('imgCC','sloCC','frqCC',par)
Plot  ('imgCC','window | transp |' + rwezo.cgrey('pclip=99',par))
Result('imgCC',['imgCC','cos'],'Overlay')

# ------------------------------------------------------------
# RWE image
rwezo.mig('migCC','migRC','frqRC','abmRC','abrRC','cos',par)
rwezo.mod('modCC','modRC','migRC','abmRC','abrRC','cos',par)

# ------------------------------------------------------------
# PLOTS
rwezo.plots(par)

End()
