from rsfproj import *
import sys, math
sys.path.append('../../Scons')
import zomig,sgmig

# ------------------------------------------------------------
# PLOTTING
# ------------------------------------------------------------
def igrey(custom):
    return '''
    grey  labelrot=n wantaxis=y wanttitle=y title=""
    pclip=100
    min2=-1500 max2=1500
    %s 
    ''' % (custom)
def igraph(custom):
    return '''
    graph labelrot=n wantaxis=n wanttitle=n title=""
    yreverse=y wantaxis=n plotfat=10 plotcol=1 %s
    ''' % (custom)
def reflector(formula,par):
    return '''
    math n1=%d o1=%g d1=%g n2=1 output="%s"
    ''' % (par['nx']/2,par['ox'],par['dx'],formula)
# ------------------------------------------------------------
par = {
    'nz':200,  'dz':5.0,  'oz':0,
    'nx':500,  'dx':10,   'ox':-2500,
    'nt':1000, 'dt':0.004,'ot':0, 'kt':201,
#
    'nw':256, 'ow':1.0, 'jw':10, 'dw':0.05,
    'nw':30, 'ow':2.0, 'jw':3,
    'nw':1,  'ow':5.0,
#    
    'verb':'y','eps':0.01,'nrmax':1,'dtmax':0.00005,
    'tmx':32,'tmy':0,'pmx':32,'pmy':0,
    'misc':'incore=n'
    }
par['zmin']=par['oz']
par['zmax']=par['oz'] + (par['nz']-1) * par['dz']
par['xmin']=par['ox']
par['xmax']=par['ox'] + (par['nx']-1) * par['dx']

# ------------------------------------------------------------
# DATA
# ------------------------------------------------------------
Flow('dat',None,
     '''
     spike nsp=1 mag=1 
     n1=%(nt)d d1=%(dt)g o1=0      k1=200
     n2=%(nx)d d2=%(dx)g o2=%(ox)g k2=100 l2=400 |
     smooth rect2=101 | 
     ricker1 frequency=10 |
     put label1=t label2=x label3=y 
     ''' % par )    
Result('dat','dat',igrey(''))
zomig.wflds('wfl','dat',par)

# ------------------------------------------------------------
# VELOCITY/SLOWNESS
# ------------------------------------------------------------
Flow('vel',None,
     '''
     spike nsp=1 mag=2000
     n1=%(nz)d d1=%(dz)g o1=0 |
     spray axis=2 n=%(nx)d o=%(ox)g d=%(dx)g |
     put label1=z label2=x label3=y 
     ''' % par )    
Result('vel','vel',igrey(''))
Flow('slo','vel',
     '''
     transp |
     math "output=1/input" |
     spray axis=2 n=1 |
     put label2=y
     ''' % par )

Flow('dsl',None,
     '''
     spike nsp=1 mag=0.00005,0.0002,0.0001
     n1=%(nz)d d1=%(dz)g o1=%(oz)g k1=080,150,050 l1=120,151,051
     n2=%(nx)d d2=%(dx)g o2=%(ox)g k2=230,295,495 l2=270,305,505 |
     put label1=z label2=x label3=y |
     smooth rect1=1 rect2=1 |
     transp plane=12 |
     transp plane=23 |
     rtoc
     ''' % par )

# ------------------------------------------------------------
# IMAGE
# ------------------------------------------------------------
zomig.image('img','slo','wfl',par)
Result('img','img','window | transp |' + igrey(''))

# ------------------------------------------------------------
# WAVEFIELD
# ------------------------------------------------------------
zomig.Awftwo('www','wfl','slo',par)

# ------------------------------------------------------------
# forward WEMVA
# ------------------------------------------------------------

zomig.s2i('dsl','dim','www','slo',par)
zomig.i2s('dim','bsl','www','slo',par)

Plot('www','www','window | real | transp |'+ igrey('title="www"'))
Plot('dim','dim','window | real | transp |'+ igrey('title="dim"'))
Plot('img','img','window |        transp |'+ igrey('title="img"'))

Plot('dsl','dsl','window | real | transp |'+ igrey('title="dsl" color=F'))
Plot('bsl','bsl','window | real | transp |'+ igrey('title="bsl" color=F'))

Result('scat','img dsl dim bsl','OverUnderAniso')
#Result('scat','img dim','Movie')

End()
