from rsfproj import *

# Fetch Data set from Repository located at pluto

Fetch('pluto.velo.hh','pluto')
Fetch('int_depth_vp.sgy','pluto')
Fetch('P15VPint_25f_padded.SEGY','pluto')

# Convert native format to RSF format
Flow('velo','pluto.velo.hh',
     '''
     dd form=native |
     put label1=z unit1=km d1=0.025 o1=0
         label2=x unit2=km d2=0.025 o2=-34.875 |
     math "output=input/1000"
     ''')

Flow('vp','int_depth_vp.sgy',
	'''
	segyread tape=$SOURCE
	''')

Flow('vpInt','P15VPint_25f_padded.SEGY',
	'''
	segyread tape=$SOURCE
	''')


# inVelo is a text file containing the header info for velo.rsf. 
Flow('inVelo','velo','in $SOURCE')

# Plot images
Result('velo','grey color=j allpos=y title=Velocity')
Result('vp','grey color=j title=Int\ Depth\ vp')
Result('vpInt','grey color=j title=VP\ Int')
End()
