from rsf.tex import *

End(options='manuscript', use='''amsmath,amsfonts,amssymb,hyperref,url,tikz''',
	include='''
%\usetikzlibrary{decorations.pathreplacing} 
%\usetikzlibrary{shapes,arrows,chains}
	''',
	color='marm vsnap')
