from rsfproj import *

for case in range(2):
    sep = 'shot%s.H' % ('','.difftrue')[case]
    Fetch(sep,'antoine')
    rsf = ('shot','mult')[case]
    Flow(rsf,sep,'dd form=native | put label1=Time label2="Trace Number" unit1=s')
    Plot(rsf,'tpow tpow=2 | grey title="(%s)" clip=1 labelsz=11 crowd=0.78' % ('ab'[case]))

Result('inter','shot mult','SideBySideAniso')

End()
