from rsf.proj import *
import dix

for case in ('agc','npk','agc2'):
    rsf = 'bei-%s.rsf' % case
    Fetch(rsf,'midpts')
    Flow(case,rsf,'dd form=native')

dv=0.0125   # velocity step
nv=96       # continuation steps
v0=1.3      # minimum velocity

dix.dix('bei',           # data name
        'agc',           # migrated image
        'npk',           # migration velocity
        'agc2',          # semlance slice
        v0=1.3,          # minimum velocity
        vm=v0+0.5*nv*dv, # median velocity
        nx=250,          # lateral dimension
        dx=0.0335,       # midpoint sampling
        x0=7.705,        # lateral origin
        units='km',      # lateral units
        rect1=15,        # vertical smoothing
        rect2=15)        # lateral  smoothing

End()
