from rsf.proj import *
from math import pi

# basic parameters
t0 = 0.2                                # time shift for Ricker wavelet
fm = 20.0                               # main frequency of Ricker wavelet

# calculate trace (time-shifted Ricker wavelet)
Flow('sig',None,
    f'''
    math d1=0.001 n1=401 label1=Time unit1=s 
    output="(1-2*{pi}^2*{fm}^2*(x1-{t0})^2)*exp(-{pi}^2*{fm}^2*(x1-{t0})^2)"
    ''')
Result('sig','graph label2=amplitude grid=y plotfat=5 title="Ricker wavelet"')

# FFT
Flow('spec','sig','rtoc | fft3 axis=1')

# amplitude spectrum
Flow('amp','spec',
     '''
     window min1=-100 max1=100 | math output="abs(input)" | real
     ''')
Result('amp','graph title="Amplitude" grid=y plotfat=5')

# & stands for atan2
Flow('ang','spec',
     '''
     window min1=-100 max1=100 | math output="imag(input)&real(input)" | real
     ''')

Flow('p','amp ang','math a=${SOURCES[1]} output="input*sin(a)" ')
Flow('q','amp ang','math a=${SOURCES[1]} output="input*cos(a)" ')
Flow('pq','p q','cat axis=2 ${SOURCES[1]}')

Result('spec','pq','matplotlib plot3D')

End()
