from rsf.tex import *


End(lclass='geophysics',use='''amssymb,hyperref,
          amsthm,amsmath,amsbsy,subfigure,latexsym,graphicx,
          color,lineno,setspace,algorithmic,algorithm,
          natbib,multirow,rotating''')



