from rsfproj import *

private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

Fetch('elf0.H','elf',private)

Flow('elf','elf0.H',
     '''
     dd form=native | cut n3=1 n2=1 n1=300 f3=663 f2=67
     ''')

Flow('gath','elf','window n3=1 f3=500 n2=131 | bandpass flo=5 fhi=60 | put unit1=s unit2=m')
Plot('gath','grey title=Input')

Flow('dip','gath','dip rect1=10 rect2=10 pmin=0')
Plot('dip','grey unit1=s unit2=m  color=j title=Slope allpos=y scalebar=y')

Flow('rad','gath','radon adj=y inv=n p0=0 dp=0.00001 np=151')
Plot('rad','grey title="Radon Transform" label2=Slope unit2=s/m')

Result('rad','gath rad','SideBySideAniso')

Flow('prad dip2','gath dip',
     'pradon adj=y inv=n p0=0 dp=0.00001 np=151 dip2=${TARGETS[1]} dip=${SOURCES[1]} verb=y')
Plot('prad','grey title="Phase-Space Radon Transform" label2=Slope unit2=s/m')

Result('prad','gath prad','SideBySideAniso')

End()
