from rsf.proj import *
import math

# get the stack created using seismic unix
Fetch('final_stack.rsf','teapot',server='http://s3.amazonaws.com',top='')
Result('sustack','final_stack','grey title="su stack"')

Fetch('npr3_gathers.sgy','teapot',server='http://s3.amazonaws.com',top='')

# ohh my!  Coordinates all need to be divided by 1000 to be in ft.
# this apply to sx, sy ,cdpx, cdpy
 
Flow(['npr3_gathers.rsf','npr3_gathers_hdr.rsf', 
      'npr3_gathers.thdr','npr3_gathers.bhdr'],
     'npr3_gathers.sgy',
     '''
     sfsegyread tfile=${TARGETS[1]} 
     hfile=${TARGETS[2]}  bfile=${TARGETS[3]} 
     ''')

Flow('gathersheaderattr.txt',
     'npr3_gathers_hdr.rsf',
     'sfheaderattr >temp; cat temp; cat temp ')

Fetch('npr3_field.sgy','teapot',server='http://s3.amazonaws.com',top='')

Flow(['npr3_field.rsf','npr3_field_hdr.rsf',
      'npr3_field.thdr','npr3_field.bhdr'],
     'npr3_field.sgy',
     '''
     sfsegyread tfile=${TARGETS[1]} 
     hfile=${TARGETS[2]}  bfile=${TARGETS[3]} 
     ''')

Flow('fieldheaderattr.txt',
     'npr3_field_hdr.rsf',
     'sfheaderattr >temp; cat temp; cat temp ')

pdfread = WhereIs('acroread') or WhereIs('kpdf') or WhereIs('evince') or \
    WhereIs('xpdf') or WhereIs('gv') or WhereIs('open')
if pdfread:
    # download and view the survey notes:
    Fetch('3dload_Teapot_Dome_3D.pdf','teapot',
          server='http://s3.amazonaws.com',top='')
    Flow('3dload','3dload_Teapot_Dome_3D.pdf',
           pdfread + ' $SOURCE',stdin=0, stdout=0)
    Fetch('teapot_processing.pdf','teapot',
          server='http://s3.amazonaws.com',top='')
    Flow('processing','teapot_processing.pdf',
           pdfread + ' $SOURCE',stdin=0,stdout=0)
    
End()
