###########################################################################
# STANDARD HEADER
###########################################################################
import sys, os

root = os.environ.get('RSFROOT')
sys.path.append(os.path.join(root,'lib'))

from rsfproj import *
from rsfrecipe import Galilee, Helderiv
##########################################################################
Book()

def plot(title):
    return '''
    grey pclip=94 title="%s" yreverse=n transp=n
    label2="north-south (km)" label1="west-east (km)"
    ''' % title

Galilee('mesh')

Flow('fill','mesh','lapfill grad=y niter=20')
Plot('ruf2','fill','igrad | ' + plot('Filled and d/dx'))

Helderiv('held','fill',na=128,eps=0.00001)
Plot('held','held',plot('Filled and helix derivative'))

Combine('helgal','ruf2 held','SideBySideAniso',result=1)

###########################################################################
End()
