from rsfproj import *

from beg import server
# replace with your own data server

for case in ('a1','a2','b1'):
    segy = 'salt-%s.segy' % case
    Fetch(segy,'segsalt',server)

    Flow([case,'t'+case,case+'.asc',case+'.bin'],segy,
         '''
         segyread tfile=${TARGETS[1]} hfile=${TARGETS[2]} bfile=${TARGETS[3]}
         ''') 

Flow('a1s','ta1',
     '''
     window n1=1 f1=22 n2=49116 | dd type=float | math output="(input-1020)/80"
     ''')
Flow('a1x','ta1 a1s',
     '''
     window n1=1 f1=23 n2=49116 | dd type=float |
     math output="(input-7500)/80"
     ''')
Flow('a1y','ta1 a1s',
     '''
     window n1=1 f1=24 n2=49116 | dd type=float |
     math s=${SOURCES[1]} output="(input-(1020+s*80))/40" 
     ''')
Flow('a1head','a1s a1y a1x',
     'cat axis=2 ${SOURCES[1:3]} | transp | dd type=int')

Flow('a1data','a1 a1head',
     '''
     window n2=49116 |
     intbin3 head=${SOURCES[1]} xkey=0 ykey=1 zkey=2 |
     put
     o2=1020  d2=80 label2=sy
     o3=-2720 d3=40 label3=hy
     o4=-200  d4=80 label4=hx     
     ''')

Result('a1near','a1data',
       '''
       window n3=1 f3=-1 n4=1 f4=3 |
       tpow tpow=1 |
       grey title="A1 Near Offset"
       ''')

End()
