from rsf.proj import *

sys.path.append('..')
import gradient

gradient.zero_offset('zodata')

Result('zodata','grey title="Zero-Offset" ')

par = gradient.par

Flow('veloc','zodata',
     '''
     window n1=1 | spray axis=1 n=501 o=0 d=0.01 label=Depth unit=km | 
     math output="%(v0)g+%(gradx)g*x2+%(gradz)g*x1" | 
     put label=Velocity unit=km/s
     ''' % par)

Result('veloc','grey color=j allpos=y bias=%(v0)g title="Velocity Model" scalebar=y barreverse=y' % par)

# FFD
Flow('vel2','veloc',
     'transp | scale dscale=0.5')

# Zero-offset migration
Flow('zomig','zodata vel2',
     '''
     reverse which=1 |
     transp |
     ffd0 nbt=50 nbb=49 nbl=50 nbr=49
     vel=${SOURCES[1]}
     ''')

Result('zomig','window min1=2.5 max1=7.5 | grey title="Zero-Offset Migration" unit2=km transp=n')

# Impulse response
#Flow('impulse','zodata','spike k1=751 k2=176 | smooth rect1=2 rect2=2 repeat=2')
Flow('impulse','zodata','spike k1=751 k2=176 | smooth rect1=6 rect2=6 repeat=3')

Flow('impres','impulse vel2',
     '''
     reverse which=1 |
     transp |
     ffd0 nbt=50 nbb=49 nbl=50 nbr=49
     vel=${SOURCES[1]}
     ''')

Plot('impres','grey title="Impulse Response" unit2=km transp=n')

Plot('theory','veloc',
     '''
     scale dscale=0.5 | eikonal yshot=5 | 
     contour nc=1 c0=1.5 wantaxis=n wanttitle=n plotcol=3 plotfat=3
     ''')

Result('impres','impres theory','Overlay')
End()
