###########################################################################
import sys, os

root = os.environ.get('RSFROOT')
sys.path.append(os.path.join(root,'lib'))

from rsfproj import *

###########################################################################
set_resdir('../Fig')

grey = '''
grey color=j allpos=y screenht=6 screenwd=12
wanttitle=n label1="Depth (km)" label2="Lateral (km)"
'''
rays =  '''
cell2 nr=1000 nt=4000 yshot=0 |
plotrays par=cgrad.rsf screenht=6 screenwd=12 jr=5 plotcol=0
'''

Flow('const',None,'spike n1=601 d1=0.01 n2=1201 d2=0.01 o2=0')
Plot('const','const',grey)
Plot('cell2','const',rays)
Combine('straight','const cell2','Overlay',result=1)

Flow('cgrad',None,
          '''spike n1=601 d1=0.01 |
          headermath output="1/sqrt(1-N*0.00165)" |
          spray n2=1201 d2=0.01 o2=0''')
Plot('cgrad','cgrad',grey)
Plot('ccell2','cgrad',rays)
Combine('parab','cgrad ccell2','Overlay',result=1)

###########################################################################

End()
