from rsf.proj import *

#Velocity model:
#Flow('Fvel', None, 'spike mag=1500,3000 nsp=2 k1=1,101 l1=100,200 d1=4 d2=4 label1=z label2=x n1#=200 n2=200 o1=2 o2=2 unit1=m unit2=m')
Flow('Fvel','../fetch/vp.rsf', 
	'''
     	sfput unit1="m" unit2="m" d1=10 d2=20 label1=Depth label2=Distance | window max2=9000
     	''')
Result('Fvel','grey color=j scalebar=y')

#Density model:
Flow('Fden','Fvel', 'math output=1')

#Source wavelet:
Flow('Fwav', None, 'spike nsp=1 n1=12000 d1=0.0005 k1=400 | ricker1 frequency=10 | transp')
Result('Fwav',''' transp | sfwiggle 
              ''') 


# experiment setup
par = {
    'nx':400, 'ox':200, 'dx':20, 'lx':'x','ux':'m',
    }

# receiver positions
Flow('r_',None,'math n1=%(nx)d d1=%(dx)g o1=%(ox)g output=0' % par)
Flow('xr','r_','math output="x1"')
Flow('zr','xr','math output=20')

Flow('rr',['xr','zr'],'''cat axis=2 space=n
     ${SOURCES[0]} ${SOURCES[1]} | transp
     ''', stdin=0)

# source positions
#Flow('xs','s_','math output="x1"')
Flow('xs',None,'spike mag=3000 nsp=1 k1=1 n1=1')
Flow('zs','xs','math output=20')

Flow('ss',['xs','zs'],'''
     cat axis=2 space=n
     ${SOURCES[0]} ${SOURCES[1]} | transp
     ''', stdin=0)

#Creating data at specified receiver + saving full wavefield every 16th step: 
Flow(['Fdat', 'Fwfl'], ['Fwav', 'Fvel', 'Fden', 'ss', 'rr'], 'awefd2d  vel=${SOURCES[1]} sou=${SOURCES[3]} rec=${SOURCES[4]} wfl=${TARGETS[1]} den=${SOURCES[2]} verb=y free=y expl=y snap=y dabc=y jdata=16 jsnap=64') 


#View the wavefield movie:
Result('movie', 'Fwfl', 'grey gainpanel=a pclip=99 color=j scalebar=y')
# View a wavefield snapshot:
Result('snap', 'Fwfl', 'window f3=40 n3=1 | grey pclip=99 color=j title="snapshot at t=1.280s"')
#View the data recorded at receiver:
Result('data', 'Fdat', 'window | grey title="Data recorded at receiver" unit2= label2=amplitude')

End()
