/* This file is automatically generated. DO NOT EDIT! */

#ifndef _vfsacrsnh_lib_h
#define _vfsacrsnh_lib_h


#define Beta_MAX 1
#define Beta_MIN -1
#define Rnip_MAX 5
#define Rnip_MIN 0
#define Rn_MAX 5
#define Rn_MIN 0
#define hMAX 50
#define mMAX 50
#define ITMAX 5000
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <rsf.h>


float signal(float s);
/*< Signal function >*/


float getRandomNumberBetween0and1();
/*< Function to get a random number between 0 and 1 >*/


float getVfsaIterationTemperature(int iteration,float dampingFactor,float inicialTemperature);
/*< Temperature function for VFSA algorithm >*/


void disturbParameters(float temperature, float* disturbedParameter, float* parameter);
/*< Perturbar os parâmetros da iteração anterior >*/


float nonHyperbolicCRSapp(float m, float h, float t0, float v0, float RN, float RNIP, float BETA);
/*< Non hyperbolic CRS approximation (FOMEL; KAZINNIK, 2013) >*/


float semblance(float m0, float dm, float om, float oh, float dh, float dt, int nt,float t0, float v0,float RN, float RNIP, float BETA, float*** t);
/*< Semblance: Non Hyperbolic CRS approximation with data >*/

#endif
