from rsf.proj import *


Flow('vel',None,
     	'''
     	math output=2.0 n1=200 n2=200 d1=0.005 d2=0.005
     	label1=x1 unit1=km label2=x2 unit2=km 
     	''')


#Flow('wav','vel','Testfd2d nb=30 nt=1000 dt=0.001')

Flow('wav','vel','sfTestspml nb=30 nt=1000 dt=0.001')



Plot('wav',
     '''
     window f1=0 f2=0 n1=200 n2=200 | 
     grey gainpanel=all title=Wave scalebar=y color=j 
     ''',view=1)

time=0.35
# Wavefield snapshot
Result('snap','wav',
     '''
     window f1=0 f2=0 n1=200 n2=200 n3=1 min3=%g |
     grey title="Wave Snapshot at %g s"
     label1=Depth unit1=km label2=Lateral unit2=km 
     scalebar=y color=j 
     ''' % (time,time))



End()
