Import('env pkgdir')

import os

py = '__init__.py'
pyc = str(py)+'c'
env.RSF_Pycompile(pyc,py)
env.Install(os.path.join(pkgdir,'gallery'),[py,pyc])

for py in Glob('[a-z]*/[_a-z]*.py'):
    pyc = str(py)+'c'
    env.RSF_Pycompile(pyc,py)	
    env.Install(os.path.join(pkgdir,'gallery'),[py,pyc])

