from rsfproj import *
import os, string

top = os.environ.get('RSFROOT')
libdir = os.path.join(top,'lib')

path = {}
for key in ('PYTHON','LD_LIBRARY_'):
    oldpath = os.environ.get(key+'PATH')
    if oldpath:
        path[key] = string.join([libdir,oldpath],':')
    else:
        path[key] = libdir

Flow('test.attr','clip.py',
     '''
     spike n1=1000 n2=100 n3=10 nsp=1 k1=500 | 
     PYTHONPATH=%(PYTHON)s LD_LIBRARY_PATH=%(LD_LIBRARY_)s
     ./$SOURCE clip=0.5 | attr
     ''' % path,stdin=0)


        
