from rsf.proj import *

Flow('vel',None,
     	'''
     	math output=1000 n1=301 n2=301 d1=1 d2=1
     	label1=x1 unit1=m label2=x2 unit2=m 
     	''')
Flow('rho','vel','math output=1000')
Flow('eta','vel','math output=10000000')

Flow('wav','vel rho eta',
	'''
	sfmaxwell_cpml2 rho=${SOURCES[1]} eta=${SOURCES[2]} order1=y
	nb=30 nt=1200 dt=0.0002 verb=y fm=30
	''')
Result('wav',
	'''	
	grey  title="Mexwell Attenuation Model" gainpanel=all
	color=i screenratio=1
	''')
Result('snapshot200','wav',
	'''
	sfwindow n3=1 f3=200| grey  title="kt=200" 
	gainpanel=all 	color=i scalebar=y
	''')

Result('snapshot400','wav',
	'''
	sfwindow n3=1 f3=400| grey  title="kt=400" 
	gainpanel=all 	color=i scalebar=y
	''')
Result('snapshot600','wav',
	'''
	sfwindow n3=1 f3=600| grey  title="kt=600" 
	gainpanel=all 	color=i scalebar=y
	''')
Result('snapshot800','wav',
	'''
	sfwindow n3=1 f3=800| grey  title="kt=800" 
	gainpanel=all 	color=i scalebar=y
	''')
Result('snapshot1000','wav',
	'''
	sfwindow n3=1 f3=1000| grey  title="kt=1000" 
	gainpanel=all 	color=i scalebar=y
	''')
Result('snapshot1200','wav',
	'''
	sfwindow n3=1 f3=1199| grey  title="kt=1200" 
	gainpanel=all 	color=i scalebar=y
	''')
End()
