from rsf.proj import *

Flow('vel',None,
     	'''
     	math output=1000 n1=301 n2=301 d1=1 d2=1
     	label1=x1 unit1=m label2=x2 unit2=m 
     	''')
Flow('rho','vel','math output=1000')
Flow('eta','vel','math output=10000000')

Flow('wav','vel rho eta',
	'''
	sfmaxwell_cpml2 rho=${SOURCES[1]} eta=${SOURCES[2]} order1=y
	nb=30 nt=500 dt=0.0005 verb=y fm=30
	''')
Result('wav',
	'''	
	grey  title="Mexwell Attenuation Model" gainpanel=all
	color=i screenratio=1
	''')

Flow('wav1 wav2','vel rho eta',
	'''
	sfmaxwell_cpml2_backward rho=${SOURCES[1]} eta=${SOURCES[2]}
	back=${TARGETS[1]} attenuating=n
	nb=30 nt=500 dt=0.0005 verb=y fm=30
	''')
Result('wav1',
	'''	
	grey  title="Mexwell Attenuation Model" gainpanel=all
	color=i screenratio=1
	''')
Result('wav2',
	'''	
	grey  title="Mexwell Attenuation Model" gainpanel=all
	color=i screenratio=1
	''')


End()
