from rsfbook import *
from rsftex import *

Papers(copyr='Colorado School of Mines',group='Center for Wave Phenomena',
       authors={'rwesalt':'Paul Sava'},line='Example Report, March 2007',
       fig=('rwesalt/sigsbee','compCC1-F15','width=\\textwidth'))

for file in ('toc','tpg'):
    Paper(file,lclass='georeport')

End(lclass='georeport')

