from rsf.book import *

report = (('2006',
           '''
           geo2006TimeShiftImagingCondition
           jse2006RWEImagingOverturningReflections
           seg2006ConvertedWavesTSIC
           '''),
          ('2007',
           '''
           geo2007StereographicImagingCondition
           gpr2007RWEHighOrderKernels
           '''),
          ('2008',
           '''
	   geo2008NumericWEMVAoperators
	   geo2008InterferometricImagingCondition
           geo2008IsotropicAngleDomainElasticRTM
 	   '''),
          ('2009',
           '''
           geo2009TTIModeSeparation
           geo2009VTIModeSeparation
 	   '''),
          )

Papers(papers=report,
       copyr='Colorado School of Mines',group='Center for Wave Phenomena',
       authors={'seg2006ConvertedWavesTSIC': 'Paul Sava and Sergey Fomel',
                'jse2006RWEImagingOverturningReflections':'Paul Sava',
                'gpr2007RWEHighOrderKernels':'Paul Sava and Sergey Fomel',
                'geo2007StereographicImagingCondition':'Paul Sava',
                'geo2008NumericWEMVAoperators':'Paul Sava and Ioan Vlad',
                'geo2008InterferometricImagingCondition':'Paul Sava and Oleg Poliannikov',
                'geo2008IsotropicAngleDomainElasticRTM': 'Jia Yan and Paul Sava
'},
       line='Example Report, November 2008',
       fig=('jse2006RWEImagingOverturningReflections/sigsbee',
            'compCC1-F15','width=\\textwidth'))

End(use='ulem,color,setspace,amssymb,mathrsfs',options='twocolumn')

