from rsfproj import *

Flow('impuls',None,
     '''
     spike
     n1=128 d1=0.008 k1=64
     n2=128 d2=0.016 k2=64
     n3=130 d3=0.016 k3=64 |
     bandpass flo=5 fhi=20
     ''')
Flow('freq','impuls','fft1 | transp plane=13')
Flow('freq1','freq','window n3=1 min3=5')
Flow('slowness',None,
     '''
     spike mag=0.256
     n1=130 d1=0.016
     n2=128 d2=0.016
     n3=128 d3=0.016
     ''')
Flow('image','freq slowness','sstep2 slowness=${SOURCES[1]} readwrite=y verb=y eps=1')
Flow('image1','freq1 slowness','sstep2 slowness=${SOURCES[1]} readwrite=y eps=0.1')

Result('image',
       '''
       byte gainpanel=a pclip=100 |
       transp plane=13 |
       grey3 wantaxis=n wanttitle=n frame1=32 frame2=64 frame3=64
       screenratio=1
       ''') 

Flow('model','impuls slowness',
     'transp plane=13 | sstep2 slowness=${SOURCES[1]} inv=y verb=y eps=1 nw=65 dw=0.976562')

Result('model',
       '''
       transp plane=13 |
       fft1 inv=y |
       byte gainpanel=a pclip=100 |
       grey3 wantaxis=n wanttitle=n frame1=48 frame2=64 frame3=64
       screenratio=1
       ''')

End()
