from rsf.proj import *

sys.path.append('..')
import gradient

gradient.zero_offset('zodata')

Result('zodata','grey title="Zero-Offset" ')

par = gradient.par

Flow('veloc','zodata',
     '''
     window n1=1 | spray axis=1 n=501 o=0 d=0.01 label=Depth unit=km | 
     math output="%(v0)g+%(gradx)g*x2+%(gradz)g*x1" | 
     put label=Velocity unit=km/s
     ''' % par)

Result('veloc','grey color=j allpos=y bias=%(v0)g title="Velocity Model" scalebar=y barreverse=y' % par)

# Fourier transform and transpose

fmax = 50 # maximum frequency
nf = 206  # number of frequencies

Flow('fft','zodata',
     'fft1 | window max1=%g | transp plane=12 | transp plane=23' % fmax)

# From velocity to slowness
Flow('slowness','veloc','transp | transp plane=23 | math output=1/input')

# Extended split-step migration
Flow('mig','fft slowness',
     '''
     zomig3 ompnth=1 mode=m --readwrite=y verb=y
     nrmax=30 slo=${SOURCES[1]} |
     window | transp
     ''',split=[3,nf,[0]],reduce='add')

Result('mig',
       '''
       window min2=2.5 max2=7.5 |
       grey title=Migration 
       label2=Depth    unit2=km 
       label1=Distance unit1=km
       ''')

End()
