from rsf.suproj import *

Fetch('seismic.segy','viking',server=os.environ.get('RSF_DATASERVER','http://www.ahay.org'))

# Convert to SU
Flow('seismic','seismic.segy',
     'segyread endian=%d tape=$SOURCE verbose=1 | segyclean' % (not little_endian()),
     stdin=0)

# First 1000 traces
Result('first','seismic',
       'suwind key=tracl count=1000 | suximage perc=99')

# Shot gathers movie
Result('shots','seismic',
       'suwind count=12000 skip=0 | suxmovie n2=1200 loop=1 perc=99 title="Frame %g" ')

# Select a shot gather
Flow('shot200','seismic','suwind key=ep min=200 max=200')

Result('shot200i','shot200','suximage perc=99 title="shot ep=200" ')
Result('shot200w','shot200','suxwigb  perc=99 title="shot ep=200" ')

# Source-receiver positions chart
Result('chart','seismic',
       '''
       suchart | xgraph n=120120 linewidth=0
       label1=sx label2=gx marksize=2 mark=8
       title="sx gx chart"
       ''')

End()
