from rsf.proj import *

mpicc = WhereIs('mpicc')
mpirun = WhereIs('mpirun')

if not mpicc or not mpirun:
    sys.stderr.write("\nNo MPI.\n")
    sys.exit(1)

np = ARGUMENTS.get('NP','2')


prog = Program('mpihello.c',CC=mpicc)
exe = str(prog[0])

Flow('a',None,'math n1=512 n2=256 output="x1+x2"')
Flow('b',None,'math n1=512 n2=256 output="-x1-x2"')

Flow('c','a %s b' % exe,
     '''
     %s -np %s ./${SOURCES[1]} input=${SOURCES[0]} b=${SOURCES[2]}
     ''' % (mpirun,np),stdin=0)

End()

