	hdr[1].offs = 
		offsetof(segy, tracr);
	hdr[2].offs = 
		offsetof(segy, fldr);
	hdr[3].offs = 
		offsetof(segy, tracf);
	hdr[4].offs = 
		offsetof(segy, ep);
	hdr[5].offs = 
		offsetof(segy, cdp);
	hdr[6].offs = 
		offsetof(segy, cdpt);
	hdr[7].offs = 
		offsetof(segy, trid);
	hdr[8].offs = 
		offsetof(segy, nvs);
	hdr[9].offs = 
		offsetof(segy, nhs);
	hdr[10].offs = 
		offsetof(segy, duse);
	hdr[11].offs = 
		offsetof(segy, offset);
	hdr[12].offs = 
		offsetof(segy, gelev);
	hdr[13].offs = 
		offsetof(segy, selev);
	hdr[14].offs = 
		offsetof(segy, sdepth);
	hdr[15].offs = 
		offsetof(segy, gdel);
	hdr[16].offs = 
		offsetof(segy, sdel);
	hdr[17].offs = 
		offsetof(segy, swdep);
	hdr[18].offs = 
		offsetof(segy, gwdep);
	hdr[19].offs = 
		offsetof(segy, scalel);
	hdr[20].offs = 
		offsetof(segy, scalco);
	hdr[21].offs = 
		offsetof(segy, sx);
	hdr[22].offs = 
		offsetof(segy, sy);
	hdr[23].offs = 
		offsetof(segy, gx);
	hdr[24].offs = 
		offsetof(segy, gy);
	hdr[25].offs = 
		offsetof(segy, counit);
	hdr[26].offs = 
		offsetof(segy, wevel);
	hdr[27].offs = 
		offsetof(segy, swevel);
	hdr[28].offs = 
		offsetof(segy, sut);
	hdr[29].offs = 
		offsetof(segy, gut);
	hdr[30].offs = 
		offsetof(segy, sstat);
	hdr[31].offs = 
		offsetof(segy, gstat);
	hdr[32].offs = 
		offsetof(segy, tstat);
	hdr[33].offs = 
		offsetof(segy, laga);
	hdr[34].offs = 
		offsetof(segy, lagb);
	hdr[35].offs = 
		offsetof(segy, delrt);
	hdr[36].offs = 
		offsetof(segy, muts);
	hdr[37].offs = 
		offsetof(segy, mute);
	hdr[38].offs = 
		offsetof(segy, ns);
	hdr[39].offs = 
		offsetof(segy, dt);
	hdr[40].offs = 
		offsetof(segy, gain);
	hdr[41].offs = 
		offsetof(segy, igc);
	hdr[42].offs = 
		offsetof(segy, igi);
	hdr[43].offs = 
		offsetof(segy, corr);
	hdr[44].offs = 
		offsetof(segy, sfs);
	hdr[45].offs = 
		offsetof(segy, sfe);
	hdr[46].offs = 
		offsetof(segy, slen);
	hdr[47].offs = 
		offsetof(segy, styp);
	hdr[48].offs = 
		offsetof(segy, stas);
	hdr[49].offs = 
		offsetof(segy, stae);
	hdr[50].offs = 
		offsetof(segy, tatyp);
	hdr[51].offs = 
		offsetof(segy, afilf);
	hdr[52].offs = 
		offsetof(segy, afils);
	hdr[53].offs = 
		offsetof(segy, nofilf);
	hdr[54].offs = 
		offsetof(segy, nofils);
	hdr[55].offs = 
		offsetof(segy, lcf);
	hdr[56].offs = 
		offsetof(segy, hcf);
	hdr[57].offs = 
		offsetof(segy, lcs);
	hdr[58].offs = 
		offsetof(segy, hcs);
	hdr[59].offs = 
		offsetof(segy, year);
	hdr[60].offs = 
		offsetof(segy, day);
	hdr[61].offs = 
		offsetof(segy, hour);
	hdr[62].offs = 
		offsetof(segy, minute);
	hdr[63].offs = 
		offsetof(segy, sec);
	hdr[64].offs = 
		offsetof(segy, timbas);
	hdr[65].offs = 
		offsetof(segy, trwf);
	hdr[66].offs = 
		offsetof(segy, grnors);
	hdr[67].offs = 
		offsetof(segy, grnofr);
	hdr[68].offs = 
		offsetof(segy, grnlof);
	hdr[69].offs = 
		offsetof(segy, gaps);
	hdr[70].offs = 
		offsetof(segy, otrav);
	hdr[71].offs = 
		offsetof(segy, d1);
	hdr[72].offs = 
		offsetof(segy, f1);
	hdr[73].offs = 
		offsetof(segy, d2);
	hdr[74].offs = 
		offsetof(segy, f2);
	hdr[75].offs = 
		offsetof(segy, ungpow);
	hdr[76].offs = 
		offsetof(segy, unscale);
	hdr[77].offs = 
		offsetof(segy, ntr);
	hdr[78].offs = 
		offsetof(segy, mark);
	hdr[79].offs = 
		offsetof(segy, shortpad);
