/* This file is automatically generated. DO NOT EDIT! */

#ifndef _apfilt_h
#define _apfilt_h


void passfilter (int nw   /* size */, 
		 float p  /* slope */, 
		 float* a /* output filter [2*nw+1] */);
/*< find filter coefficients >*/


void aderfilter (int nw   /* size */, 
		 float p  /* slope */, 
		 float* a /* output filter [2*nw+1] */);
/*< find coefficients for filter derivative >*/

#endif
