/* This file is automatically generated. DO NOT EDIT! */

#ifndef _down_h
#define _down_h


void sf_down_init(float *w1);
/*< initialize >*/


void sf_down_lop (bool adj, bool add, int nx, int ny, float* xx, float* yy);
/*< linear operator >*/

#endif
