/* This file is automatically generated. DO NOT EDIT! */

#ifndef _hilbert_h
#define _hilbert_h


void hilbert_init(int nt1  /* transform length */, 
		  int n1   /* trace length */, 
		  float c1 /* filter parameter */);
/*< initialize >*/


void hilbert_free(void);
/*< free allocated storage >*/


void hilbert (const float* trace, float* trace2);
/*< transform >*/


void hilbert4 (const float* trace, float* trace2);
/*< transform - kind 4 filter >*/

#endif
