/* This file is automatically generated. DO NOT EDIT! */

#ifndef _pwd_h
#define _pwd_h


#include <rsf.h>


typedef struct Pwd *pwd; /* abstract data type */


pwd pwd_init(int n1 /* trace length */, 
	     int nw /* filter order */);
/*< initialize >*/


void pwd_close (pwd w);
/*< free allocated storage >*/


void pwd_define (bool adj        /* adjoint flag */, 
		 pwd w           /* pwd object */, 
		 const float* pp /* slope */, 
		 float* diag     /* defined diagonal */, 
		 float** offd    /* defined off-diagonal */);
/*< fill the matrix >*/


void pwd_set (bool adj   /* adjoint flag */,
	      pwd w      /* pwd object */, 
	      float* inp /* input */, 
	      float* out /* output */, 
	      float* tmp /* temporary storage */);
/*< matrix multiplication >*/

#endif
