/* This file is automatically generated. DO NOT EDIT! */

#ifndef _pwdsl_h
#define _pwdsl_h


#include <rsf.h>


void pwdsl_init(int m1, int m2       /* data dimensions */, 
		int rect1, int rect2 /* triangle radius */,
		float eps            /* regularization parameter */);
/*< initialize >*/


void pwdsl_set(float **dip /* dip field [n2][n1] */);
/*< set the local slopes for applying the linear operator >*/


void pwdsl_close(void);
/*< free allocated storage >*/


void pwdsl_lop(bool adj, bool add, int nx, int ny, float* x, float* y);
/*< linear operator >*/

#endif
