import os, sys, re, string, glob
sys.path.append('../..')
import configure

progs = '''
thr sort
'''

cpp_progs = 'clipcc'

try:  # distributed version
    Import('env')
    env = env.Copy()
    root = env.get('RSFROOT')

    libdir = os.path.join(root,'lib')
    bindir = os.path.join(root,'bin')
    incdir = os.path.join(root,'include')
    dir = string.replace(os.getcwd(),'/build','')
    src = map(os.path.basename,glob.glob(os.path.join(dir,'[a-z]*.c')))
except: # local version
    root = None
    env = Environment()
    opts=Options('../../config.py')
    configure.options(opts)
    opts.Update(env)
    env['CCFLAGS'] = string.replace(env.get('CCFLAGS',''),'-O2','-g')
    src = glob.glob('[a-z]*.c')
    env.Append(BUILDERS={'Include':configure.Header},
               SCANNERS=[configure.Include])
    SConscript('../../filt/lib/SConstruct')

env.Prepend(CPPPATH=['../../include'],
            LIBPATH=['../../filt/lib'],LIBS=['rsf'])

for source in src:
    inc = env.Include(source,prefix='')
    obj = env.StaticObject(source)
    env.Depends(obj,inc)

mains = Split(progs)
for prog in mains:
    mainc = env.Program(prog + '.c')
    if root:
        env.Install(bindir,mainc[0])

######################################################################
# C++ PROGRAMS
######################################################################

api = string.split(string.lower(env.get('API','')),',')

if 'c++' in api:
    cpp_mains = Split(cpp_progs)
    
    for prog in cpp_mains:
        # compilation
        main = env.Program(prog + '.cc',
                           LIBS=['rsf++']+env.get('LIBS',[]))
        
        if root:
            env.Install(bindir,main[0])
else:
    cpp_mains = [] 


######################################################################
# SELF-DOCUMENTATION
######################################################################
if root:
    user = os.path.basename(os.getcwd())
    main = 'sf%s.py' % user
    
    docs = map(lambda prog: env.Doc(prog+'.c'),mains) + \
           map(lambda prog: env.Doc(prog+'.cc'),cpp_mains)
    env.Depends(docs,'#/python/rsfdoc.py')

    doc = env.Command(main,docs,configure.docmerge)
    env.Install(libdir,doc)

    # clean compiled python: sfslim.pyc
    Clean(os.path.join(libdir,main),os.path.join(libdir,main+'c'))
#####################################################################

