from rsf.proj import *

###############################################################################
data='../shot/shot0.rsf'

# data has tpow squared already applied

Flow('cmp',data,'shot2cmp half=n positive=n')

End()
