/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_solve_h
#define _sf_solve_h

int solve (int pnot, int p1, int q1, int p2, int q2);
/*< compute intersection - floating point version >*/

#endif
