from rsf.proj import *

Flow('zero',None,
     'math n1=256 n2=100 o1=0, d1=0.004 o2=0 d2=10 output="0" | fft1 ')

Flow('data','zero',
     '''
     addevent nfft=256 event=0 v0=100000000 t0=0.5
     | addevent nfft=256 event=0 v0=1500 t0=0.3
     | addevent nfft=256 event=0 v0=1800 t0=0.2
     | fft1 inv=y
     ''')

Flow('pca', 'data','pca nc=1 ')

Flow('med', 'data',
     'shuffle | mflt rect1=0 rect2=4 ')

for x in ('data', 'pca', 'med'):
	Result(x,'grey title="%s"'%(x.upper()))

End()


