from rsf.proj import *

Flow('vel', None, 
	'''
	math output=2000 n1=400 n2=400 n3=400 d1=4 d2=4 d3=4
	label1=Depth label2=xline label3=iline unit1=m unit2=m unit3=m
	''')

Result('vel',
       '''
       byte allpos=y gainpanel=all |
       grey3 flat=n frame1=200 frame2=200 frame3=200 color=j 
       title="3D velocity model" point1=0.8 point2=0.8
       ''')

# replace sfgpufd3d with sfgpufbrec3d and test wavefield reconstruction in 3d
Flow('wav','vel',
	'''
	sfgpufbrec3d nt=800 kt=300 fm=20 dt=0.0005 ns=1 szbeg=200 sxbeg=200 sybeg=200
	jsz=0 jsx=10 jsy=10 
	''')


Result('wav',
       '''
       byte allpos=n gainpanel=all |
       grey3 flat=n frame1=200 frame2=200 frame3=200 color=j 
       title="shot snap of GPU fd3d" point1=0.8 point2=0.8
       ''')


End()
