from rsfproj import *

fft3 = 'fft1 | fft3 axis=2 | fft3 axis=3'
ifft3 = 'fft3 axis=3 inv=y | fft3 axis=2 inv=y | fft1 inv=y'

Flow('taper3',None,
     '''spike
     n1=128 o1=0.008 d1=0.008
     n2=128 o2=0     d2=0.016
     n3=128 o3=0     d3=0.016
     k1=64 k2=64 k3=64 nsp=1
     | %s | dipfilter v1=-1.5 v2=-1 v3=1 v4=1.5 taper=2 pass=0 dim=3 | %s |
     bandpass flo=5 fhi=25''' % (fft3,ifft3))
Flow('fft3','taper3','stretch rule=L dens=4 | %s' % fft3)
Flow('oper3','fft3','fkamo h1=1 h2=1 f1=45 f2=90')
Flow('imp3',['fft3','oper3'],
     '''add mode=prod ${SOURCES[1]} | %s |
     stretch rule=L dens=4 inv=y''' % ifft3)
Result('fk-imp','imp3',
       '''byte gainpanel=all |
       grey3 wanttitle=n
       frame1=71 frame2=64 frame3=64
       label1="Time (s)" label2="X Midpoint (km)" label3="Y midpoint (km)"
       ''')

###########################################################################

End()
