import rsfproj
import string

proj = rsfproj.Project()
api = proj.get('API',[])

# C api

proj.Program('AFDMc__.c')

# C++ api

if 'c++' in api:
    proj.Program('AFDMc++.cc',LIBS=['rsf++','rsf','m'])

# F90 api

if 'f90' in api:
    rsfproj.Program90('AFDMf90')

