from rsfbook import *

Papers(copyr='The University of Texas at Austin',
       group='Jackson School of Geosciences',
       line='Selected papers',
       authors={'diffr':'Sergey Fomel, Evgeny Landa, and M.~Turhan Taner',
                'pwc':'Sergey Fomel and Antoine Guitton',
                'time2depth':'Maria Cameron, Sergey Fomel, and James Sethian',
                'medianfilter': 'Yang Liu, Cai Liu, and Dian Wang',
                'simistack': 'Guochang Liu, Sergey Fomel, Long Jin, and Xiaohong Chen',
                'strfilter': 'Yang Liu, Sergey Fomel, and Guochang Liu'},
       fig=('diffr/chan3d','pwmig','width=\\textwidth'))

End(use='amsmath,newalg')

