from rsf.proj import *
from rsf.recipes.beg import server as private

trace=300

Flow('line.asc',None,
     'echo %d 0 %d 4 n1=4 data_format=ascii_float in=$TARGET' %
     (trace,trace))

for mode in ['pp','ss']:
    data = 'bend_l1_%cmig_enhanc.sgy' % mode[1]
    Fetch(data,'vecta',private)
    Flow(mode,data,
         '''
         segyread tape=$SOURCE read=data |
         window n2=471 | scale axis=2 | put label2=Trace
         ''',stdin=0)

nails = ('''
0.32 0.72
0.57 1.22
0.97 1.97
''').split()

Flow('nails0.asc',None,
     'echo %s n1=2 n2=%d in=$TARGET data_format=ascii_float' %
     (' '.join(nails),len(nails)/2))
Flow('nails','nails0.asc','dd form=native')
Flow('nreal','nails','window n1=1')
Flow('nimag','nails','window f1=1')

Flow('fit','nails pp1','linefit pattern=${SOURCES[1]}')

Flow('fit0','fit','math output=input-x1 | spray o=0 d=1 n=471')

import warp as newwarp
newwarp.nwarp2('vec','pp','ss','fit0',
               nx=471,
               inter=5,
               tmax=1.5,
               ss=1,
               trace=trace,
               gmax=2.3,
               gmin=1.5,
               dt=0.002,
               g0=0.9,
               ng=41,
               rect1=50,
               rect2=50,
               fmax=70,
               frect=20,
               fmin=20,
               frame1=285,
               iter=2,
               clip=0.39)

box = '''
      box x0=%g y0=%g label="%s" xt=%g yt=%g lab_fat=3
      '''
x = 5
y = 1.1
w = 80
w1= 0.2

Flow('frame.asc',None,
     'echo %s n1=10 data_format=ascii_float in=$TARGET' % \
     ' '.join(map(str,(x,y,x+w,y,x+w,y+w1,x,y+w1,x,y))))
Plot('frame','frame.asc',
     '''
     dd type=complex form=native |
     graph min1=0 max1=180 min2=0 max2=1.5 pad=n plotfat=10 plotcol=3
     wantaxis=n wanttitle=n 
     ''')

Result('after1','vec-in1-1 frame','Overlay')

End()

