from rsfproj import *

segy = 'sac120hz_10272004.sgy'

Fetch(segy,'sanclem')

Flow('sac120 ./hfile ./bfile tfile',segy,
     '''
     segyread tape=$SOURCE tfile=${TARGETS[3]}
     hfile=${TARGETS[1]} bfile=${TARGETS[2]}
     ''',stdin=0)
Flow('./sac','sac120','put n2=400 n3=500 d2=0.25 d3=1 o2=-99.75 o3=251')

Flow('cmp','sac','shot2cmp positive=n')
Flow('mut','cmp','mutter v0=3000 t0=0.1 | bandpass flo=20')

Flow('vscan','mut','vscan semblance=y v0=1000 nv=100 dv=25')
Flow('vrms','vscan',
     'window f1=100 | pad beg1=100 | blindpick rect1=10 rect2=20')
Result('sanvrms','vrms',
       '''
       window min3=348.25 max3=753 |
       grey color=j allpos=y scalebar=y wanttitle=n
       barlabel="RMS velocity (km/s)"
       label1="Time (s)" label2="Midpoint (m)"
       bias=1000
       ''')
Flow('nmo',['mut','vrms'],'nmo velocity=${SOURCES[1]}')
Flow('stack','nmo','stack')
Result('sanstack','stack',
       '''
       window min2=450 max2=750 |
       grey title="NMO Stack" label1="Time (s)" label2="Midpoint (m)"
       ''')

End()
