from rsf.proj import *
from rsf.recipes.beg import server
from math import pi

Fetch(['vel_hessiso.H',
       'vel_hessiso.H@',
       'density_hessiso.H',
       'densityfinal.H@'],'hess',server)

Flow('vel','vel_hessiso.H vel_hessiso.H@',
     'dd form=native | put label1=z label2=x unit1=ft unit2=ft')
Flow('den','density_hessiso.H densityfinal.H@',
     'dd form=native | put label1=z label2=x unit1=ft unit2=ft')

f0 = 5
f1 = 60
nf = 562

df = (f1-f0)/(nf-1)

w0 = f0*2*pi
dw = df*2*pi

Flow('impulsed',None,
     '''
     spike mag=0 
     o1=0 n1=3000 d1=20 
     o2=0 n2=1    d2=20 
     n3=%d d3=%g o3=%g 
     n4=1 d4=0.1 o4=0 
     n5=1 d5=0.1 o5=0 | rtoc |
     put plane_os_x=38400 plane_ds_x=50 plane_ns_x=1 plane_os_y=0 plane_ds_y=12.5 plane_ns_y=1
     ''' % (nf,dw,w0))
Flow('wavelet',None,
     '''
     spike n1=1700 d1=0.006 k1=8 | ricker1 frequency=25 | fft1 opt=n | window min1=%g max1=%g |
     put o1=%g d1=%g
     ''' % (f0,f1,w0,dw))

Flow('twoway','impulsed vel wavelet',
     '''
     isoimpulse Data=${SOURCES[0]} Velocity=${SOURCES[1]} Wavelet=${SOURCES[2]} 
     mig_nz=2700 mig_dz=6 nhx=1 image_min_x=0 image_max_x=60000.0 
     Image_hx=$TARGET fd_a=0.664820 fd_b=0.948380 fd_trick=0.11 operator=1 
     vti=0 t=5.328 tilt=1 --readwrite=y
     ''',stdin=0,stdout=0)

Flow('wtwoway','twoway','window max1=16000 max4=60000 min4=10000')

End()
