from rsf.suproj import *

Fetch('seismic.segy','viking',server=os.environ.get('RSF_DATASERVER','http://www.ahay.org'))

# Convert to SU
Flow('seismic','seismic.segy',
     '''
     segyread endian=%d tape=$SOURCE verbose=1 | 
     segyclean
     ''' % (not little_endian()),stdin=0)

# Sort and gain
Flow('cdps','seismic',
     'susort cdp offset | sugain jon=1')

# Brute stack
Flow('bstack','cdps','sustack')
stacks = ['bstack']

# Constant-velocity NMO and stack
for v in (1500,2300):
    stack = 'stack%d' % v    
    Flow(stack,'cdps','sunmo vnmo=%d | sustack' % v)
    stacks.append(stack)

Flow('stack','cdps',
     'sunmo vnmo=1500,1800,2300 tnmo=0.0,1.0,2.0 | sustack')
stacks.append('stack')

for stack in stacks:
    Result(stack,'suximage perc=99')

End()
