from rsf.proj import *

Flow('inp',None,'spike n1=15 label1=" " ')
Flow('filt',None,'spike n1=2 nsp=2 k1=1,2 mag=1,-0.5')

Flow('1','inp filt','conv filt=${SOURCES[1]} trans=n | pad n1=16')
Flow('2','inp filt','conv filt=${SOURCES[1]} trans=y | pad n1=16')
Flow('pin','inp','pad n1=16')
Flow('pf','filt','pad n1=16')

Result('conv',['1','2','pf','pin'],
       '''cat axis=2 ${SOURCES[1:4]} |
       dots dots=2 connect=0 gaineach=0 overlap=1.25
       labels=icai1:tcai1:filter:input labelsz=14''')

###########################################################################
End()
