from rsf.proj import *

n2=3

for i in range(n2):
    Flow('pef%03d.txt'%i, None, 
         '''
         /bin/cat slurm_prefix.txt                 >s_${TARGETS[0]}.job;
         echo "pushd .."                          >>s_${TARGETS[0]}.job;
         echo "scons demult%03d.rsf"              >>s_${TARGETS[0]}.job;
         echo "popd .."                           >>s_${TARGETS[0]}.job;
         echo "touch ./s_${TARGETS[0]}.touch.job" >>s_${TARGETS[0]}.job;
         echo pwd;
	 pwd;
         rm ./s_${TARGETS[0]}.job.touch;
	 echo run fakesub;
	 ./fakesub ./s_${TARGETS[0]}.job;
         echo pwd;
         pwd;
	 echo "(while [ ! -f ./s_${TARGETS[0]}.job.touch ]; do (sleep 1); done )";
	 (while [ ! -f ./s_${TARGETS[0]}.job.touch ]; do (sleep 1); done );
         echo "all done in flow"
         ''')
	 
End()
