from rsf.proj import *

#SConscript('../segy/SConstruct')

for win in range(4):
    shots = 'shots%d' % win

    Plot(shots,'../segy/DeconShots3.rsf',
         '''
     window n2=100000 f2=%d j1=2 | put n2=1000 n3=100 | grey title="%s 10000 traces"
     ''' % (win*100000,('1st','2nd','3rd','4th')[win]),view=1)

Flow('foldplot','../segy/DeconShots3_hdr.rsf',
     '''
      dd type=float |
      fold
          verbose=1
          o1=60 n1=10  d1=5 label1=offset
          o2=1001 n2=1943 d2=1   label2=xline
          o3=5100 n3=296  d3=1   label3=iline        
     ''')
#	  o2=5100 n2=300  d2=1 label2=iline
#	  o3=2801 n3=144  d3=1 label3=xline
#    ''')
# plot xline 1001-2943 
#      iline after 5100?  before 5400  
#	  o2=990 n2=20  d2=1 label2=xline
#	  o3=5300 n3=100  d3=1 label3=iline
#    ''')
 
#          o2=0 n2=2943 d2=1   label2=xline
#          o3=0 n3=5395  d3=1   label3=iline        
#    ''')

Plot('foldplot','grey title=foldplot pclip=100 allpos=y scalebar=y',view=1)

Flow('zoomfoldplot','../segy/DeconShots3_hdr.rsf',
    '''
      dd type=float |
      fold
          verbose=1
          o1=60 n1=50  d1=1 label1=offset
          o2=2001 n2=100 d2=1   label2=xline
          o3=5301 n3=1  d3=1   label3=iline        
    ''')

Result('zoomfoldplot','grey title=foldplot pclip=95')

Result('foldplot3','foldplot',
     '''
     byte gainpanel=all plclip=100 allpos=y |
     grey3  title=foldplot 
            frame1=4 frame2=94 frame3=172
     ''')

Flow('foldplot_off','foldplot','transp plane=13')

Plot('foldplot_off','grey title=foldplot pclip=100 allpos=y',view=1)

End()
