from rsfproj import *

import string

###########################################################################

grey = '''grey color=j allpos=y screenht=6 screenwd=12
wanttitle=n label1="Depth (km)" label2="Lateral (km)"
scalebar=y barlabel="Velocity (km/s)"'''

rays =  '''cell2 nr=1000 nt=4000 yshot=0 |
plotrays frame=$SOURCE screenht=6 screenwd=12 jr=5 plotcol=0
scalebar=y'''

contour = '''contour scalebar=y plotcol=0 wanttitle=n
screenht=6 screenwd=12 c0=0 dc=0.1 nc=20'''

fronts = string.join(['eikonal yshot=0',contour],' | ')
exact = string.join(['window n3=1 f3=1',contour],' | ')

Flow('const',None,"spike n1=601 d1=0.01 n2=1201 d2=0.01 o2=0")
Plot('const',grey)
Plot('cell2','const',rays)
Result('straight','const cell2','Overlay')

Flow('vofz',None,'vofz n=600 s=0')
Flow('cgrad','vofz','window n3=1')
Plot('cgrad',grey)
Plot('ccell2','cgrad',rays)
Result('circle','cgrad ccell2','Overlay')

Plot('ceiko','cgrad',fronts)
Result('ceiko','cgrad ceiko','Overlay')
Plot('cexact','vofz',exact)
Result('cexact','cgrad cexact','Overlay')

Flow('s2ofz',None,'s2ofz n=600 s=0')
Flow('c2grad','s2ofz','window n3=1')
Plot('c2grad',grey)
Plot('c2cell2','c2grad',rays)
Result('parab','c2grad c2cell2','Overlay')

Plot('c2eiko','c2grad',fronts)
Result('c2eiko','c2grad c2eiko','Overlay')
Plot('c2exact','s2ofz',exact)
Result('c2exact','c2grad c2exact','Overlay')
    
###########################################################################
End()
