from rsfproj import *
import string

###########################################################################

grey = '''grey color=j allpos=y screenwd=12 screenht=4
wanttitle=n label1=Depth unit1=km label2=Lateral unit2=km
scalebar=y barlabel=Velocity barunit=km/s barreverse=y'''

def rays(plotcol=7):
    return '''cell2 nr=1000 nt=4000 yshot=0 traj=traj >/dev/null &&
    plotrays < traj frame=$SOURCE screenht=6 screenwd=12 jr=5 plotcol=%d
    scalebar=y screenht=4 > $TARGET &&
    /bin/rm traj''' % plotcol

contour = '''contour scalebar=y plotcol=7 wanttitle=n
screenht=4 screenwd=12 c0=0 dc=0.1 nc=30'''

fronts = string.join(['eikonal yshot=0',contour],' | ')

def exact(f3):
    return string.join(['window n3=1 f3=%d' % f3,contour],' | ')

Flow('const','s2ofz','math output=1')
Plot('const',grey)
Plot('cell2','const',rays(0),stdout=-1)
Result('straight','const cell2','Overlay')

Flow('vofz',None,'vofz n=600 s=0')
Flow('cgrad','vofz','window n3=1')
Plot('cgrad',grey)
Plot('ccell2','cgrad',rays(),stdout=-1)
Result('circle','cgrad ccell2','Overlay')

Plot('ceiko','cgrad',fronts)
Result('ceiko','cgrad ceiko','Overlay')
Plot('cexact','vofz',exact(1))
Result('cexact','cgrad cexact','Overlay')

Flow('s2ofz',None,'s2ofz n=600 s=0')
Flow('c2grad','s2ofz','window n3=1')
Plot('c2grad',grey)
Plot('c2cell2','c2grad',rays(),stdout=-1)
Result('parab','c2grad c2cell2','Overlay')

Plot('c2eiko','c2grad',fronts)
Result('c2eiko','c2grad c2eiko','Overlay')

Plot('c2exact1','s2ofz',exact(1))
Plot('c2exact2','s2ofz',exact(2))
Result('c2exact','c2grad c2exact1 c2exact2','Overlay')
    
###########################################################################
End()
