from rsfproj import *

Flow('spike1',None,
     '''
     spike n1=442 n2=101 d1=0.005 d2=20 o1=0 o2=-1000 k1=201 k2=51 |
     bandpass fhi=60
     ''')

Flow('spike2',None,
     '''
     spike n1=842 n2=51 d1=0.005 d2=20 o1=0 o2=-500 k1=401 k2=26 |
     bandpass fhi=60
     ''')

Flow('spike3',None,
     '''
     spike n1=1242 n2=25 d1=0.005 d2=20 o1=0 o2=-250 k1=601 k2=13 |
     bandpass fhi=60
     ''')

h = (1000,500,250)
f = ((180,380,580),(120,320,520))

for adj in (0,1):
    for type in (1,3):
        imp = 'imp%d_%d' % (adj,type)
        imps = []
        for case in (1,2,3):
            hale = imp + '_%d' % case
            Flow(hale,'spike%d' % case,
                 'dmo adj=%d h=%d velhalf=250 n=100 type=%d inv=0' %
                 (adj,h[case-1],type))
            Plot(hale,
                 '''
                 window n1=101 f1=%d | wiggle title="offset=%d m"
                 transp=y yreverse=y poly=y labelsz=20 titlesz=25
                 ''' % (f[adj][case-1],2*h[case-1]))
            imps.append(hale)
        Plot(imp,imps,'OverUnderAniso')

Result('adjimp','imp1_1 imp1_3','SideBySideAniso')
Result('adjinv','imp0_1 imp0_3','SideBySideAniso')

End()
