from rsf.proj import *

lag = (1,2,3,97,98,99,100)
flt = (-.36,-.024,-.013,-.024,-.05,-.11,-.31)
n1 = len(lag)

Flow('lag.asc',None,
     'echo %s n1=%d n=100,100 data_format=ascii_int in=$TARGET' %
     (' '.join(map (str, lag)),n1))
Flow('lag','lag.asc','dd form=native')
Flow('flt.asc','lag',
     '''echo %s a0=1 n1=%d data_format=ascii_float in=$TARGET
     lag=$SOURCE''' % (' '.join(map (str, flt)),n1),stdin=0)
Flow('flt','flt.asc','dd form=native')

Flow('spike3',None,'spike n1=30 n2=30 nsp=2 k1=4,10 k2=10,4 mag=1,-1')
Flow('inp3',None,'spike n1=30 n2=30 nsp=2 k1=29,25 k2=20,10 mag=1,-1')

def helicon(adj=0,div=0):
    return 'helicon filt=${SOURCES[1]} adj=%d div=%d' % (adj,div)

g = 'grey gainpanel=every pclip=100 wantaxis=n crowd=.88 gpow=.7 title="%s" '

Flow('inp','spike3 inp3 flt',
     'helicon filt=${SOURCES[2]} | add ${SOURCES[1]}')
Flow('div', 'inp flt',helicon(0,1))
Flow('div2','div flt',helicon(1,1))
Plot('inp',  g % 'input')
Plot('div',  g % 'input/filter')
Plot('div2', g % '(input/filter)/filter\'')
Result('lapfac','inp div div2','SideBySideAniso',vppen='txscale=2.4')

End()
