import sys, os, string, re


Import('env')
env = env.Clone()

env.Tool('python')
env.Tool('swig')
env.Tool('numpytool')

env.Append( SWIGFLAGS=['-python'] )

env.InstallPythonModule(['rsfbak.py'])

modules = Split('rsf vplot vfsr')

for module in modules:
    ifile = module+'.i'
    python = env.LoadableModule('_c_'+module,[ifile])
    pfiles = [python,module+'.py']
        
    install = env.InstallPythonModule(pfiles)    

#    if env['PLATFORM'] == 'darwin':    
#        for lib in ('rsf','rsfplot'):
#            env.AddPostAction(install,
#                              'install_name_tool -change '
#                              'build/api/c/libd%s.dylib '
#                              '${lib_prefix}/libd%s.dylib ${lib_prefix}/%s' % \
#                                  (lib,lib,python[0]))

