/* This file is automatically generated. DO NOT EDIT! */

#ifndef _omputil_h
#define _omputil_h


/*------------------------------------------------------------*/
int omp_init();
/*< init OMP parameters >*/

#endif
