/* This file is automatically generated. DO NOT EDIT! */

#ifndef _wex_h
#define _wex_h


#include <rsf.h>


#ifdef _OPENMP
#include <omp.h>
#include "omputil.h"
#endif


#include "wex.h"
#include "wextap.h"
#include "wexslo.h"
#include "wexssr.h"
#include "wexutl.h"


/*------------------------------------------------------------*/
wexcub3d wex_cube(bool    verb_,
		  sf_axis amx_,
		  sf_axis amy_,
		  sf_axis az_,
		  sf_axis alx_,
		  sf_axis aly_,
		  sf_axis aw_,
		  sf_axis ae_,
		  float   eps_,
		  int     ompnth_
    );
/*< initialize SR migration space >*/


/*------------------------------------------------------------*/
wexop3d wex_init(wexcub3d cub);
/*< initialize >*/


/*------------------------------------------------------------*/
void wex_store(wexop3d weop,
	       wexcub3d cub,
               int iz,
               int ompith
    );
/*< store wavefield >*/


/*------------------------------------------------------------*/
void wex_close(wexop3d weop);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void wexdatum(wexop3d weop,
              wexcub3d cub,
              wexssr3d ssr,
              wextap3d tap,
              wexslo3d slo,
              int  wexsign,
              sf_file data /* adj=0, reflectively r[nz][nmy][nmx]; adj=1 data [nw][nmy][nmx] */,
              sf_file wflr /* receiver wavefield [nw][nz][nmy][nmx] */,
              int     inv /* down/upward flag */);
/*< Datuming wavefield by continuation >*/


/*------------------------------------------------------------*/
void wex(wexop3d weop,
	 wexcub3d cub,
	 wexssr3d ssr,
	 wextap3d tap,
	 wexslo3d slo,
	 int  wexsign,
	 sf_file   data /* adj=0, reflectively r[nz][nmy][nmx]; adj=1 data [nw][nmy][nmx] */,
	 sf_file   wflr /* receiver wavefield [nw][nz][nmy][nmx] */,
         bool    adj /* adjoint flag             */);
/*< Save wavefield from continuation >*/

#endif
