/* This file is automatically generated. DO NOT EDIT! */

#ifndef _wexeic_h
#define _wexeic_h


#include <rsf.h>
#include <math.h>
/*^*/
#ifdef _OPENMP
#include <omp.h>
#include "omputil.h"
#endif
/*^*/
#include "wex.h"
#include "wexeic.h"
/*^*/
#ifdef SF_HAS_COMPLEX_H
#define cWGH(a,b,c)  (+1.*(conjf(a)*b)*c)
#define cAWGH(a,b,c) (+1.*(a*b)*c)
#define cCOR(a,b) (conjf(a)*b)
#define cACOR(a,b) (a*b)
#define cMUL(a,b) (a*b) 
#else
#define cWGH(a,b,c) (+1.*sf_cmul((sf_cmul(conjf(a),b)),c))
#define cAWGH(a,b,c) (+1.*sf_cmul((sf_cmul(a,b)),c))
#define cCOR(a,b) (sf_cmul(conjf(a),b))
#define cACOR(a,b) (sf_cmul(a,b))
#define cMUL(a,b) (sf_cmul(a,b))
#endif


/*------------------------------------------------------------*/
wexcip3d wexcip_init(wexcub3d cub,
                        int  nhx_,
                        int  nhy_,
                        int  nhz_,
                        int  nht_,
                        int  nhx2_,
                        int  nhy2_,
                        int  nhz2_,
                        int  nht2_,
                        int   nc_,
                      float  dht_,
                      float  oht_,
                    sf_file Fc,
                        int eic);
/*< initialize I.C. >*/


/*------------------------------------------------------------*/
void wexcip_close(wexcip3d cip, int eic);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void wexcip_for(wexcub3d cub,
                wexcip3d cip,
                 sf_file wfls,
                 sf_file wflr,
                 sf_file imag,
                 int eic,
                 int rep,
                 int cjg
         );
/*< E.I.C >*/


/*------------------------------------------------------------*/
void wexcip_adj(wexcub3d cub,
                wexcip3d cip,
                 sf_file wfls,
                 sf_file wflr,
                 sf_file imag,
                 int eic,
                 int rep,
                 int cjg
         );
/*< E.I.C >*/


/*------------------------------------------------------------*/
void wexcip_for_drv(wexcub3d cub,
                   wexcip3d cip,
                    sf_file wfls,
                    sf_file wflr,
                    sf_file derv
         );
/*< E.I.C >*/


/*------------------------------------------------------------*/
void wexcip_for_new(wexcub3d cub,
                   wexcip3d cip,
                    sf_file wfls,
                    sf_file wflr,
                    sf_file imag
         );
/*< E.I.C >*/


/*------------------------------------------------------------*/
void wexzocip_for(wexcub3d cub,
                  wexcip3d cip,
                   sf_file wflr,
                   sf_file imag
         );
/*< zero-offset I.C >*/


/*------------------------------------------------------------*/
void wexzocip_adj(wexcub3d cub,
                wexcip3d cip,
                 sf_file wflr,
                 sf_file imag
         );
/*< zero-offset I.C >*/

#endif
