/* This file is automatically generated. DO NOT EDIT! */

#ifndef _wexslo_h
#define _wexslo_h


#include "wexutl.h"


/*------------------------------------------------------------*/
wexslo3d wexslo_init(wexcub3d   cub,
		     sf_file  file_,   /* slowness slice */
		     int     nrmax,   /* maximum number of references */
		     float   dsmax
    );
/*< initialize slowness >*/


/*------------------------------------------------------------*/
int wexslo(int nr           /* maximum number of references */, 
	  float ds         /* minimum slowness separation */, 
	  int ns           /* number of slownesses */, 
	  const float* ss  /* [ns] slowness array */, 
	  float* sr        /* [nr] reference slownesses squared */);
/*< compute reference slownesses, return their number >*/


/*------------------------------------------------------------*/
void wexslo_close(wexslo3d slo);
/*< close slowness >*/

#endif
