from rsfbook import *

Papers(copyr='The University of Texas at Austin',
       group='Seismic Wavefield Imaging',
       papers=map(lambda x: 'hw%d/paper.tex' % x,range(1,6)),
       line='Homework Assignments',
       fig=('hw2/blake','ray','width=\\textwidth'))

End(use='color')
