from rsf.proj import *

# Download SEGY data
Fetch('data2013.sgy','kfupm')

# Convert to RSF
Flow('data tdata data.bin data.asc','data2013.sgy',
     'segyread tfile=${TARGETS[1]} bfile=${TARGETS[2]} hfile=${TARGETS[3]}')

# Gain using AGC
Flow('data-agc','data','shapeagc rect1=250')

# Gain using t^2
Flow('data-tm','data','pow pow1=2')

# Display first 6 shot records
Flow('first6','tdata','window n1=1 f1=4 | mask max=6')

for data in Split('data data-agc data-tm'):
    Result(data,[data,'first6'],
           'headerwindow mask=${SOURCES[1]} | wiggle transp=y yreverse=y poly=y title=Shots')
    
End()
