  " ",
  " ----------------------------- SEGYTAPERMUTE --------------------------------",
  " ",
    " Linear top mute with cubic taper, cubic taper on offset or gx, ",
  " zero-slope bottom mute with cubic taper.",
  " iwave/trace/include/segyops.hh",
  " ",
  " ------------------- begin segytapermute parameters -------------------------",
  " ",
    " mute_slope   = 0.0         slowness, ms/m",
    " mute_zotime  = 0.0         zero offset intercept, ms",
    " mute_width   = 0.0         width of mute taper, ms",
    " mute_type    = 0           x coord used: 0: offset, 1: gx, m",
    " taper_min    = -flt_max    taper begin, m",
    " taper_max    = flt_max     taper end, m",
    " taper_width  = 0.0         width of taper zone, m",
    " taper_type   = 0           ",
    " time_width   = 0.0         t axis taper at trace end, ms",
  " ",
  " -------------------- end segytapermute parameters ---------------------------",
