from rsf.proj import *

Flow('sin',None,'math n1=1000 output="sin(0.5*x1)" ')

Result('sin1','sin','wiggle title="One Trace" ')
Result('sin2','sin',
       'sed "s/n1=1000/n1=50 n2=20/" | wiggle title=Traces ')

plane = 'suplane_3_dips.dat'

Fetch(plane,'plane')
Flow('plane',plane,'segyread tape=$SOURCE read=data su=y endian=0',stdin=0)
Result('plane',
       '''
       wiggle clip=1 transp=y yreverse=y poly=y
       wanttitle=n wheretitle=b wherexlabel=t
       ''')

End()
