import os, string

root   = os.environ.get('RSFROOT')
libdir = os.path.join(root,'lib')
incdir = os.path.join(root,'include')

from rsfproj import *

#proj = rsfproj.Project()
#proj['CXXFLAGS'] = string.replace(proj.get('CXXFLAGS',''),'-O3','-g')

Program(  'AFDMc__.c',  LIBS=[         'rsf','m'])
Program(  'AFDMc++.cc', LIBS=['rsf++' ,'rsf','m'])
Program90('AFDMf90')

