from rsf.proj import *

sys.path.append('..')
import constant

constant.get_zodata('data')
Result('data','grey title="Zero Offset" ')

nx = 351
x0 = -1

Flow('fft','data','cosft sign2=1 | spray axis=2 n=1')

Flow('vc','fft','fourvc v0=0.0001 dv=0.01 nv=201',split=[3,'omp'])

Flow('vel','data','spike') # velocity=1

Flow('mig','vc vel','cosft sign3=-1 o3=%g | slice pick=${SOURCES[1]}' % x0)

Result('mig','window min2=0 max2=1.5 | grey title="VC Zero-Offset Migration" ')

# Impulse response

Flow('imp','data','spike k1=501 k2=175 | ricker1 frequency=10')

Flow('ifft','imp','cosft sign2=1 | spray axis=2 n=1')

Flow('ivc','ifft','fourvc v0=0.0001 dv=0.01 nv=201 pad2=4096',split=[3,'omp'])

Flow('imig','ivc vel','cosft sign3=-1 o3=%g | slice pick=${SOURCES[1]}' % x0)

Result('imig','window max1=3 | grey title="VC Impulse Response" ')

End()
