from rsf.proj import *
import math

Flow(['teapot','tteapot','teapot.asc','teapot.bin'],None,
     '''
     segyread tfile=${TARGETS[1]} hfile=${TARGETS[2]} bfile=${TARGETS[3]} tape=npr3_field.sgy
     ''',stdin=0)

# Xline/Inline numbers
Flow('ix','tteapot','dd type=float | headermath output="xline"')
Flow('il','tteapot','dd type=float | headermath output="iline"')
Flow('ixil',['ix','il'],'cmplx ${SOURCES[1]}')
Result('ixil','graph symbol="+" title="Xline/Inline" plotcol=2')

# Xline/Inline coordinates
Flow('ixc','tteapot','dd type=float | headermath output="cdpx"')
Flow('ilc','tteapot','dd type=float | headermath output="cdpy"')
Flow('ixilcoord',['ixc','ilc'],'cmplx ${SOURCES[1]}')
Result('ixilcoord','graph symbol="+" title="Xline/Inline coordinates" plotcol=4')

# Shot coordinates
Flow('sx','tteapot','dd type=float | headermath output="sx"')
Flow('sy','tteapot','dd type=float | headermath output="sy"')
Flow('sxsycoord',['sx','sy'],'cmplx ${SOURCES[1]}')
Result('sxsycoord','graph symbol="+" title="Shot coordinates" plotcol=5')

# Receiver coordinates
Flow('gx','tteapot','dd type=float | headermath output="gx"')
Flow('gy','tteapot','dd type=float | headermath output="gy"')
Flow('gxgycoord',['gx','gy'],'cmplx ${SOURCES[1]}')

End()

