from rsf.proj import *

sys.path.append('..')
import constant

constant.get_zodata('data')
Result('data','grey title="Zero Offset" ')

nx = 351

Flow('fft','data','cosft sign2=1')

Flow('gazdag','fft','gazdag vel=1',split=[2,nx])

Flow('pmig','gazdag','cosft sign2=-1')

Result('pmig','window min2=0 max2=1.5 | grey title="Phase-Shift Zero-Offset Migration" ')

# Impulse response

Flow('imp','data','spike k1=501 k2=175 | ricker1 frequency=10')

Flow('ifft','imp','cosft sign2=1')

Flow('igazdag','ifft','gazdag vel=1 pad=4096',split=[2,'omp'])

Flow('ipmig','igazdag','cosft sign2=-1')

Result('ipmig','window max1=3 | grey title="Phase-Shift Impulse Response" ')


End()
