from rsfproj import *

Flow('model',None,
     '''
     spike n1=100 d1=0.08 n2=4 nsp=4 k2=1,2,3,4 mag=1,2.2,3.5,5 |
     unif2 n1=110 d1=0.05 v00=5,6,8,10,15
     ''')
Result('model',
       '''
       grey color=j allpos=y title="Model" scalebar=y
       barlabel="Velocity (kft/s)" label1="Depth (kft)" label2="Lateral (kft)"
       barreverse=y pclip=100
       ''')

End()
