from rsf.proj import *

# files have names like:
#wget ftp://software.seg.org/pub/datasets/2D/Statics_1994/7m_shots_0201_0329.segy.gz
# or
#wget https://s3.amazonaws.com/open.source.geoscience/open_data/bpstatics94/7m_shots_0201_0329.segy.gz


for filename in ['7o_5m_final_vtap',
                 '7m_shots_0201_0329',
		 '7m_shots_0331_0599',
		 '7m_shots_0601_0869',
		 '7m_shots_0871_1139',
		 '7m_shots_1141_1409',
		 '7m_shots_1411_1679',
		 '7m_shots_1681_1949']:
    Fetch(filename+'.segy.gz',dir='bpstatics94',
      server='https://s3.amazonaws.com',top='open.source.geoscience/open_data',
      usedatapath=0)

    Flow(filename+'.segy',
         filename+'.segy.gz',
        '''
        gunzip 
        ''')

    Flow([filename+'.rsf' ,filename+'_hdr.rsf',
          filename+'.thdr',filename+'.bhdr'],
         filename+'.segy',
         '''
         sfsegyread tfile=${TARGETS[1]} 
           hfile=${TARGETS[2]}  bfile=${TARGETS[3]} 
         ''')

Flow('7m_shots.rsf',
     ['7m_shots_0201_0329.rsf',
      '7m_shots_0331_0599.rsf',
      '7m_shots_0601_0869.rsf',
      '7m_shots_0871_1139.rsf',
      '7m_shots_1141_1409.rsf',
      '7m_shots_1411_1679.rsf',
      '7m_shots_1681_1949.rsf'],
     'sfcat  ${SOURCES[0:7]} axis=2',stdin=0)
Flow('7m_shots_hdr.rsf',
     ['7m_shots_0201_0329_hdr.rsf',
      '7m_shots_0331_0599_hdr.rsf',
      '7m_shots_0601_0869_hdr.rsf',
      '7m_shots_0871_1139_hdr.rsf',
      '7m_shots_1141_1409_hdr.rsf',
      '7m_shots_1411_1679_hdr.rsf',
      '7m_shots_1681_1949_hdr.rsf'],
     'sfcat  ${SOURCES[0:7]} axis=2',stdin=0)

Fetch('obrien_statics_model_vel.gif',dir='bpstatics94',
      server='https://s3.amazonaws.com',top='open.source.geoscience/open_data',
      usedatapath=0)
Flow('obrien_statics_model_vel.display',
     'obrien_statics_model_vel.gif',
     'open ${SOURCES[0]}',
     stdin=0,stdout=0)

for filename in ['README.txt','README_Modification']:
    Fetch(filename,dir='bpstatics94',
      server='https://s3.amazonaws.com',top='open.source.geoscience/open_data',
      usedatapath=0)

Flow('README.display','README.txt','/bin/cat ${SOURCES[0]}',stdin=0,stdout=-1)

End()
