from rsfproj import *
import os
import warp

private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

for mode in ('pp','ps'):
    segy = mode + '_stack.sgy'
    Fetch(segy,'apache',private)

    cube = mode+'cube'
    Flow([cube,'t'+cube,cube+'.a',cube+'.b'],segy,
         '''
         segyread tfile=${TARGETS[1]} hfile=${TARGETS[2]} bfile=${TARGETS[3]}
         tape=$SOURCE | window max1=%g
         ''' % (1.1,2)[mode=='ps'],stdin=0)

    Flow(mode,cube,'intbin')

gamma = 2.5

Flow('warp0','pp','math output="%g*x1" ' % (0.5*(gamma-1)))

warp.warp3('ap3','ppcube','pscube','warp0',
           nx=326,
           o2=375,
           tmax=1.1,
           inter=2,
           trace=600,
           dt=0.002,
           g0=0.9,
           gmin=2,
           gmax=3,
           ng=51,
           rect1=50,
           rect2=50,
           fmin=10,
           fmax=50,
           frect=9,
           frame1=400,
           iter=2,
           clip=11.33)

End()
