from rsf.book import *

Papers(copyr='Rice University',
       group='The Rice Inversion Project',
       papers=Split('''
       struct
       '''),
       authors = {'struct':'William Symes'},
       line='Selected papers',
       fig=('struct/project','framesrc','width=\\textwidth'))
       
End(use='hyperref,amsmath,setspace,wasysym',
    include=r'''
\newcommand{\rs}[1]{\mathstrut\mbox{\scriptsize\rm \#1}}
\newcommand{\rr}[1]{\mbox{\rm #1}}
\newcommand{\mb}{\mathbf}
\newcommand{\om}{\bar{m}}
\newcommand{\oM}{\bar{M}}
\newcommand{\oF}{\bar{F}}
\newcommand{\cJ}{\mathcal{J}}
\newcommand{\bx}{{\bf x}}
\everymath{\displaystyle}
''')

