from rsf.book import *

Papers(copyr='Rice University',
       group='The Rice Inversion Project',
       papers=Split('''
       struct
       asg
       '''),
       authors = {'struct':'William Symes',
                  'asg':'William Symes'},
       line='Selected papers',
       fig=('struct/project','framesrc','width=\\textwidth'))
       
End(use='hyperref,amsmath,setspace,wasysym',
    include=r'''
\newcommand{\rs}[1]{\mathstrut\mbox{\scriptsize\rm \#1}}
\newcommand{\rr}[1]{\mbox{\rm #1}}
\newcommand{\mb}{\mathbf}
\newcommand{\om}{\bar{m}}
\newcommand{\oM}{\bar{M}}
\newcommand{\oF}{\bar{F}}
\newcommand{\cJ}{\mathcal{J}}
\everymath{\displaystyle}
\newcommand{\du}{\delta u}
\newcommand{\dm}{\delta m}
\newcommand{\lu}{\lambda u}
\newcommand{\lm}{\lambda m}
\newcommand{\muu}{\mu u}
\newcommand{\bF}{{\bf F}}
\newcommand{\bS}{{\bf S}}
\newcommand{\bH}{{\bf H}}
\newcommand{\bM}{{\bf M}}
\newcommand{\bR}{{\bf R}}
\newcommand{\bu}{{\bf u}}
\newcommand{\bx}{{\bf x}}
\newcommand{\bv}{{\bf v}}
\newcommand{\be}{{\bf e}}
\newcommand{\bp}{{\bf p}}
\newcommand{\cS}{{\cal S}}
\newcommand{\peq}{\,+\hspace{-0.15cm}=}
\newcommand{\pp}{\,+\hspace{-0.1cm}+}
\newcommand{\mm}{\,-\hspace{-0.1cm}-}
''')

