from rsfproj import *
# ------------------------------------------------------------
# PLOTTING
# ------------------------------------------------------------
def igrey(custom):
    return '''
    grey %s 
    ''' % (custom)

# ------------------------------------------------------------
## 
 # Simple model
 ##
# ------------------------------------------------------------
par = {
    'nz':250, 'dz':2,     'oz':0, 'zmin':0, 'zmax':500,
    'nx':250, 'dx':4,     'ox':0, 'xmin':0, 'xmax':1000,
    'nt':1500,'dt':0.0005,'ot':0,
    'nw':60,  'ow':5,
    'tx':16,
    'px':0,
    'eps':0.01,
    'nrmax':3,
    'kz':200,
    'ds':8, 'os':400, 'ns':1,
    'nw':100, 'ow':0, 'jw':1
    }
nw=60
ow=5

ns=1
os=400
ds=8

# ------------------------------------------------------------
# VELOCITY / SLOWNESS
# ------------------------------------------------------------
Flow('vel',None,
     '''
     spike nsp=3 mag=-1000,-1000,-1000
           n1=%(nz)d d1=%(dz)g o1=%(oz)g
           k1=160,140,180
           l1=250,250,250
           label1="z"
           n2=%(nx)d d2=%(dx)g o2=%(ox)g
           k2=001,101,151
           l2=100,150,250
           label2="x"|
     math output="input + 2000"
     ''' % par)
Flow('s0','vel',
     '''
     transp |
     math "output=1/input" |
     spray axis=2 n=1 |
     put label2=y
     ''' % par )
# ------------------------------------------------------------
# REFLECTIVITY
# ------------------------------------------------------------
Flow('refl',None,
     '''
     spike nsp=3 mag=1,2,3
           n1=%(nz)d d1=%(dz)g o1=%(oz)g
           k1=160,140,180
           l1=160,140,180
           label1="z"
           n2=%(nx)d d2=%(dx)g o2=%(ox)g
           k2=001,101,151
           l2=100,150,250
           label2="x"
     ''' % par)
Flow('r0','refl',
     '''
     transp |
     spray axis=2 n=1 o=0 d=1 |
     put label2=y
     ''' % par)

Result('s0','s0','window      | transp |'+igrey('pclip=99 allpos=y color=j'))
Result('r0','r0','window      | transp |'+igrey('pclip=100'))

# ------------------------------------------------------------
# wavelet
Flow('ttt',None,
     '''
     spike nsp=1 n1=%(nt)d d1=%(dt)g o1=%(ot)g
     n2=1 d2=%(dx)g o2=%(os)g |
     math output="exp(-40000*((x1-0.1)^2))" |
     halfint inv=y adj=n |
     halfint inv=y adj=y |
     bandpass flo=5 
     ''' % par)
Result('ttt','ttt','window n1=500 | graph')

Flow('sou','ttt',
     '''
     fft1 |
     window squeeze=n n1=%(nw)d min1=%(ow)g j1=%(jw)d |
     put label1=w
     ''' % par )
Result('sou','sou','real | graph')
# ------------------------------------------------------------


def pgraph(args):
    return '''
    graph %s
    yreverse=y symbolsz=16 wantaxis=n title=" "
    min1=0 max1=1000 min2=0 max2=500
    ''' % (args)

#def igrey(args):
#    return '''
#    grey labelrot=n %s
#    label1="z" label2="x" title=" "
#    min2=0 max2=1000 min1=0 max1=500
#    ''' % (args)
def dgrey(args):
    return '''
    grey labelrot=n %s
    label1="t" label2="x" title=" "
    min2=0 max2=1000
    ''' % (args)
# ------------------------------------------------------------

Plot('vel','vel',igrey('pclip=100 bias=900 allpos=y'))

# ------------------------------------------------------------

Flow('rs',None,'math n1=1 d1=0 o1=0 output=1')

for i in range(ns):
    o = os+i*ds
    par['o']=o
    
    zs = 'zs' + str(i)
    xs = 'xs' + str(i)

    zr = 'zr' + str(i)
    xr = 'xr' + str(i)    
    ss = 'ss' + str(i)
    rr = 'rr' + str(i)

    dd = 'dd' + str(i)
    ee = 'ee' + str(i)
    ww = 'ww' + str(i)
    sh = 'sh' + str(i)

    gg = 'gg' + str(i)

    Flow(zs,None,'math n1=1 d1=0 o1=0 output=0')
    Flow(xs,None,'math n1=1 d1=0 o1=0 output=%(o)g' % par)

    Flow(zr,None,'math n1=250 d1=%(dx)g o1=0 output="00"' % par )
    Flow(xr,None,'math n1=250 d1=%(dx)g o1=0 output="x1"' % par )

    Flow(ss,[xs,zs,'rs'],'cat axis=2 space=n ${SOURCES[0]} ${SOURCES[1]} ${SOURCES[2]} | transp ', stdin=0)
    Flow(rr,[xr,zr]     ,'cat axis=2 space=n ${SOURCES[0]} ${SOURCES[1]}               | transp ', stdin=0)

    Plot(ss,ss,'window n1=2 | dd type=complex | window | ' + pgraph('symbol=* plotcol=2'))
    Plot(rr,rr,'window n1=2 | dd type=complex | window | ' + pgraph('symbol=. plotcol=1 symbolsz=.01'))

    Result(gg,['vel',ss,rr],'Overlay')
    
    Flow([dd,ww],['ttt','vel',ss,rr],
     '''
     afdm2d verb=y abc=y free=n snap=y jsnap=300
         nbz=50 tz=0.006125
         nbx=50 tx=0.006125 
         vel=${SOURCES[1]}
         sou=${SOURCES[2]}
         rec=${SOURCES[3]}
         wfl=${TARGETS[1]}
     ''' % par)
    
    Plot(ww,ww,'window n3=1 f3=2|' + igrey('pclip=100'))
    Result(ww,[ww,ss,rr],'Overlay')
    
    Plot(dd,dd,'transp |' + igrey('pclip=99'))
    Result(dd,[dd,ss,rr],'Overlay')

# ------------------------------------------------------------

Flow('sdd','sou',
     '''
     pad beg2=100 n2out=%(nx)d |
     transp |
     spray axis=2 n=1 o=0 d=1 |
     put label1=x label2=y
     ''' % par )
Flow('srr www','sdd s0 r0',
     '''
     srmod readwrite=y verb=y eps=0.01 nr=5 dt=0.00005 tx=32 px=100
     slo=${SOURCES[1]}
     ref=${SOURCES[2]}
     www=${TARGETS[1]}
     ''')

Flow('trr','srr',
     '''
     window |
     transp |
     pad n1out=751 |
     fft1 inv=y |
     put label1=t
     ''' % par)
Plot('trr','trr',igrey('pclip=100'))
Result('trr',['trr','ss0','rr0'],'Overlay')

End()
