/* This file is automatically generated. DO NOT EDIT! */

#ifndef _mpisponge_h
#define _mpisponge_h


typedef struct {
    int bzl; float *wzl;
    int bzh; float *wzh;
    int bxl; float *wxl;
    int bxh; float *wxh;
} Sponge;


Sponge *sponge_init(const int *b,  /* [4]={bzl,bzh,bxl,bxh} */
		    const float *c /* [4]={czl,czh,cxl,cxh} */);
/*< initialize >*/


void sponge_apply(float *u,     /* [Nz][Nx] */
                  const int *n, /* [2]={nz,nx} */
                  const Sponge *S);
/*< apply >*/

#endif
