import os, sys

try:
    import bldutil
    glob_build = True
    srcroot = '../..'
    Import('env bindir pkgdir')
except:
    glob_build = False
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug()
    bindir = pkgdir = None

has_fftw = False # True

progs = '''
integral1 pseudodepth swapbyte raytest vtiwave
'''

if has_fftw:
	env.Append(CPPPATH='/usr/include',LIBS='fftw3f')
else:
	progs = progs.replace('vtiwave','')

if env.get('LAPACK'):
	env.Append(LIBS='lapack')
else:
	progs = progs.replace('pseudodepth','')
    
targets = bldutil.UserSconsTargets()
targets.c = progs

targets.build_all(env, glob_build, srcroot, bindir, pkgdir)
