import os, sys

try:
    import bldutil
    glob_build = True
    srcroot = '../..'
    Import('env bindir pkgdir')
    env = env.Clone()
except:
    glob_build = False
    srcroot = os.environ.get('RSFSRC', '../..')
    sys.path.append(os.path.join(srcroot,'framework'))
    import bldutil
    env = bldutil.Debug()
    bindir = pkgdir = None

progs = '''
integral1 swapbyte 
'''

lapack = env.get('LAPACK')

if lapack:
    env.Prepend(LIBS=lapack)
    progs += ' pseudodepth'
elif glob_build:
    for prog in Split('pseudodepth'):
        prog = env.RSF_Place('sf'+prog,None,var='LAPACK',package='lapack')      
        env.Install(bindir,prog)

fftw = env.get('FFTW')
if fftw:
    env.Prepend(LIBS=[fftw])
    progs += ' zomiso zomvti'
elif glob_build:
    for prog in Split('zomiso zomvti'):
        prog = env.RSF_Place('sf'+prog,None,var='FFTW',package='fftw')
        env.Install(bindir,prog)




targets = bldutil.UserSconsTargets()
targets.c = progs

targets.build_all(env, glob_build, srcroot, bindir, pkgdir)
