/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sponge_h
#define _sponge_h


typedef struct {
    int bzl; float *wzl;
    int bzh; float *wzh;
    int bxl; float *wxl;
    int bxh; float *wxh;
} Sponge;


Sponge *sponge_init(const int *b,   /* {bzl,bzh,bxl,bxh} */
					const float *c  /* {czl,czh,cxl,cxh} */);
/*< >*/


void sponge_apply(float *u,     /* [Nz][Nx] */
                  const int *n, /* {nz,nx} */
                  const Sponge *S);
/*< >*/


void sponge_free(Sponge *S);
/*< >*/

#endif
