/* This file is automatically generated. DO NOT EDIT! */

#ifndef _util_h
#define _util_h


/* fast fft size */
int fft_size(int n);
/*< >*/


/* update boundary to fit fast fft size */
void fft_expand(int n,
                int *l, /* [1] */
                int *h  /* [1] */);
/*< >*/


/* expand 2D model */
void expand(float *q, /* [N2][N1]    */
            const float *p,    /* [n2][n1]    */
            const int *n,      /* {n1,n2} */
            const int *l,      /* {l1,l2} */
            const int *h       /* {h1,h2} */);
/*< >*/


/* compute wavenumbers
   0     to N/2 positive
   N/2+1 to N-1 negative */
void compute_k(float *k, /* [nk] */
               int nk);
/*< >*/

#endif
