from rsf.proj import * 

f0=3.0 
A0=1.0 
t0=3.5 

Flow('data',None,'''math n1=700 d1=0.01 o1=0.0
                    output="%g*exp(-2*(x1-%g)^2)*cos(2*3.14*%g*(x1-%g))" '''  
                    %(A0,t0,f0,t0)) 

# stretch data 
#Flow('stretch','data','spray axis=2 n=101 o=0.6 d=0.008 | math output="x1*x2" ')
#Flow('sdata',['data','stretch'],'spray axis=2 n=101 o=0.6 d=0.008 | iwarp warp=${SOURCES[1]} | transp plane=24')

Flow('stretch','data','spray axis=2 n=101 o=0.7 d=0.006 | math output="x1*x2" ')
Flow('sdata',['data','stretch'],'spray axis=2 n=101 o=0.7 d=0.006 | iwarp warp=${SOURCES[1]} | transp plane=24')


Flow('syn_test',None,'''math n1=700 d1=0.01 o1=0.0 
                        output="(%g+%g)*exp(-2*(x1-%g-%g)^2)*cos(2*3.14*%g*(x1-%g-%g))"'''  
                        %(A0,0.2,t0,0.2,f0,t0,0.2)) 
Result('data_analy',['data','syn_test'],'''cat axis=2 ${SOURCES[1]} | graph dash=0,1 wanttitle=n label1=Time unit1=s 
                        labelsz=6 labelfat=4  plotfat=5  screenratio=0.6 screenht=8''')

k=0
l2result=[] 
filtresult=[]
for j in range (16): 
    for i in range (21):
        k=k+1 
        syn='syn_%4.4d'%k 

        filt='sfilt_%4.4d'%k
        pred='spred_%4.4d'%k

        l2diff='l2diff_%4.4d'%k
        filtdiff='filtdiff_%4.4d'%k

        dA=-0.5+j*0.1
        dt=-1.0+i*0.1 
        #dt=-0.6+i*0.1 

        Flow(syn,None,'''math n1=700 d1=0.01 o1=0.0 
                         output="(%g+%g)*exp(-2*(x1-%g-%g)^2)*cos(2*3.14*%g*(x1-%g-%g))"'''  
                         %(A0,dA,t0,dt,f0,t0,dt)) 
       
        # least-squares 
        Flow(l2diff,[syn,'data'],'''math data=${SOURCES[1]} output="(input-data)^2" | 
                                    stack axis=1''') 

        
        # lpf 
        #Flow([filt,pred],['sdata',syn],'''lpf match=${SOURCES[1]} pred=${TARGETS[1]} rect1=10 rect2=5 niter=100''')
        Flow([filt,pred],['sdata',syn],'''lpf match=${SOURCES[1]} pred=${TARGETS[1]} niter=500''')
        Flow(filtdiff,filt,'''misfit_calcmisfit_filt''')  


        l2result.append(l2diff)
        filtresult.append(filtdiff)
    

Flow('ZMISFIT_L2_cat',l2result,'cat axis=1 ${SOURCES[1:-1]}') 
Flow('ZMISFIT_L2','ZMISFIT_L2_cat','''put n1=21 d1=0.1 o1=-1.0 n2=16 d2=0.1 o2=-0.5 | 
                   remap1 n1=201 d1=0.01 | transp | remap1 n1=151 d1=0.01 ''') 
Flow('ZMISFIT_L2_scale','ZMISFIT_L2','scale axis=2') 
Plot('ZMISFIT_L2_scale','''grey color=j allpos=y scalebar=y wanttitle=n screenratio=0.45
                     label2=dt unit2=s label1=dA barlabel=Misfit labelsz=10 labelfat=5 wherexlabel=b''')
Plot('ZMISFIT_L2_1D','ZMISFIT_L2_scale','''window n1=1 f1=100| graph wanttitle=n screenratio=0.45 
                      label1=dt unit1=s label2=Misfit labelsz=10 labelfat=5''') 


Flow('ZMISFIT_filt_cat',filtresult,'cat axis=1 ${SOURCES[1:-1]}') 
Flow('ZMISFIT_filt','ZMISFIT_filt_cat','''put n1=21 d1=0.1 o1=-1.0 n2=16 d2=0.1 o2=-0.5 |
                      remap1 n1=201 d1=0.01 | transp | remap1 n1=151 d1=0.01''') 
Flow('ZMISFIT_filt_scale','ZMISFIT_filt','scale axis=2') 
Plot('ZMISFIT_filt_scale','''grey color=j allpos=y scalebar=y wanttitle=n screenratio=0.45
                       label2=dt unit2=s label1=dA barlabel=Misfit labelsz=10 labelfat=5 wherexlabel=b''')
Plot('ZMISFIT_filt_1D','ZMISFIT_filt_scale','''window n1=1 f1=100| graph wanttitle=n screenratio=0.45 
                      label1=dt unit1=s label2=Misfit labelsz=10 labelfat=5''') 


Result('ZMISFIT_analy',['ZMISFIT_L2_scale','ZMISFIT_filt_scale'],'OverUnderIso')
Result('ZMISFIT_analy_1D',['ZMISFIT_L2_1D','ZMISFIT_filt_1D'],'OverUnderIso')

End()
