/* This file is automatically generated. DO NOT EDIT! */

#ifndef _cosft3_h
#define _cosft3_h


float cosft_dk(int n, float d);
/*< wavenumber sampling for cosine FT >*/


void cosft3(bool inv,               /* forward or inverse */ 
	    int n1, int n2, int n3, /* dimensions */
	    float ***data           /* data [n3][n2][n1] */);
/*< 3-D transform (in place) >*/


void cosft12(bool inv,               /* forward or inverse */ 
	     int n1, int n2, int n3, /* dimensions */
	     float ***data           /* data [n3][n2][n1] */);
/*< transform first two coordinates (in place) >*/


void cosft2(bool inv,       /* forward or inverse */ 
	    int n1, int n2, /* dimensions */
	    float **data    /* data [n2][n1] */);
/*< 2-D transform (in place) >*/


void cosft1(bool inv,    /* forward or inverse */ 
	    int n1,      /* dimensions */
	    float *data  /* data [n3][n2][n1] */);
/*< 1-D transform (in place) >*/


void cosfthx(bool inv,               /* forward or inverse */ 
	     int n1, int n2, int n3, /* dimensions */
	     float ***data           /* data [n3][n2][n1] */);
/*< transform last two coordinates x h(in place) >*/


void cosftz(bool inv,               /* forward or inverse */ 
	     int n1, int n2, int n3, /* dimensions */
	     float ***data           /* data [n3][n2][n1] */);
/*< transform first coordinate z (in place) >*/

#endif
