/* This file is automatically generated. DO NOT EDIT! */

#ifndef _lap_h
#define _lap_h


void lap1_init(int n /* */);
/*< initialize >*/


   
void lap1(float *uin /* input */, 
          float *uout /*output*/, 
          int order /*Laplacian order*/);
/*< 1-D second-order derivative >*/

#endif
