/* This file is automatically generated. DO NOT EDIT! */

#ifndef _srcsm_h
#define _srcsm_h


void srcsm_init(float dz, float dx/*grid size*/);
/*< initialization >*/


void srcsm_close(void);
/*< free memory allocation>*/


void source_smooth(float **source /*source matrix*/, 
                   int iz /*source index*/, 
                   int ix /*source index*/,
                   float val/*source value*/);
/*< smooth source input >*/


void source_smooth1(float dz /*grid size*/,
                    float dx /*grid size*/, 
                    float alpha /*decay parameter*/, 
                    float **source /*source matrix*/, 
                    int iz /*source index*/, 
                    int ix /*source index*/,
                    float val/*source value*/);
/*< smooth source input >*/

#endif
