/* This file is automatically generated. DO NOT EDIT! */

#ifndef _v0_h
#define _v0_h


#include "vconstant.h"
   
float v0_cal(float *v /* v[nxb] */ ,
             int nxb /* size of v */ , 
             int v0kind /* the kind of v0, 0:rms 1:mean 2:minimum 3:maximum*/);
/*< calculate v0 >*/

#endif
