from rsf.proj import *

Fetch('marmvel.hh','marm')
Flow('marm','marmvel.hh','dd form=native')
Plot('marm','window j1=2 j2=2 | grey allpos=y screenratio=.327 screenht=4.7 wanttitle=n')

for order in (1,2):
    eiko = 'eiko%d' % order
    Flow(eiko,'marm','eikonal order=%d yshot=5000 b1=5 b2=5' % order)
    Plot(eiko,
         '''
         window j1=2 j2=2 |
         contour screenratio=.327 screenht=4.7 wanttitle=n wantaxis=n dash=%d nc=200
         ''' % (0,3)[order-1])

Result('marmousi','marm eiko1 eiko2','Overlay')


End()
