from rsf.proj import *

Fetch('blast.46.H','blast')

Flow('data','blast.46.H','dd form=native | window f1=150 n1=150')
Flow('pef lag','data',
     'hpef lag=${TARGETS[1]} maskin=$SOURCE a=7,2,2')
Flow('miss','data pef','miss padin=10 filt=${SOURCES[1]} prec=0')

for case in ['data','miss']:
    Flow(case+'bin',case,'byte clip=.0007')
    plots = []

    for wind in range(12):
        plots.append(case + str(wind))
        Plot(plots[wind],case+'bin',
             '''window n3=1 f3=%d |
             grey crowd=0.95 wanttitle=n
             ''' % wind)

    Plot(case+'top',plots[0:4],'SideBySideAniso')
    Plot(case+'mid',plots[4:8],'SideBySideAniso')
    Plot(case+'bot',plots[8:12],'SideBySideAniso')
    Plot(case,map(lambda x: case+x,['top','mid','bot']),'OverUnderAniso')
Result('passfill','data miss','SideBySideAniso')

###########################################################################
End()
