const char * sdoc[] = {
" Driver for acoustic constant density centered difference modeling in ",
" 2D or 3D. Outputs pressure traces at specified sample rates, arbitrary",
" receiver positions, and/or movie frames of pressure. Array sources with",
" arbitrarily many traces at arbitrary locations, receivers at arbitrary ",
" locations. Uses centered difference scheme of order 2 in time and 2k in",
" space, k=1, 2, or 4, derived from 2nd order pressure form of acoustodynamics.",
" Either pressure-free (reflecting) or absorbing (PML) boundary conditions on",
" boundary faces of simulation hypercube. Optionally parallelized at both loop",
" (domain decomposition) and task (shot) levels.",
" ",
" Authors: Muhong Zhou, William W. Symes",
" ",
" Typical parameter list. May be copied, edited, and used for input: place",
" in file \"parfile\", invoke modeling command by ",
" ",
" sfacd par=parfile [Madagascar install] ",
" ",
" or ",
" ",
" acd.x par=parfile [standalone install]",
" ",
" Given values are defaults, non-optional values in corner brackets.",
" ",
" -------------------------------- cut here ------------------------------",
" ",
" INPUT DATA FOR iwave",
" ",
" ------------------------------------------------------------------------",
" FD:",
" ",
"          order = 2          spatial half-order",
"            cfl = 0.75       proportion of max dt/dx",
"           cmin = 1.0        min permitted velocity (m/ms) - sanity check",
"           cmax = 4.5        max permitted velocity (m/ms) - used in dt comp",
"          fpeak = 0.010      nominal central frequency (KHz)",
" ",
" ------------------------------------------------------------------------",
" PML info: layer thickness in WL at fpeak, cmax. Set = 0.0 for reflecting",
" boundary",
" ",
"            nl1 = 0.0         axis 1 - low end",
"            nr1 = 0.0         axis 1 - high end",
"            nl2 = 0.0         axis 2 - low end",
"            nr2 = 0.0         axis 2 - high end",
"            nl3 = 0.0         axis 3 - low end",
"            nr3 = 0.0         axis 3 - high end",
" ",
" ------------------------------------------------------------------------",
" Source info:",
" ",
"         source = <path>      path to input source data file (traces), ",
" 	                       SU format",
"        sampord = 1           spatial interp order - 0 (nr nbr) or ",
"                              1 (multilin)",
" ",
" ------------------------------------------------------------------------",
" Trace info:",
" ",
"       hdrfile  = <path>      input prototype trace file, SU format",
"      datafile  = <path>      output data file, SU format - headers",
"                              from hdrfile, trace data from modeling",
" ",
" ------------------------------------------------------------------------",
" Movie info:",
"     moviestep  = 0.0         time between movie frames (= 0.0,",
"                              or do not include, for no movie)",
" ",
" ------------------------------------------------------------------------",
" Model info:",
" ",
"       velocity = <path>      path to input velocity file, RSF format",
" ",
" ------------------------------------------------------------------------",
" MPI info:",
" ",
"        mpi_np1 = 1           number of subdomains along axis 1",
"        mpi_np2 = 1           number of subdomains along axis 2",
"        mpi_np3 = 1           number of subdomains along axis 3",
"        partask = 1           number of shots to execute in parallel",
" ",
" ------------------------------------------------------------------------",
" Output info:",
" ",
"       printact = 0           output at every time step",
"                              0 - none",
"                              1 - time step index",
"                              2 - diagnostic messages from main routines",
"                              > 2 - much more, useful only for serious ",
"                                 debugging",
"        dump_pi = 0           dump parallel/dom. decomp info",
"       dump_lda = 0           dump grid data for allocated arrays",
"       dump_ldc = 0           dump grid data for computational arrays",
"       dump_ldr = 0           dump grid data for receive buffers",
"       dump_lds = 0           dump grid data for send buffers",
"      dump_term = 0           dump trace header data",
" ",
" -------------------------------- cut here ------------------------------",
NULL };
