from rsf.proj import *
import math

SConscript('../segy/SConstruct')

Flow(['line5320.rsf','line5320_hdr.rsf'],'../segy/DeconShots3.rsf',
    '''
      sftahsort input=$SOURCE sort="iline:5320,5320 xline offset" \
      | sftahmakeskey pkey=xline skey=cdpt verbose=1 \
      | sftahwrite \
        verbose=1 \
	label3=xline o3=1001 n3=1943 d3=1 \
	label2=cdpt  o2=1    n2=12   d2=1 \
	output=${TARGETS[0]}
    ''',stdout=0,stdin=0)

stkfiles=[]
for vel in range(1300, 1950,50):
    print('vel=',vel)
    stkfiles.append("stk%d.rsf"%vel)
    print("stkfiles=",stkfiles)
    
    Flow(['stk%d.rsf'%vel , 'stk%d_hdr.rsf'%vel ],'line5320.rsf',
	'''
      	sftahsort input=$SOURCE sort="xline offset"
      	| sftahnmo tnmo=0 vnmo=%d str=.2 \
      	| sftahstack key=xline \
      	| sftahwrite \
          verbose=1
	  label2=xline o2=1001 n2=1882 d2=1 
	  output=${TARGETS[0]}
    	'''%vel,stdout=0,stdin=0)

print("final stkfiles=",stkfiles)
Flow("velscan",stkfiles,
     '''
     sfcat ${SOURCES[0:-2]} 
     | sfput label3="vel" d3=50 o3=1300     
     ''',stdin=0)

Result('velscan','sfwindow max1=.3 n2=600 |sfgrey title="velocity scan"')
Result('velscan1','velscan','sfwindow max1=1 n2=600 |sfgrey title="velocity scan"')

#Result('stk1300',
#        '''
#	   sfwindow max1=.6 \
#	   |  sfgrey title="stk v=1300"
#	''')
 	
End()
