from rsfproj import *

Fetch('galilee.h','galilee')

Flow('gal','galilee.h','dd form=native')
Flow('clip','gal','window f1=2 | mask max=-212')
Flow('gal2',['gal','clip'],'headerwindow mask=${SOURCES[1]}')

Flow('mesh','gal2',
     '''window f1=2 | math output="-input-212" |
     bin interp=1 nx=560 ny=880 head=$SOURCE
     xkey=0 ykey=1
     xmin=198 xmax=212 ymin=233 ymax=257''')
Result('mesh',
       '''
       grey gpow=0.7 allpos=y
       pclip=94 yreverse=n transp=n
       title="Binned" label2="North-South (km)" label1="West-East (km)"
       ''')

#Flow('fill','mesh','miss2 filt1=10 niter=30 force=n eps=0.275')
Flow('fill','mesh','miss2 filt1=10 niter=30 force=n eps=1 shape=n')
grey = '''igrad |
       grey gpow=0.7
       pclip=94 yreverse=n transp=n
       title="Filled" label2="North-South (km)" label1="West-East (km)"
       '''
Result('fill',grey)
Result('cross','fill',
       '''window n2=1 f2=300 n1=440 f1=80 |
       scale dscale=-1 |
       dots dots=0 connect=4 label1="West-East (km)"
       ''')

fills = []
for iter in range(1,15):
    fill = 'fill%d' % iter
    Flow(fill,'mesh','miss2 filt1=10 niter=%d force=n eps=1 shape=n' % iter)
    Plot(fill,grey)
    fills.append(fill)
Plot('movie',fills,'Movie')

###########################################################################

End()

# 	$Id: SConstruct 691 2004-07-04 19:28:08Z fomels $	
