from rsf.proj import *
import os
remote='"/Volumes/HD-PCFU3/newzealand//Taranaiki\ B\ asin/PARIHAKA-3D/C40502_Parihaka_M3D_Final_PSTM_Far_Stack_IL825-2815.SEGY"'
# before running past into command line:
# ln -s /Volumes/HD-PCFU3/newzealand//Taranaiki\ B\ asin/PARIHAKA-3D/C40502_Parihaka_M3D_Final_PSTM_Far_Stack_IL825-2815.SEGY farstack.sgy
# or ln -s /Volumes/data/newzealand/Taranaiki\ B\ asin/PARIHAKA-3D/C40502_Parihaka_M3D_Final_PSTM_Far_Stack_IL825-2815.SEGY farstack.sgy
# or ln -s /Volumes/data/newzealand/Taranaiki\ B\ asin/PARIHAKA-3D/C40502_Parihaka_M3D_Final_PSTM_Mid_Stack_IL824-2813.SEGY midstack.sgy
# or ln -s /Volumes/data/newzealand/Taranaiki\ B\ asin/PARIHAKA-3D/C40502_Parihaka_M3D_Final_PSTM_Near_Stack_IL824-2811.SEGY nearstack.sgy

# this does not work:   Flow('farstack.sgy',remote,'ln -s "${SOURCE} ${TARGET}"')

#https://s3.amazonaws.com/open.source.geoscience/open_data/newzealand/Taranaiki_Basin/PARIHAKA-3D/Parihaka_PSTM_full_angle.sgy

for file in ['far', 'mid', 'near']:
   Flow(['%sstack.rsf'%file,'%sstack_hdr.rsf'%file,
      '%sstack.thdr'%file,'%sstack.bhdr'%file],
     '%sstack.sgy'%file,
     '''
     sfsegyread
        tfile=${TARGETS[1]} 
        hfile=${TARGETS[2]}  
	bfile=${TARGETS[3]} 
     ''')
   Flow('%sheaderattr.txt'%file,'%sstack_hdr.rsf'%file,
     'sfheaderattr > $TARGET && /bin/cat $TARGET',stdout=-1)
   #sftahread input=farstack.rsf | sftahgethw key=sx,gx,offset >/dev/null
   #sfheaderattr <farstack_hdr.rsf 
   # map traces from sequential segy order to 3d volume using header
   Flow(['%simage.rsf'%file,'%simage_hdr.rsf'%file],
        ['%sstack.rsf'%file,'%sstack_hdr.rsf'%file],
     '''
     sftahsort \
          input=${SOURCES[0]} \
	  sort="iline:1736,2657 xline:4200,5325"
	  verbose=1 \
     | sftahwrite \
          output=${TARGETS[0]} \
          label2="xline" o2=4200 n2=1126 d2=1 \
          label3="iline" o3=1736 n3=922 d3=1
	  verbose=1
     ''',stdout=0, stdin=0)
   Flow('%strim_image'%file,'%simage'%file,'sfwindow n1=1168')
   Flow('Parihaka_PSTM_%s_stack.sgy'%file,
     '%strim_image.rsf %simage_hdr.rsf %sstack.thdr'%(file,file,file),
     '''
     sfsegywrite 
        tfile=${SOURCES[1]} 
        hfile=${SOURCES[2]}   
     ''')
   Result("%strim_image"%file,
          "sfwindow j3=50 | sfgrey title='Parihaka 3d %s'"%file)
   Plot("%simage2415"%file,"%strim_image"%file,
     """
     sfwindow min3=2415 max3=2415
     | sfgrey title='Parihaka 3d %s stack line 2415'
     """%file)
   Plot("%simagex5031"%file,"%strim_image"%file,
     """
	sfwindow min2=5031 max2=5031
	| sfput label2='xline' 
	| sfgrey title='Parihaka 3d %s stack xline 5031'
     """%file)
   Result("%silxl"%file,"%simage2415 %simagex5031"%(file,file),'SideBySideAniso')
   Result("%sil"%file,"%simage2415"%file,'SideBySideAniso')
   Result("%sxl"%file,"%simage2415"%file,'SideBySideAniso')
   Result("%simage3d"%file,"%simage"%file,
       '''
       sfwindow n1=1168 
       | byte 
       | grey3 frame1=600 frame2=550 frame3=450 title='Parihaka 3D %s'
       '''%file)
   Result("%simage3d1"%file,"%simage"%file,
       '''
       sfwindow n1=1168 
       | byte 
       | grey3 frame1=600 frame2=550 frame3=450 title='Parihaka 3D %s' flat=n
       '''%file)



Result("ilcmp","image2415  ../displayin/image2415.vpl",'SideBySideAniso')
Result("xlcmp","imagex5031 ../displayin/imagex5031.vpl",'SideBySideAniso')





End()
