import os, sys, string
sys.path.append('../..')
import configure

src = '''
clip dashvec dither dupside error fatvec geth greycorr intersect solve
sort vecoutline vptodev
'''

try: # distribution version
    Import('env root libdir')
    env = env.Clone()
except: # local version
    env = configure.Debug()
    root = None
    SConscript('../../plot/lib/SConstruct')

env.Prepend(CPPPATH=['../../include'])

sources  = map(lambda x: x+'.c',Split(src))
includes = map(lambda x: x+'.h',Split(src))

objects = []
for source in Split(src):
    env.Include(source,prefix='pen_')
    obj = env.StaticObject(source+'.c')
    env.Depends(obj,source+'.h')
    objects.append(obj)

inc = env.Command('util.h',includes,Action(configure.merge))
lib = env.StaticLibrary('penutil',objects)
