from rsf.proj import *

Fetch('avo.HH','avo')
Flow('avo','avo.HH','dd form=native')

Flow('b1','avo','window f1=50 n1=250 j2=2')
Flow('n','b1','window n2=12')
Flow('ms','b1','window f2=12 n2=12 | scale dscale=0.80')
Flow('f','b1','window f2=24')
Flow('bsr','n ms f','cat axis=2 ${SOURCES[1:3]} | put label1=Time unit1=s label2=Offset unit2=km')

Plot('seafloor',None,'box x0=8.168333 y0=6.953333 label="seafloor" xt=1 yt=-1')
Plot('bsr-ann',None, 'box x0=5.533333 y0=3.100000 label="BSR" xt=-1 yt=1')

Plot('bsr','wiggle wanttitle=n transp=y yreverse=y poly=y wheretitle=t')

Result('bsr-ann','bsr seafloor bsr-ann','Overlay')

Flow('nb1','avo','window f1=200 n1=100 j2=2')
Flow('nn','nb1','window n2=12')
Flow('nms','nb1','window f2=12 n2=12 | scale dscale=0.80')
Flow('nf','nb1','window f2=24')
Flow('bsr-nmo','nn nms nf','cat axis=2 ${SOURCES[1:3]} | put label1=Time unit1=s label2=Offset unit2=km')

tp0=4.975 
twidth=0.025
tp1=tp0+twidth

Flow('bsr-picks','bsr-nmo','scale dscale=0.375 | window min1=%g max1=%g | sfmin axis=1' % (tp0,tp1))
Result('bsr-picks',
       '''
       graph  wanttitle=n label1=angle unit1="degree" min2=-0.5 max2=0 symbol=+ symbolsz=5
       label2="reflection amplitude" unit2=
       ''')

End()
