from rsf.proj import *

Flow('plane',None,
     '''
     spike n1=64 n2=32 d2=1 o2=1 label2=Trace unit2=
     nsp=3 k1=8,20,32 k2=4 l2=28 p2=2,1,0 
     ''')

Flow('time.asc',None,
     'echo 0.0 115 402 696 900 1068 1586 2112 2738 2983 n1=10 in=$TARGET data_format=ascii_float')
Flow('vel.asc',None,
     'echo 1521 1719 1827 1936 2030 2471 2774 3302 3539 n1=10 in=$TARGET data_format=ascii_float')
Flow('velt','vel.asc time.asc',
     'invbin1 head=${SOURCES[1]} nx=3000 dx=1 x0=0 | dd form=native')
Plot('velt',
     '''
     graph wanttitle=n transp=y yreverse=y 
     label1=Time unit1=s label2=Velocity unit2=m/s
     ''')

Flow('velz','velt','time2depth velocity=$SOURCE intime=y nz=128 dz=2')
Plot('velz',
     '''
     graph wanttitle=n transp=y yreverse=y 
     label1=Depth unit1=m label2=Velocity unit2=m/s
     ''')
Result('vel','velt velz','SideBySideAniso')

Flow('velt2','velt','spray axis=2 n=32')
Flow('depth','plane velt2',
     '''
     time2depth velocity=${SOURCES[1]} intime=y nz=128 dz=2 |
     put label1=Depth unit1=m
     ''')

Flow('velz2','velz','spray axis=2 n=32')
Flow('plane2','depth velz2',
     'depth2time velocity=${SOURCES[1]} nt=64 dt=0.004') 

for plot in ('plane','depth','plane2'):
    Plot(plot,
         '''
         wiggle clip=1 transp=y yreverse=y poly=y
         wanttitle=n wheretitle=b wherexlabel=t
         ''')

Result('depth','plane depth', 'SideBySideAniso')
Result('plane','plane plane2','SideBySideAniso')

End()
