from rsf.proj import *

n1=1201
n2=3201
o1=0
o2=10.025 
dx=0.025
dz=0.025
nt=10001
dt=0.001
nb=50
n0=2

vstr = 'sigsbee2a_stratigraphy.sgy'
Fetch(vstr,'sigsbee')
Flow('zvstr',vstr,'segyread read=data')

Flow('zvel','zvstr',
     '''
     put d1=0.025 o2=10.025 d2=0.025
     label1=Depth unit1=kft label2=Lateral unit2=kft |
     scale dscale=0.001
     ''')

Result('zvel',
       '''
       grey title=Velocity titlesz=7 color=j
       screenratio=0.375 screenht=4 labelsz=5 scalebar=y
       mean=y
       ''')

Flow('zvel0','zvel','math output="0.5*input"')


# Compute approximate reflectivity
Flow('zref','zvel',
     '''
     depth2time velocity=$SOURCE nt=%d dt=%g |
     ai2refl | ricker1 frequency=15 |
     time2depth velocity=$SOURCE | 
     pad beg1=%d end1=%d beg2=%d end2=%d
     '''%(nt,dt,nb,nb,nb,nb))
Result('zref','grey title=Reflectivity titlesz=7 labelsz=5')


Flow('data','zref zvel0','rtm2d vel=${SOURCES[1]} nb=%d n0=%d nt=%d dt=%g adj=n'%(nb,n0,nt,dt))
Result('data','grey title="Zero-Offset Data" grid=y label1=Time unit1=s label2=Distance unit2=km')

#sfdottest sfrtm2d mod=zref.rsf dat=data.rsf vel=zvel0.rsf nb=20 n0=2 nt=2300 dt=0.001

# ================= reverse-time migration ==================
Flow('image-rtm','data zvel0','rtm2d vel=${SOURCES[1]} n0=%d nb=%d adj=y'%(n0,nb))
Result('image-rtm','window n1=%d f1=%d n2=%d f2=%d| grey title=RTM titlesz=7'%(n1,nb,n2,nb))

# sfdottest sfrtm2d mod=image-rtm.rsf dat=data.rsf vel=zvel0.rsf nb=20 n0=2 nt=2300 dt=0.001


# sfconjgrad sfrtm2d mod=image-rtm.rsf < data.rsf vel=zvel0.rsf nb=20 n0=2 nt=2300 dt=0.001 niter=5 > invs.rsf
# ============== least-squares migration ====================
Flow('image-lsrtm','data zvel0','lsrtm2d vel=${SOURCES[1]} n0=%d nb=%d nt=%d dt=%g niter=5 verb=y'%(n0,nb,nt,dt))

#Flow('image-lsrtm','data zvel0 image-rtm',
#	'''
#	sfconjgrad sfrtm2d split=2 nb=20 n0=2 nt=2300 dt=0.001 vel=${SOURCES[1]} mod=${SOURCES[2]} niter=5
#	''')

Result('image-lsrtm',
	'''
	window n1=%d f1=%d n2=%d f2=%d | 
	put label1=Depth unit1=km label2=Lateral unit2=km |
	grey title="LSRTM"
	'''%(n1,nb,n2,nb))
End()
