from rsfproj import *

sgy = 'ALL-gathers.sgy'

# Download data
Fetch(sgy,'dragon')

# Convert from SEGY to RSF
Flow('gathers tgathers gathers.asc gathers.bin',sgy,
     '''
     segyread tfile=${TARGETS[1]} hfile=${TARGETS[2]} bfile=${TARGETS[3]}
     ''')

# Collect CMP bins

Flow('bin','gathers','intbin xk=cdpt yk=cdp')

Flow('off','tgathers',
     '''
     dd type=float |
     headermath output=offset |
     intbin xk=cdpt yk=cdp head=$SOURCE 
     ''')

Flow('scn','bin off',
     'vscan offset=${SOURCES[1]} semblance=y half=n v0=1400 dv=20 nv=101')

End()
