  " ",
  " ----------------------------------- ACDEFWI ---------------------------------",
  " ",
  " Acoustic constant density extended full waveform inversion",
  " iwave/acd/main/acdefwi.cc", 
" ",
  " ------------------------- begin acdefwi parameters -------------------------",
  " ",
    " I/O:",
  "          data = <path>      input data file, SU format ",
  "           csq = <path>      input vel-squared reference file",
  "        csqext = <path>      input extended vel-squared reference file",
  "   init_csqext = <path>      path to initial csqext file (may be same as csqext)",
  "  final_csqext = <path>      path to final csqext file",
  "        source = <path>      path to input source data file (traces), ",
  "                             SU format, source position(s) indicated by",
  "                             RECEIVER coordinates (gx, gy, gelev) - may",
  "                             prepare input source with correct headers",
  "                             using eg. towed_array.x or planewave utilities",
    " ",
    " Optional I/O:",
  "       datamut = \"\"          path to muted data file - optional output",
  "       dataest = \"\"          data estimated from final model - optional output",
  "       datares = \"\"          data residual from final model - optional output",
  "       outfile = \"\"          verbose output - default is terminal",
  "      printact = 0           output at every time step",
  "                             0 - none",
  "                             1 - time step index",
  "                             2 - diagnostic messages from main routines",
  "                             > 2 - much more, useful only for serious ",
  "                                debugging",
  "       dump_pi = 0           dump parallel/dom. decomp info",
  "      dump_lda = 0           dump grid data for allocated arrays",
  "      dump_ldc = 0           dump grid data for computational arrays",
  "      dump_ldr = 0           dump grid data for receive buffers",
  "      dump_lds = 0           dump grid data for send buffers",
  "     dump_term = 0           dump trace header data",
    " ",
    " FD:",
  "         order = 2           spatial half-order",
  "           cfl = 0.75        proportion of max dt/dx",
  "          cmin = 1.0         min permitted velocity (m/ms) - sanity check, m/ms",
  "          cmax = 4.5         max permitted velocity (m/ms) - used in dt comp m/ms",
  "       sampord = 1           spatial interp order for sampling or adjoint",
  "                             sampling trace data to/from grid - 0 (nr nbr) ",
  "                             or 1 (multilin)",  
  "       mpi_np1 = 1           number of subdomains along axis 1",
  "       mpi_np2 = 1           number of subdomains along axis 2",
  "       mpi_np3 = 1           number of subdomains along axis 3",
  "       partask = 1           number of shots to execute in parallel",
  " ",
    " Optimization:",

  "     OptMethod = lbfgs       optimization method - current choices are ",
  "                             lbfgs (default) and trcg",
    " ",
  " --------------------------- end acdefwi parameters -------------------------",

