from rsf.proj import *

# create a model
Flow('model',None,'math n1=301 d1=0.01 o1=0 n2=1001 d2=0.01 o2=0 output="1+2*x1+0.5*x2"')

# plot the model
Plot('model','model','grey color=j scalebar=y')

# do a ray-tracing
Flow('ray','model','rays2 yshot=5 nt=500 dt=0.001 a0=180 nr=1')

# plot the ray
Plot('ray','graph transp=y yreverse=y')

# overlay model and ray
Result('overlay','model ray','Overlay')

End()
