from rsfproj import *

private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

vel = 'velcassis240x240prep.segy'
dat = 'datacassis240x240prep.segy'

for file in ('vel','data'):
    segy = file+'cassis240x240prep.segy'
    Fetch(segy,'cassis',private)

    Flow([file,'t'+file,'./h'+file,'./b'+file],segy,
         '''
         segyread tape=$SOURCE
         tfile=${TARGETS[1]} hfile=${TARGETS[2]} bfile=${TARGETS[3]}
         ''',stdin=0)

Result('vel',
       '''
       put d2=0.01 |
       grey color=j allpos=y bias=1450 scalebar=y
       title="Velocity Model" barreverse=y
       label2="Lateral (km)" label1="Depth (km)"
       ''')

Flow('dat','data',
     '''
     intbin xk=tracf yk=fldr |
     put o3=5 d3=0.025 o2=0 d2=0.0125
     ''')

Flow('czo','dat','window n2=1 max1=3.5')

Result('czo',
       'grey title="Zero Offset" label2="Lateral (km)" label1="Time (s)" ')

Flow('cd0','czo','dip rect1=40 rect2=10')

Result('cd0',
       '''
       grey color=j scalebar=y
       title="Zero Offset Slope" 
       label2="Lateral (km)" label1="Time (s)"
       ''')

Flow('cdi0','czo cd0','pwd dip=${SOURCES[1]}')

Result('cdi0',
       'grey title="Diffractions" label2="Lateral (km)" label1="Time (s)" ')

Flow('csi0','czo cd0',
     '''
     pwdsmooth2 dip=${SOURCES[1]} rect1=1 rect2=2 |
     add ${SOURCES[0]} scale=-1,1
     ''')

Result('csi0',
       '''
       grey title="Diffractions (Shaping)"
       label2="Lateral (km)" label1="Time (s)"
       ''')

Flow('shot','dat','window n3=1 f3=210')

Plot('shot',
     'grey title="Shot Gather" label2="Half-Offset (km)" label1="Time (s)" ')

Flow('cmp','dat',
     '''
     math output=0 |
     interleave $SOURCE axis=3 |
     put d3=0.0125 o3=4.9875 |
     shot2cmp
     ''')

Flow('dat2','cmp',
     '''
     reverse which=2 opt=n |
     window n2=140 |
     cat axis=2 $SOURCE |
     cmp2shot |
     window n3=421 min3=5 j3=2 
     ''')

End()
