# Generated by scons -nQ > plot.sh
/Users/maxu1/rsf/bin/sfmath n1=41 o1=-4 d1=.2 output=".5*x1" > y1.rsf
< y1.rsf /Users/maxu1/rsf/bin/sfmath output="sin(x1)" > y2.rsf
< y1.rsf /Users/maxu1/rsf/bin/sfmath sin=y2.rsf output="input-sin" > y3.rsf
< y3.rsf /Users/maxu1/rsf/bin/sfgraph title="0.5x-sin(x)" > Fig/fig1.vpl
< y3.rsf /Users/maxu1/rsf/bin/sfgraph title="0.5x-sin(x)" symbol=o symbolsz=12 grid=y min1=-4 max1=4 > Fig/fig2.vpl
< y3.rsf /Users/maxu1/rsf/bin/sfgraph wanttitle=n wantaxis=n > line.vpl
< y3.rsf /Users/maxu1/rsf/bin/sfgraph title="0.5x-sin(x)" symbol=o symbolsz=12 > dots.vpl
/Users/maxu1/rsf/bin/vppen erase=o vpstyle=n line.vpl dots.vpl > Fig/fig3.vpl
< y1.rsf /Users/maxu1/rsf/bin/sfcat y2.rsf y3.rsf axis=2 > y4.rsf
< y4.rsf /Users/maxu1/rsf/bin/sfgraph title="0.5x,sin(x),0.5x-sin(x)" label1=x label2=y > Fig/fig4.vpl
/Users/maxu1/rsf/bin/sfmath n1=101 d1=2 n2=201 d2=2 output="1500+5*x1" > vb.rsf
< vb.rsf /Users/maxu1/rsf/bin/sfmath output="-exp(-.002*((x1-100)*(x1-100)+(x2-200)*(x2-200)))*450" > v1.rsf
< vb.rsf /Users/maxu1/rsf/bin/sfadd scale=1,1 v1.rsf > v.rsf
< v.rsf /Users/maxu1/rsf/bin/sfgrey title=Velocity color=j bias=1500 scalebar=y barreverse=y > Fig/fig5.vpl
< v.rsf /Users/maxu1/rsf/bin/sfeikonal yshot=200 > eik.rsf
< eik.rsf /Users/maxu1/rsf/bin/sfcontour nc=45 title=Traveltime plotfat=5 > Fig/fig6.vpl
< v.rsf /Users/maxu1/rsf/bin/sfgrey bias=1500 min1=0 max1=200 min2=0 max2=400 wanttitle=n wantaxis=n > v.vpl
< eik.rsf /Users/maxu1/rsf/bin/sfcontour title=Overlay nc=45 plotfat=5 min1=0 max1=200 min2=0 max2=400 > eik.vpl
/Users/maxu1/rsf/bin/vppen erase=o vpstyle=n v.vpl eik.vpl > Fig/fig7.vpl
retrieve(["shots.hh"], [])
< shots.hh /Users/maxu1/rsf/bin/sfdd form=native type=float | /Users/maxu1/rsf/bin/sfwindow n1=480 n2=24 | /Users/maxu1/rsf/bin/sftransp plane=23 | /Users/maxu1/rsf/bin/sfput label1=Time unit1=sec label3=Offset unit3=m label2=Shot unit2=m > shots.rsf
< shots.rsf /Users/maxu1/rsf/bin/sfbyte | /Users/maxu1/rsf/bin/sfgrey3 frame1=0 frame2=24 frame3=0 point1=.75 point2=.65 wanttitle=n flat=n title="Data" > Fig/fig8.vpl
/Users/maxu1/rsf/bin/sfspike n1=500 n2=50 k1=100,300 nsp=2 o2=1 d2=1 | /Users/maxu1/rsf/bin/sfricker1 frequency=5 > spike.rsf
< spike.rsf /Users/maxu1/rsf/bin/sfwindow n1=1 | /Users/maxu1/rsf/bin/sfnoise type=n rep=y seed=2005 range=3 > offset.rsf
< offset.rsf /Users/maxu1/rsf/bin/sftransp | /Users/maxu1/rsf/bin/sfheadersort head=offset.rsf > offset2.rsf
< spike.rsf /Users/maxu1/rsf/bin/sfwindow n2=1 | /Users/maxu1/rsf/bin/sfmath output="3+0.5*x1" > velocity.rsf
< spike.rsf /Users/maxu1/rsf/bin/sfinmo offset=offset2.rsf velocity=velocity.rsf half=n > data.rsf
< data.rsf /Users/maxu1/rsf/bin/sfwiggle title= label2="Trace Number" unit2= yreverse=y transp=y poly=y > Fig/fig9.vpl
