###########################################################################
import sys, os

root = os.environ.get('RSFROOT')
libdir = os.path.join(root,'lib')
incdir = os.path.join(root,'include')
sys.path.append(libdir)

###########################################################################

import rsfproj

proj = rsfproj.Project()

############################################################################

test = 'spike n1=1000 n2=100 n3=10 nsp=1 k1=500 | %s.exe clip=0.5 | attr'

############################################################################
# C API
############################################################################

proj.Program('clip.c')
ctest = proj.Flow('c','clip.exe',test % 'clip',suffix='.attr',stdin=0)
Default(ctest)

api = proj.get('API','').lower().split(',')

############################################################################
# C++ API
############################################################################

if 'c++' in api:
    proj.Program('clip.cc',OBJSUFFIX='++.o',LIBS=['rsf++','rsf','m'])
    cctest = proj.Flow('cc','clip++.exe',test % 'clip++',suffix='.attr',stdin=0)
    Default(cctest)

############################################################################
# Fortran-77 API
############################################################################

if 'fortran' in api:
    proj.Program('clip.f',OBJSUFFIX='f.o',LIBS=['rsff','rsf','m'],
                 LINK=proj.get('F77'),LINKFLAGS=proj.get('F77FLAGS'))
    ftest = proj.Flow('f','clipf.exe',test % 'clipf',suffix='.attr',stdin=0)
    Default(ftest)

############################################################################
# Fortran-90 API
############################################################################

if 'fortran-90' in api:
    proj.Program('clip.f90',PROGSUFFIX='f90.exe',LIBS=['rsff90','rsf','m'],
                 LINK=proj.get('F90'),LINKFLAGS=proj.get('F90FLAGS'))
    f90test = proj.Flow('f90','clipf90.exe',test % 'clipf90',
                        suffix='.attr',stdin=0)
    Default(f90test)

############################################################################
# Python API
############################################################################

if 'python' in api:
    pytest = proj.Flow('py','clippy.exe',
                       test % 'clippy',suffix='.attr',stdin=0)
    Default(pytest)

############################################################################

proj.End()
