###########################################################################
import sys, os

root = os.environ.get('RSFROOT')
libdir = os.path.join(root,'lib')
sys.path.append(libdir)

###########################################################################

import rsfproj

proj = rsfproj.Project()

############################################################################

test = 'spike n1=1000 n2=100 n3=10 nsp=1 k1=500 | %s.x clip=0.5 | attr'

############################################################################
# C API
############################################################################

cprog = proj.Program('clip.c')
ctest = proj.Flow('c',None,test % 'clip',suffix='.attr')
proj.Depends(ctest,cprog)
Default(ctest)

############################################################################

proj.End()
