from rsf.proj import *
#for shot in range(4,6297,4):
#Flow('tapl','Imag_0','window n1=20 | put o1=0 d1=1 n1=20 | math output="x1/20.0" | put d1=12.5')
#Flow('tapr','Imag_0','window n1=20 | put o1=0 d1=1 n1=20 | math output="(20.0-x1)/20.0" | put d1=12.5')
#Flow('tapm','Imag_0','window f1=40 | math output="1.0" ')
#Flow('tap','tapl tapm tapr','cat ${SOURCES[1:3]} axis=1')
#for shot in range(0,900,5):
imgs=[]
for shot in range(0,300,5):
    img = 'Imag_'+str(shot)
    imgpad = 'Pad_'+str(shot)
    Flow(imgpad,img,'pad beg1=%d end1=%d | window f1=800 n1=3617' %(shot,6116-shot))
    imgs.append(imgpad)
Flow('imgpad11',imgs,
     '''
     add ${SOURCES[1:60]}  
     ''')
imgs=[]
for shot in range(300,600,5):
    img = 'Imag_'+str(shot)
    imgpad = 'Pad_'+str(shot)
    Flow(imgpad,img,'pad beg1=%d end1=%d | window f1=800 n1=3617' %(shot,6116-shot))
    imgs.append(imgpad)
Flow('imgpad12',imgs,
     '''
     add ${SOURCES[1:60]}  
     ''')
imgs=[]
for shot in range(600,860,5):
    img = 'Imag_'+str(shot)
    imgpad = 'Pad_'+str(shot)
    Flow(imgpad,img,'pad beg1=%d end1=%d | window f1=800 n1=3617' %(shot,6116-shot))
    imgs.append(imgpad)
Flow('imgpad13',imgs,
     '''
     add ${SOURCES[1:52]}  
     ''')
Flow('imgpad1','imgpad11 imgpad12 imgpad13','add ${SOURCES[1:3]} | put o1=0 out=stdout')
imgs=[]
for shot in range(865,1800,5):
    img = 'Imag_'+str(shot)
    imgpad = 'Pad_'+str(shot)
    Flow(imgpad,img,'pad beg1=%d end1=%d | window f1=800 n1=3617' %(shot,6116-shot))
    imgs.append(imgpad)
Flow('imgpad2',imgs,
     '''
     add ${SOURCES[1:187]}  
     ''')
imgs=[]
for shot in range(1800,2700,5):
    img = 'Imag_'+str(shot)
    imgpad = 'Pad_'+str(shot)
    Flow(imgpad,img,'pad beg1=%d end1=%d | window f1=800 n1=3617' %(shot,6116-shot))
    imgs.append(imgpad)
Flow('imgpad3',imgs,
     '''
     add ${SOURCES[1:180]}  
     ''')
imgs=[]
for shot in range(2700,3600,5):
    img = 'Imag_'+str(shot)
    imgpad = 'Pad_'+str(shot)
    Flow(imgpad,img,'pad beg1=%d end1=%d | window f1=800 n1=3617' %(shot,6116-shot))
    imgs.append(imgpad)
Flow('imgpad4',imgs,
     '''
     add ${SOURCES[1:180]}  
     ''')
Flow('img_s','imgpad1 imgpad2 imgpad3 imgpad4','add ${SOURCES[1:4]} | put o1=0 out=stdout')
Flow('img_ps','img_s',
     '''
     laplace |
     pow pow2=1.5 out=stdout  
     ''')
#     agc rect1=400 rect2=400 out=stdout 
Result('img_ps',
       '''
       agc rect1=300 rect2=300 |
       grey poly=y label2="Depth" label1="Distance" title="VTI RTM Image"
       yreverse=y transp=n gainpanel=each pclip=99 unit1="km" unit2="km"
       screenratio=0.5 screenht=9 labelsz=6 titlesz=8
      ''')
Result('hvtiffdrtm','img_ps',
       '''
       agc rect1=300 rect2=300 |
       grey poly=y label2="Depth" label1="Distance" title="VTI RTM Image"
       yreverse=y transp=n gainpanel=each pclip=99 unit1="km" unit2="km"
       screenht=9 labelsz=6 titlesz=8
      ''')
End()





