from rsf.proj import *

Flow('make',None,'make n1=100 n2=20')
Flow('hole','make','hole')
Flow('pef mask0 lag','hole',
     '''
     hpef maskin=$SOURCE maskout=${TARGETS[1]}
     a=5,3 niter=100 lag=${TARGETS[2]}
     ''')
Flow('mask','mask0','dd type=float')
Flow('miss','hole pef',
     'miss padin=10 filt=${SOURCES[1]} niter=100')

title = {
    'make':'original',
    'hole':'gapped',
    'mask':'selector',
    'miss':'restored',
    }

for plot in title.keys():
    Plot(plot,'grey clip=.075 title="%s" wantaxis=n' % title[plot])

Result('hole','make hole miss mask','SideBySideAniso',vppen='txscale=2')

###########################################################################
End()
