from rsfproj import *

import os
private = {'login':os.environ.get('BEG_LOGIN'),
           'password':os.environ.get('BEG_PASSWORD'),
           'server':os.environ.get('BEG_SERVER')}

segy = 'calhon3d_Full_stack_enhance.sgy'
Fetch(segy,'calhoun',private)

Flow('cal cal.bin cal.asc tcal',segy,
     '''
     segyread bfile=${TARGETS[1]} hfile=${TARGETS[2]} tfile=${TARGETS[3]}
     ''')

#SUBLINE SPACING: 40 METERS
#XLINE SPACING:   25 METERS

Flow('bcal','cal','intbin xk=fldr yk=cdp')

Flow('line','bcal','window n2=1 min2=4220')
Flow('line2','line','window min1=1.6 max1=5 max2=1725')

Result('line2','grey wanttitle=n label1=Time unit1=s label2=Trace')

Flow('dip','line2','twodip2 eps=10 lam=10 verb=y')

for dip in range(2):
    Result('dip%d' % dip,'dip',
           '''
           window n3=1 f3=%d |
           grey title="Dip %d" scalebar=y color=j
           label1=Time unit1=s label2=Trace pclip=100
           barlabel="Dip (samples)"
           ''' % (dip,dip))


Flow('vg','line2 dip',
     'pwdsigk dips=${SOURCES[1]} verb=y nliter=2 niter=1000 eps=10')
Result('vg','stack axis=3 | grey wanttitle=n label1=Time unit1=s label2=Trace')

End()
